### ISSUE TITLE
Upgraded Angular 1.x component does not work when used in creating route(ng.upgrade)

### ISSUE THREAD

**Issue by mwaa** [angular/angular#10069]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] feature request
```

**Current behavior**

Upgraded Angular 1.x component does now work with angular component router, when used in router config. The following error is thrown 
`Error: Uncaught (in promise): Could not compile 'class4' because it is not a component` Please note the number 4 is based on how many components have been upgraded i think and changes based on how many components you have

**Expected/desired behavior**

I should be able to use upgraded components in router config and should work like other components. i.e route does not throw error when visited instead displays correct content.

**Reproduction of the problem**
The plunker url shows the error when you visit the link Angular1.x

http://plnkr.co/edit/nSAWZH

**Current work around this behavior.**
I have to create a new angular 2 component which uses the upgraded component as the template. This creates double work making upgrade pointless in the first place.

**What is the motivation / use case for changing the behavior?**
Slowly upgrading a large angular 1.x application to angular 2.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Angular router version:** 3.0.0-beta.2
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [TypeScript X.X]

**Comment by brandonroberts** [comment]
Fix the plunker to reproduce the issue.

**Comment by mwaa** [comment]
@brandonroberts should be fixed

**Comment by vicb** [comment]
is this still an issue ?

**Comment by mwaa** [comment]
@vicb will look into later after my work day. But from what i have checked of the code so far in above repo is that we use different strategies in creating the routes. 

@vsavkin uses the template of the component created i.e `<messages></messages>` which is the angular1 way of creating routes. While for my issue i used the upgraded component class i.e MessageComponent which is angular2 way of creating routes.

This said i will try with latest release version and give feedback in 24hrs time

**Comment by atscott** [comment]
Hi @mwaa, We're making a coordinated effort to triage and clean up our backlog of issues in GitHub. Can you create a reproduction using the most recent version of Angular to confirm that this is still an issue? Thanks!

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one for now given that we don't have any reproduce scenario with the recent Angular. Happy to re-open if / when we get a reproduce scenario.
