### ISSUE TITLE
Router: Services needing the Router service fail if OnDestroy is implemented

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#10770]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Services that implement the `OnDestroy` interface that are included in the root `NgModule` providers are automatically instantiated. If the service injects the `Router`, it throws an error.

`Error: Bootstrap at least one component before injecting Router`

**Expected/desired behavior**

Services injecting the router that implement the `OnDestroy` interface are instantiated without error.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/JQVPXQt62G2W56S84R5R?p=preview

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 

@MikeRyan52 @meenie @vsavkin

**Comment by meenie** [comment]
@brandonroberts Thanks for putting this together. I pretty much accepted that this is what it is and just deal with it haha.  Suppose it is good to pose the question to the team to see what they think.

**Comment by Delagen** [comment]
ngOnInit is the same effect

**Comment by azulinternet** [comment]
Alternatively, you can perform Router injection directly:

`constructor(private injector: Injector) {}`

`ngOnInit() {`
&nbsp;&nbsp;`this.injector.get(Router);`
`}`

**Comment by ersandeepranjit** [comment]
@azulinternet  does that solve the issue for you ?

**Comment by azulinternet** [comment]
I have no project with this scenario, @ersandeepranjit... just gave an alternative way to use the injector in any case. Apparently, does not solve, right? =/

**Comment by ersandeepranjit** [comment]
When will this be fixed as , AuthGuard Service could not be implemented without this ?

**Comment by brandonroberts** [comment]
This issue should be fixed once https://github.com/angular/angular/pull/11656/files lands

**Comment by ersandeepranjit** [comment]
@brandonroberts  has it fixed ? As per the issue #11656 is closed and mentioned as merged

**Comment by vicb** [comment]
it should be in 2.1-beta (2.0.1 is 2.0.0 + fixes while 2.1 receives new features)

**Comment by NathanWalker** [comment]
@vicb I just installed `2.1.0-beta.0` and this issue still exists :(  Am I missing something?
```
Bootstrap at least one component before injecting Router.
```
![screen shot 2016-09-27 at 1 52 08 pm](https://cloud.githubusercontent.com/assets/457187/18891339/a339314e-84b9-11e6-9e28-e91483e37bbb.png)

**Comment by ersandeepranjit** [comment]
@NathanWalker, Is that Issue due to the AuthService, If it is then you might be using ngOnInit method in AuthService, which was troubling in my case, I removed it  and it just worked

**Comment by brandonroberts** [comment]
@ersandeepranjit @NathanWalker you probably need to upgrade to latest router beta also which is `3.1.0-beta.0`

**Comment by vicb** [comment]
thanks @brandonroberts I forgot to mention the router veriosn

**Comment by NathanWalker** [comment]
Thank you @brandonroberts ! That was exactly it. Had not updated that one package.
Whew! Works great now. Wish this were officially released 👍   Such a critical bug fix :-0
