### ISSUE TITLE
Lazy load auxilary

### ISSUE THREAD

**Issue by michalstepien** [angular/angular#10981]
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/YmsQ4L1KKVPnRn72pq6N?p=preview

**What is the expected behavior?**

Can do this:

`RouterModule.forChild([
            {
                path: '', component: OffersDelete, outlet: 'actions'
            }
])`

**What is the motivation / use case for changing the behavior?**

If you have multiple modules that are triggered by aux routing always You have to create a fake component to operate the first route

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.X
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by vsavkin** [comment]
Doesn't seem to be an issue in RC6. Check after RC6 is out.

**Comment by maxime1992** [comment]
I don't like to ask for an ETA but this issue is opened since august and it's really a problem to not be able to use auxiliary routes (within a lazy loaded module). 

Is there any chance someone looks into it?

**Comment by victornoel** [comment]
Any news on that?

It seems #13807 has a complete plunkr to repro this issue :)

What can we do to help fix it? :)

**Comment by SoulOnFire** [comment]
I have the same problem. Lazy modules don't work on aux routes

**Comment by JL-ConcepT** [comment]
Any updates on this problem?

**Comment by maxime1992** [comment]
It seems that lazy load and auxiliary routes are not widely used together.
We can see a lot of demos, separated but that's it. **It's like no one uses it in a medium/large app** :open_mouth: 

These 2 are killer functionalities and no one seems to care about that issue ¯\\\_(ツ)_/¯
It's been **nearly 8 months now**.

_I don't want to put pressure on anyone and I know it's open source. So instead of asking for ETA someone should try to implement it. But the router doesn't seem to be the better things to start digging for the first time in Angular code base. Especially for an issue with lazy loading and auxiliary routes._

That said, I hope someone can take a look into that and I'm sure the 21 people who put a :+1: [on my comment](https://github.com/angular/angular/issues/10981#issuecomment-271164211) would send kudos to our savior :angel: :heart: 

PS : I also created a [stackoverflow question](http://stackoverflow.com/questions/42022382/angular2-routing-on-lazy-loaded-module-with-multiple-named-outlets/42023015#comment73703763_42023015) (when I thought I was missing something instead of a bug) and it has +100 views.

**Comment by vivanov-dp** [comment]
I don't think it wouldn't be wide used if it worked.

I have the same problem, using Angular@4.0.3 and I have to move forward, so I'm moving the component in question out to it's own separate module with no children paths, to be able to display it in the aux outlet, hopefully lazy-loaded. If that doesn't work I will even make it load normally.

When this is fixed I might change it back, if I have time

**Comment by chrisalexander55** [comment]
Huge chest bump to the Angular team but unfortunately I have to agree. I think the bar was set relatively low by targeting simple router-based apps with named outlets sprinkled in. Not only is lazy routing with named outlets not supported at this time but there is zero guidance on memory management (i.e. module unloading). Hopefully, this will be picked up for NG 5 or a patch. Angular team and community still rock in my world! 👍

**Comment by gtzinos** [comment]
Hello, any workaround to fix this issue ?

**Comment by maxime1992** [comment]
@gtzinos I tried to ask on [Twitter](https://twitter.com/sizerOne/status/862575475314610177) this morning because I don't know what to do either after 8 months but no luck nor workaround yet

**Comment by nekkon** [comment]
So far I have not found a working demo with lazy loading in a named router outlet e.x. <router-outlet name="view"></router-outlet>. I have made a plunkr to find a way to make it work without success. Any help would be much appreciated.

https://plnkr.co/edit/EW3PZUMC63euf2QYxtW5?p=preview

In the example above View1, View2 and View3 are lazy loaded in the default router-outlet. View3_1 and View3_2 are lazy loaded in the named router-outlet without success.

**Comment by KeithGillette** [comment]
After much frustrating experimentation, I have had success getting lazy-loaded modules to use named router-outlets in an Angular 4.1.0 project with the following module hierarchy and routing configuration.

Below is the module and routing hierarchy followed the route configuration for the first three modules, which required a number of componentless parent routes:

- **`AppModule`** '/' AppComponent <router-outlet>
	- **`StartModule`** (eager): '/start', StartComponent
		- '/start/sign-in', SignInComponent
		- 'start-register', RegisterComponent
    - **`MainModule`** (lazy): '/main', MainComponent <router-outlet>
	- **`LibraryModule`** (lazy): '/main/library', LibraryComponent: <router-outlet><router-outlet name="detail">
		- '/main/library/:manualId'
		- '/main/library/:manualId/:sectionId'
		- '/main/library/:manualId/:sectionId/:procedureId'
		- '/main/library/:manualId/:sectionId/:procedureId/:procedureStepId'
		- '/main/library/:manualId/:sectionId/:procedureId/:procedureStepId/:contentId'
	- **`AssignmentModule`** (lazy): InboxComponent: <router-outlet><router-outlet name="detail">
		- '/main/inbox/:assignmentId'
		- '/main/inbox/:assignmentId/:taskId'
		- '/main/inbox/:assignmentId/:taskId/content/:contentId'
		- '/main/inbox/:assignmentId/:taskId/comment/:commentId'
		- '/main/inbox/:assignmentId/:taskId/feedback/:feedbackId'
    - **`ExchangeModule`** (lazy): ExchangeComponent <router-outlet>


**AppRoutingModule:**
```typescript
	const routes: Routes = [
		{ path: '', redirectTo: 'start', pathMatch: 'full' },
		{ path: 'main', loadChildren: './main/main.module#MainModule' },
		{ path: '**', redirectTo: 'start' }
	];
```
**MainRoutingModule:**
```typescript
	const routes: Routes = [
		{
			path: '', component: MainComponent,
			canActivate: [MainRoutingGuardService],
			children: [
				{path: '', redirectTo: 'library', pathMatch: 'full'}, // @ToDo: change default path to 'inbox' when InboxModule developed
				{path: 'library', loadChildren: '../../library/library.module#LibraryModule'}
			]
		}];
```
**LibraryRoutingModule:**
```typescript
	const routes: Routes = [
		{	path: '',	component: LibraryComponent, children: [
			{ path: ':manualId/:manualSectionId', children: [
				{ path: '', component: ProcedureListComponent },
				{ path: '', component: ManualDetailComponent, outlet: 'detail' },
			]},
			{ path: ':manualId/:manualSectionId/:procedureId', children: [
				{ path: '', component: ProcedureListComponent },
				{ path: '', component: ProcedureDetailComponent, outlet: 'detail' },
			]},
			{ path: ':manualId/:manualSectionId/:procedureId/:procedureStepId', children: [
				{ path: '', component: ProcedureStepListComponent },
				{ path: '', component: ProcedureStepDetailComponent, outlet: 'detail' },
			]},
			{ path: ':manualId/:manualSectionId/:procedureId/:procedureStepId/:contentId', children: [
				{ path: '', component: ProcedureStepListComponent },
				{ path: '', component: ProcedureStepDetailComponent, outlet: 'detail' },
			]},
		]}
	];
```

**Comment by maxime1992** [comment]
@KeithGillette what did you do exactly to make it work ? Did you have to change anything or is it just working since 4.1.x ? My demo [plunkr](http://plnkr.co/edit/TiwzIoR8t57yRrx8zpaQ?p=preview) which is now running on 4.1.2 is still not working.

**Comment by KeithGillette** [comment]
Hi @maxime1992. I had not tried to get this working prior to using Angular 4.1.0. Things that tripped me up along the way:

- leaving the lazy-loaded modules in the `AppModule` imports
- attempting to make the route entries with the named outlets direct children of the path loading the component with the primary and named auxiliary router-outlets.
- attempting to name the paths containing the components to load into said router-outlets

On the last two points, note the "extra" componentless route that contains the actual path and groups the unnamed child routes that actually load into the component specified in the unnamed parent route.

**Comment by nekkon** [comment]
@KeithGillette Where exactly is the outlet named detail? Is is it in LibraryComponent?

**Comment by KeithGillette** [comment]
Correct, @nekkon. Sorry, I hadn't noticed that the Github markdown wasn't displaying the router outlet definitions in the module and routing hierarchy I included in my original post. I corrected the markdown to display the router outlets associated with each component.

**Comment by royling** [comment]
@KeithGillette I noticed that the detail outlet are all with an empty path:
```js
{ path: '', component: ProcedureDetailComponent, outlet: 'detail' },
```

As I tried, this does work. But for a non-empty path, it's not working. That's the problem @maxime1992 has reported in the plunkr.

**Comment by KeithGillette** [comment]
Hi, @royling. You are correct, though the path does in effect have a unique name from its componentless parent, which is the only way I could get named outlets to work.

The original post reported that in lazy-loaded modules "[y]ou have to create a fake component to operate the first route" and others on the thread seem unable to get named routing outlets to work in lazy-loaded modules at all. I'm not sure I fully understand the original poster's issue, but in my case, I found no need for fake components to get named outlets in nested lazy-loaded modules to work _if_ they were empty-path child routes of a componentless route, a work-around (unless this is the design?) which may be helpful at least to the others unable to get auxiliary routes working at all.

**Comment by royling** [comment]
@KeithGillette this workaround is helpful only for the scenario that you want to always load the component in the auxiliary outlet. But if you would like to load different routes into this outlet conditionally, you have to name other routes with unique paths, that will not work. I think that's a common use case.

**Comment by KeithGillette** [comment]
I'm not following you, @royling. As I understand it, paths don't load in outlets, components load in outlets based on the path.

Using the work-around I posted, I can load arbitrary components (or no components at all) into both the primary and named auxiliary outlets conditionally based on unique path, so long as that unique path is specified in a componentless parent route, with the components to load in the given outlets specified as pathless child routes of that uniquely named componentless parent route, as shown.

**Comment by jonesmac** [comment]
@KeithGillette you are my hero.  After 3 hours of fighting I stumbled across this post.  Sure enough, I was trying to use a named router outlet on the root component of a lazy-loaded module and found myself down the rabbit hole!  I can confirm as well that if you add the outlet entry as a child of a named(!) route all works as expected.

**Broken**
```javascript
{
    path: '',
    component: ScheduleContainerComponent,
    resolve: {
      loops: LoopsResolve
    },
    children: [
      {
        path: 'addloop',
        component: AddLoopComponent,
        outlet: 'overlay'
      }
    ],
},
```

**Fixed**
```javascript
{
    path: '',
    resolve: {
      loops: LoopsResolve
    },
    children: [
      {
        path: 'show',
        component: ScheduleContainerComponent,
        children: [
          {
            path: 'addloop',
            component: AddLoopComponent,
            outlet: 'overlay'
          },
        ]
      },
    ],
  },
```

This makes absolutely no sense and I could find no examples of documentation that explains that this exists or a workaround.

**Comment by royling** [comment]
@KeithGillette yes, you are right and the workaround is OK. Thanks!
- >so long as that unique path is specified in a componentless parent route
- >the given outlets specified as pathless child routes of that uniquely named componentless parent route

**Comment by jonesmac** [comment]
@royling I'm wondering if you tested trying to remove the secondary route component?
Something like:
`{ outlets: { aux: null } }`

I tried it and that part is still broken for me even with the workaround.  Can you let me know if it works for you?  I eventually had to move on with a different solution altogether because of this but wanted someone else to verify.

**Comment by Artur93gev** [comment]
Hi
I have the same issue as mentioned in this post. I have two different applications that need usage of this.I've a question how will the router recognize the route by URL if the named router outlet is not dropping in it?

P.S.
 Till today I was thinking that the Angular architecture not allows this. I thought that this is some like an external small application case in your whole application that must be initialized from the start

**Comment by KeithGillette** [comment]
@jonesmac, I don't think that syntax will work. If you don't want a component to appear in a named secondary/auxiliary outlet, just don't include it as a child route for the given path. In my work-around example,  for any given componentless parent route that you did not want the named outlet filled, you'd just omit the entire second child route entry that specifies the outlet name.

**Comment by KeithGillette** [comment]
@Artur93gev, as [shown in my work-around example](https://github.com/angular/angular/issues/10981#issuecomment-301787482), the path is provided to the Angular router in the componentless parent path. Its pathless child routes then tell the router what to display in the primary and named/secondary router outlets.

**Comment by royling** [comment]
@jonesmac good catch, I also failed to remove the aux outlet...

**Comment by marslan2037** [comment]
any update on this issue?

**Comment by liuweireign** [comment]
same problem. any new information?

**Comment by kentoj** [comment]
I confirm @KeithGillette's solution and @royling's clarifications. I am using angular 4.0.1.

I had success using a blank, parent, component-less route like shown by @jonesmac, then register the original child module root component under a new unique name as a child route of the blank route then things should work.

Also be aware of the more complex `[routerLink]` syntax.

**Parent HTML**
```html
<div>
  <router-outlet></router-outlet>
</div>
```

**Parent Routing Config**
```typescript
const rootRoutes: Routes = [
  {
    path: 'submodule1',
    loadChildren: 'app/submodule1/sub1.module#SubModule1'
  }];
```

**Child HTML**
```html
<h1>Inner Router</h1>
<router-outlet name="childoutlet"></router-outlet>
```

**Example lazy-loaded, child module routes**
```typescript
const childModuleRoutes: Routes = [
  {
    path: '',
    children: [
      {
        path: 'unique-child-route', component: SubmoduleHomeComponent,
        children: [
          { path: 'sub-component1-route', component: SubComponent1, outlet: 'childoutlet' },
          { path: 'sub-component2-route', component: SubComponent2, outlet: 'childoutlet' }
        ]
      },
      { path: '**', redirectTo: 'unique-child-route' }
    ]
  }
];
```

**Child Navigation Bar**
```html
<div class="ui menu">
  <div class="header item">
    SubModule Nav
  </div>
  <a class="item" [routerLink]="[{outlets: {childoutlet:'sub-component1-route'}}]">SubComponent1</a>
  <a class="item" [routerLink]="[{outlets: {childoutlet:'sub-component2-route'}}]" [routerLinkActive]="['active']">SubComponent2</a>
</div>
```

**Comment by gtzinos** [comment]
@nekkon

**Comment by jonesmac** [comment]
@kentoj were you able to set the secondary outlet to null?  I [wasn't](https://github.com/angular/angular/issues/10981#issuecomment-303104660) able to get this part to work.

**Comment by gtzinos** [comment]
Guys if you will stop using the named outlets (just without names) it working fine.

**Comment by kentoj** [comment]
@jonesmac I never tried setting it to null explicitly though I may have done so incidentally by leaving it out of the **outlets** declaration in the `[routerLink]` directive declaration.

**Comment by dmitrysteblyuk** [comment]
May this issue finally get addressed after one year of waiting?
The way I see it, the suggested workaround works only to some extent (there's a way to navigate to a named outlet but there's no way to go back by setting it to null).

**Comment by Sntax** [comment]
I'm somewhat baffled that this is still an open issue... wow.

**Comment by maxime1992** [comment]
**1 year! Happy birthday**! :cake: :birthday: :gift: :balloon: :tada:!!!!

![image](https://user-images.githubusercontent.com/4950209/29555690-b90c7504-8723-11e7-841a-084566fb59c7.png)

Seriously, I don't understand why this issue is so underrated...
Barely 20 people uses those functionalities together?!

@kara, sorry to ping but vsavkin removed his assignment on this issue and it seems you're the only one from the Angular team. Do you think you might take a look or share it with someone who might? Thanks :smile:

**Comment by theivanaguilar** [comment]
It would be awesome to have this fixed before the 2 years celebration 😆

**Comment by duluca** [comment]
I've forked @maxime1992's plnkr, and made it a bit more obvious what's working and what's not working as a repro: http://plnkr.co/edit/9XC0AsHo6mJQN59h27vH?p=preview

Given below HTML for the lazy loaded module default template: 
```html
    <div>
      <router-outlet></router-outlet>
      <router-outlet name="aux"></router-outlet>
    </div>
```

Given below child routes defined within the lazy loaded module: 
```js
const routes = [
  {
    path: '',
    component: LazyLoadedComponent,
    children: [
      {
        path: '',
        component: NonAuxComponent
      },
      {
        path: '', // this works on load, when going to the root /lazy route
        component: AuxComponent,
        outlet: 'aux'
      },
      {
        path: 'auxpath', // this does not work
        component: Aux2Component,
        outlet: 'aux2'
      }
    ]
  }
]
```

When navigated to route `/lazy` using `routerLink="lazy"`
- NonAuxComponent renders successfully in the *primary* outlet
- AuxComponent renders successfully in the *aux* outlet

When navigated to route `/lazy/(aux:auxpath)` using `[routerLink]="[{ outlets: { aux: 'auxpath' } }]`:
- Nothing happens. NonAux and Aux components remain rendered. The URL doesn't change.
- **Expected Behavior**: URL should change to `/lazy/(aux:auxpath)` and AuxComponent should be replaced by Aux2Component

**Comment by royling** [comment]
See this aged bug #10726 about the aux routes with top-level empty path in routing module...

**Comment by indranilmaiti** [comment]
Will it ever be solved?

**Comment by seaBubble** [comment]
Running into the same issue, it would be nice to get it fixed.

**Comment by photostu** [comment]
Chalk me up as another user that needs to lazy load a secondary route and component combo.

**Comment by duluca** [comment]
I struggled with this again for a bit, and I'm not convinced that there's a bug. Perhaps an issue of documentation. I'm working on a Hands On Angular book. I've created a sample project that demonstrates the concept in use [here](https://github.com/duluca/lemon-mart).

Given the Parent Component and the Router Config below, notice that the routerLink only specifies the detail outlet. When I originally tried to redefine the master outlet in the link, the link simply wouldn't do anything. 

_Perhaps this is the issue everyone is running into?_

## Parent Component
[user-management.component.ts](https://github.com/duluca/lemon-mart/blob/master/src/app/manager/user-management/user-management.component.ts)
```
...
  template: `
    <div class="horizontal-padding">
      <router-outlet name="master"></router-outlet>
      <div style="min-height: 10px"></div>
      <router-outlet name="detail"></router-outlet>
    </div>
  `,
...
```

## Routing Config
[manager-routing.module.ts](https://github.com/duluca/lemon-mart/blob/master/src/app/manager/manager-routing.module.ts)
```
...
const routes: Routes = [
  {
    path: '',
    component: ManagerComponent,
    children: [
      { path: '', redirectTo: '/manager/home', pathMatch: 'full' },
      {
        path: 'home',
        component: ManagerHomeComponent,
        canActivate: [AuthGuard],
        data: {
          expectedRole: Role.Manager,
        },
      },
      {
        path: 'users',
        component: UserManagementComponent,
        children: [
          { path: '', component: UserTableComponent, outlet: 'master' },
          {
            path: 'user',
            component: ViewUserComponent,
            outlet: 'detail',
            resolve: {
              user: UserResolve,
            },
          },
        ],
        canActivate: [AuthGuard],
        canActivateChild: [AuthGuard],
        data: {
          expectedRole: Role.Manager,
        },
      },
      { path: 'receipts', component: ReceiptLookupComponent },
    ],
  },
]
...
```

## Navigation 
[user-table.component.html](https://github.com/duluca/lemon-mart/blob/master/src/app/manager/user-table/user-table.component.html)
```
...
<a mat-button mat-icon-button [routerLink]="['/manager/users', { outlets: { detail: ['user', {userId: row.id}] } }]" skipLocationChange>
  <mat-icon>visibility</mat-icon>
</a>
...
```

**Comment by photostu** [comment]
I found this in another thread and solved my problem just fine:

https://github.com/angular/angular/issues/12842#issuecomment-270836368

**Comment by duluca** [comment]
@photostu just to be clear, you had to specify a route for the "master/primary" outlet? In your config, does your "master/primary" have a default (i.e. empty) `''` route as mine does above?

**Comment by photostu** [comment]
This is what my root level routing looks like:
`[
  { path: '', redirectTo: '/recipe', pathMatch: 'full' },
  {
    path: 'recipe',
    loadChildren: './recipe/recipe.module#RecipeModule'
  },
  {
    path: 'cart',
    outlet:'sidebar',
    component: ProxyRouteComponent,
    children:[
        {
            path:'',
            loadChildren: './cart/cart.module#CartModule'
        }
    ]
  },
//   { path: '**', component: NotFoundPageComponent },
];`

using this I can call a route of /#/recipe(sidebar:cart) and get 2 distinct modules loaded to 2 different router-outlets

**Comment by elclanrs** [comment]
I've been reading this thread for a while, and I'm not sure if this is working fine or not. If I leave the lazy route empty, then outlets seem to work fine. This is my config:

```
// app-routing.module.ts

const appRoutes = [
  {
    path: '',
    loadChildren: './path/to/my-component.module#MyComponentModule'
  },
  ...
]
```

```
// my-component-routing.module.ts

const componentRoutes = [
  {
    path: 'my-component',
    component: MyComponent,
    children: [
      {
        path: 'child',
        outlet: 'aux',
        component: ChildComponent
      }
    ]
  }
]
```

**Comment by olegshestakov** [comment]
Please fix this issue

**Comment by knlambert** [comment]
Same problem here. It's pretty ugly compared to the global quality of angular.

**Comment by royling** [comment]
@elclanrs that could work in a single lazy loaded module case, what if you have multiple lazy loaded modules? I don't think it works.

**Comment by elclanrs** [comment]
@royling, seems to work with multiple lazy loaded modules too.

**Comment by theivanaguilar** [comment]
For anyone with this issue, a workaround is to create a component that uses the `Router` module to handle the redirection manually in the empty route.

It's ugly, it's not optimal, but unfortunately it's the only thing that works (at least for me) in this situation, and does not crash the app when refreshing on that route.

**Comment by montella1507** [comment]
it is ridiculous that they are talking about quality on conferences and noone cares about this elementary problem with router.. Angular Material + Angular Router, i will not wonder if there are 2 groups of developers, because quality of Material/Router is terrible compared to angular.

**Comment by royling** [comment]
@elclanrs thanks, good to know that, then this looks like another workaround...

**Comment by SerkanSipahi** [comment]
Please please fix this issue !!!

**Comment by netwobble** [comment]
I'm sure this is a common request for med to larger applications. Constrained to one router outlet OR give up lazy loading.  This does not seem like a great compromise.  I see a lot of great things coming with each release but we need core functionality to be fixed.

**Comment by SerkanSipahi** [comment]
Good news from @IgorMinar https://twitter.com/IgorMinar/status/976727622964031488

##### Twitter
>Bitcollage: hi there, i hope you can hear me despite the huge twitter rush!There is since 2 years a named router outlet bug (https://goo.gl/Gy63e8 ) in combination with "lazyLoad modules"! Is there a plan to fix that issue? Personally i have not the skills for that! #Angular

>IgorMinar: I bumped up the priority on that issue. We'll need @jasonaden1 to take a look after he's done with his current RxJS work. Thanks for highlighting this issue.

##### Backlog
The issue is also labeled (by Igor) an hour ago from `medium` to `high` :)

I hope so that will be fixed in shortly :)

**Comment by sharpdevel** [comment]
Perhaps one more hint:

With the following route definition:

`export const ROUTES: Routes = [{ path: 'server-worker/create-job', component: CreateJobComponent, outlet: 'details-outlet' }];`

and using it like:

`this.router.navigate([{outlets: {'details-outlet': ['server-worker/job-details']}} ]);`

won't work because the "/" is escaped to "%2F"

When lazy loading modules like:

`export const ROUTES: Routes = [{ path: 'server-worker', loadChildren: './modules/server-worker/server-worker.module#ServerWorkerModule' }];`

we automatically introduce a relative path which would destroy the "router.navigate" command like above.

**Comment by Brampage** [comment]
Hello... any updates? It's still not working.

**Comment by tibinthomas** [comment]
I'm also facing the same issue.

**Comment by SerkanSipahi** [comment]
@IgorMinar sorry that we bother you. Any updates about that issue here?

**Comment by jasonaden** [comment]
Just merged #23459 to fix this long-standing issue. If you experience any problems or there are remaining outstanding use cases that aren't fixed, please create a *new* issue and reference this issue.

**Comment by gtzinos** [comment]
@nekkon

**Comment by andrewjrhill** [comment]
![382](https://user-images.githubusercontent.com/3358672/41406657-3f9ecbf2-6fcd-11e8-8936-e47d8ed38775.gif)

**Comment by montella1507** [comment]
I am so excited.. I have been starting my every day  with checking this issue for last 2 years if it is fixed.. What would I do now? My life is complete yet.Thank you

**Comment by codefactorydevelopment** [comment]
Did anyone get this to work with angular6.x?

just trying to use named routed in lazy loaded module but without success. getting same errors as before.

**Comment by vottens** [comment]
I've tried it today without any luck! Someone else?

**Comment by SerkanSipahi** [comment]
I think he merged into master and it should be released in shortly.

**Comment by vottens** [comment]
I've tried to load aux routes with version 6.0.5 and with 6.1.0-beta.0. The change log says that these issues are solved, but i still can not get it to work. Any one else tried this?

**Comment by TomDemulierChevret** [comment]
Read the [Changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md), the fix has only been included in 6.1.0-beta.**1**. ;)

**Comment by vottens** [comment]
@TomDemulierChevret 6.1.0-beta.0 was a typo, i meant 6.1.0-beta.1. 
I have made a test setup with the beta version. 
https://stackblitz.com/edit/lazy-load-auxilary
It's not working!

**Comment by TomDemulierChevret** [comment]
#23459 did not fix the issue presented in your stackblitz but another one.

It seems fixed situations with routing like this : 
```{
    path: 'test',
    component: Component,
    children: [
      {
        path: 'aux1',
        component: Aux1Component,
        loadChildren: 'pathToTheModule'
      }
    ]
  }
```

**Comment by codefactorydevelopment** [comment]
i'll drop a question here as there is tremendeous amount of confusion around this topic for a long period of time...

is there a way to have named router and auxiliary route completely defined within lazy loaded module?

so, route, outlet, component...everything in lazy loaded module, nothing in core module.

**Comment by vottens** [comment]
That's probably the case, but that means that there is still a bug with loading aux routes from within lazy modules...

**Comment by codefactorydevelopment** [comment]
@vottens
of course. i have a few usecases where not having this feature forces us into some pretty ugly workarounds.

**Comment by asmith2306** [comment]
I got this to work in Angular v 6.1.0 with @kentoj example.  Was banging my head against the wall for a while.  Working now.  Thanks.

**Comment by luckylooke** [comment]
I was able to make auxiliary lazy loaded routes to work ([see demo](https://stackblitz.com/edit/angular-multiple-outlet-v2-lazy?embed=1&file=src/app/viewport/viewport-routing.module.ts)), but I have no luck to setup default route, my scenario is a bit complicated as I am using two "equal" auxiliary outlets, left and right. Think of them as total-commander setup. All children components can appear on left or right. Everything is working for now, except the default route. I am getting unexpected result with redirectTo property.. as I would expect when specifying  `redirectTo:"person"` path to be relatively redirected into `/(mySide:person)`, but instead it redirects to `/person`. Which is pretty much the same when I use `redirectTo:"/person"`. But IMHO this should be differentiated, and so redirect should be resolved relatively, when omitting `/`. I have written more on [SO](https://stackoverflow.com/questions/52520221/default-route-redirect-not-working-for-lazy-loaded-routes-in-angular-2) for anyone interested. Anyway, thanks for your excellent work on this framework I am really enjoying to work with. Happy coding! :)

**Comment by luckylooke** [comment]
There is a problem even in less complex [example](https://stackblitz.com/edit/angular-routing222-gyofle?embed=1&file=src/app/main/main.routing.module.ts). Auxiliary route cannot be navigated at all. same [example but moving the aux route](https://stackblitz.com/edit/angular-routing222-iasisx?embed=1&file=src/app/main/main.routing.module.ts) behind named (sagmented) route, now it works! But it certainly should be working also for default routes. Many thanks for looking into issue in advance :)

**Comment by BenRacicot** [comment]
@luckylooke It may be SB but I can't see any lazy-loading going on in any of those examples. I believe any lazy loaded feature would need to have an ng-module. Otherwise it wouldn't be packed up by the CLI as a feature module. I too am roadblocked without being able to lazy-load components without the router.

**Comment by luckylooke** [comment]
@BenRacicot yes, in last comment I am showing that it is even not lazy loading related. I present that for breaking auxiliary navigation it is just enough to have it under nonamed route in root.

**Comment by lakinduakash** [comment]
I have two router outlets in my application. One is the primary router outlet and other router outlet is in component template which is loaded with lazy loaded module. Name of the router outlet is `pr` and I have defined path for that route inside the lazy loaded module like this 

`{outlet:'pr',path: 'students', component: StudentTableComponent, canActivate: [AuthGuard]}`

Inside the component I have router link with this.

 

    <button mat-button mat-stroked-button 
    [routerLink]="[{ outlets: { pr:'students'} }]">View Students
     </button>

In the same component I have put the `<router-outlet name="pr"></router-outlet>`. After clicking the link app is correctly navigated showing `project/132/(pr:students)`. No errors appears ,although not showing the component. If I put the router outlet in the main component which have primary outlet it loads. Ex: 

    <router-outlet></router-outlet>
    
    <router-outlet name="pr"></router-outlet>
But after moving outlet elsewhere Angular won't identify the outlet

**Comment by lakinduakash** [comment]
I think this is the same issue right?

**Comment by samfrach** [comment]
@luckylooke : why do you use your ProxyComponent twice ? Therefore you have twice : <router-outlet></router-outlet>

**Comment by samfrach** [comment]
Dear all,

I want to use a outlet named "modal" anywhere in my application .... the main reason is to be able to bookmark the primary URL with the modal window ...

I have a lazy loaded module "ProductsModule" that manages products... 
I would like to open a product in my "modal" outlet from anywhere....

The primary outlet URL can be /A/xxx /B/yyy or whatever... I should be able to add "url(modal:/product/33)"

It works great with lazy module.... 
I define a path for /product/:id with outlet modal at the routing for routes... 

But .... when I want a lazy module... it's dead... 

any idea ? should I give an example or it is understandable ?

**Comment by henrique-barreto** [comment]
Still not working...

**Comment by javix** [comment]
Why was this issue closed?

**Comment by squelix** [comment]
Is it fixed ? In which version number ?

**Comment by BenRacicot** [comment]
Is there a StackBlitz example of what isn't working?
http://plnkr.co/edit/YmsQ4L1KKVPnRn72pq6N?p=preview is full of errors

**Comment by domenichelfenstein** [comment]
I just wanted to say this issue isn't resolved at all.

For everyone wanting to reproduce the problem:
This is working but without Lazy-Loading: https://stackblitz.com/edit/outlet-problem-eager
This is not working but has Lazy-Loading: https://stackblitz.com/edit/outlet-problem-lazy

**Comment by vottens** [comment]
Hi @domenichelfenstein 

[https://stackblitz.com/edit/outlet-problem-lazy-sigxxx](https://stackblitz.com/edit/outlet-problem-lazy-sigxxx)

I made a change to your stackblitz app, know it works!
You have to give your lazy module a named default route, otherwise it won't work.
This is a workarround!

Gr Vincent

**Comment by digeomel** [comment]
I am not sure if this is related, but I just wasted days trying to find a solution to my problem and I stumbled upon the solution by trial and error, so here's how I made it work in my case. I'm working with Angular 7, Router is 7.2.11.

Apparently there's a difference between this:

``this.router.navigate(['/a/b', param1, { outlets: { secondary: ['c', param2] } }]);``

and this:

``this.router.navigate([{ outlets: { primary: ['/a/b', param1], secondary: ['c', param2] } }]);``

The first one results in a URL like:

``/a/b/1/(secondary:c/2)``

which works fine, but the 2nd one results in a URL like:

``/a/b/1(secondary:c/2)``

which fails. Notice that the difference between the 2 URLs is the slash **/** between the end of the primary route and the beginning of the secondary route.

**Comment by brgrz** [comment]
@jasonaden Why was this closed because it is still an open issue, as is this https://github.com/angular/angular/issues/23791 and a couple of other issues referenced throughout this thread? Nested routes with outlets at various levels is a crippling issue in Angular and at least for me currently a roadblock -- because everything boils down to hours of trial and error trying to get even basic 2 level scenarios to work.

**Comment by thackerc** [comment]
@digeomel What do your routes look like?

**Comment by tburger** [comment]
I got close but when I navigate, the named outlet is filling but the primary outlet is being cleared.  I don't want the primary outlet to change.

The html
<router-outlet></router-outlet>
<router-outlet name="dialogOutlet"></router-outlet>

The route:
 {    
    path: 'packoutdialog'
    , children:[
      {path:'', outlet:'dialogOutlet', component: PackoutComponent}]
     
  },

Either of these will fill the dialogOutlet but clear the primary
 this.router.navigate(['inventory', 'packoutedialog'])
this.router.navigate(['packoutdialog',{outlets:{'dialogOutlet':[]}}],{skipLocationChange: true, relativeTo: this.activatedRoute.parent});


This seems like it should work but does not.
this.router.navigate([{outlets:{'dialogOutlet':['inventory','packoutdialog']}}])

**Comment by matheo** [comment]
Thanks @digeomel 
You saved me some hair :)

`/primary/route/(secondary:path/id)` works
so I had to trial and error until I get the correct routing array to resolve the primary component correctly.

Also, it seems that the named route needs to match the request exactly, it doesn't match a segment. And I couldn't load a lazy-loaded module in this secondary route, the Router doesn't load component matching the route.

I debugged with `RouterModule.forRoot(routes, { enableTracing: true });` in my AppModule and it finds the lazy loaded component, but `router-outlet name="secondary"` only renders an empty ng-component :(

**Comment by maxime1992** [comment]
Patching the following changes directly into the compiled version of the router (from node_modules) completely fixed the issue for me :raised_hands: https://github.com/angular/angular/pull/25483

It's definitely **not** the right way of doing things but it feels so much simpler in that case than breaking some of my routes or have non empty routes for a workaround.

I hope that PR gets merged at some point.

**Comment by inthegarage** [comment]
I created a further stackblitz as a further playground for this issue.  Please fork it as you wish.

https://stackblitz.com/edit/angular-router-auxilary-issue

It moves between panel b and c in panel a. Thanks to several posters here it has helped solve my panel in panel problem.

**Comment by Jonathan002** [comment]
Hey guys, I've created a workaround for loading a lazy module's component through custom named outlets routing. Please have a look and hope this is useful.

Repo: https://github.com/Jonathan002/route-master-example

**Comment by jayoungers** [comment]
I have a menu that opens modal windows, where each could contain quite a bit of code: my goal was to lazy load the modals on demand when needed, which I was able to get to work like so:

app.component:
```html
    <router-outlet></router-outlet>
    <router-outlet name="modal"></router-outlet>
```
link:
```html
<a [routerLink]="['', { outlets: { modal: ['tools', 'view-stuff'] } }]">View Stuff</a>
```
added this to the root routes:
```ts
{
  path: 'tools',
  outlet: 'modal',
  children: [
    {
      path: 'view-stuff',
      loadChildren: () => import('app/tools/view-stuff/tools-view-stuff.module').then(m => m.ToolsViewStuffModule)
    }
  ]
}
```
view-stuff-module
```ts
@Component({
  selector: 'app-view-stuff-launcher-component',
  template: ''
})
export class ToolsViewStuffLauncherComponent implements OnInit {
  constructor(private modalService: ModalService) {}

  ngOnInit() {
    this.modalService.open(ToolsViewStuffModalComponent);
  }
}

const routes: Routes = [
  {
    path: '',
    component: ToolsViewStuffLauncherComponent
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes), CommonModule, SharedModule],
  providers: [ModalService],
  declarations: [ToolsViewStuffLauncherComponent, ToolsViewStuffModalComponent],
  entryComponents: [ToolsViewStuffModalComponent]
})
export class ToolsViewStuffModule {}
```

**Comment by BenRacicot** [comment]
@jayoungers that is awesome! Could you setup a StackBlitz for us?

**Comment by asvishnyakov** [comment]
Any updates on this?

**Comment by Mark12870** [comment]
I think I've got the same problem. The router-outlet doesn't work when I lazy-load its parent.

**Comment by patachon** [comment]
> ```ts
> ToolsViewStuffModalComponent
> ```

@jayoungers 
I tried your solution but strangely, I get "No component factory found for ToolsViewStuffModalComponent" even though it's defined in entryComponents. Any idea?

**Comment by jayoungers** [comment]
@patachon - I don't know which modal library you're using, but generally in order for them to work properly you need to add the modal service as a provider in your secondary module (even though you likely have it imported or provided in a primary module as well)

**Comment by patachon** [comment]
@jayoungers You're right!  I'm using Angular Material and imported MatDialogModule in the lazy-loaded module as well. Now I can see the dialog opens!
Thank you very much! 👍
