### ISSUE TITLE
FormsModule: untouched text input is not pristine in IE 11

### ISSUE THREAD

**Issue by macjohnny** [angular/angular#14667]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When showing a form in IE 11 with an input field, the initial state of the field is not pristine, leading to error messages being shown to the user before he touched the field.

**Expected behavior**
The field state should be pristine until the user first entered and removed some text. This works fine in e.g. Google Chrome

**Minimal reproduction of the problem with instructions**
http://embed.plnkr.co/fm7lH2/
The red error message should only be display when the user entered and removed some text.

**What is the motivation / use case for changing the behavior?**
Form validation errors should only be displayed when a user touched the form.

**Please tell us about your environment:**
Windows 7 / IE 11

* **Angular version:** 2.4.7

* **Browser:** IE 11
 
* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` =   v6.3.1

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/14440

**Comment by DzmitryShylovich** [comment]
@macjohnny close this issue pls. there's no need to have 2 separate issue for the same bug. thx

**Comment by macjohnny** [comment]
see #14440

**Comment by DzmitryShylovich** [comment]
@macjohnny looks like it's not related to #14440 
The origin of the issue is `mdInput` property. Without `mdInput` everything is fine

**Comment by macjohnny** [comment]
@DzmitryShylovich so it is a material2 issue?
i copied the issue here: https://github.com/angular/material2/issues/3256

**Comment by DzmitryShylovich** [comment]
> so it is a material2 issue?

yeah

**Comment by mmalerba** [comment]
@DzmitryShylovich this appears to be a core bug afterall:

It looks like the source of this bug is the fact that `MdInputDirective` sets up an `@Input()` on `placeholder` and then re-binds it in the `host`. Ideally this should be fixed in angular core.

Here's an example of this happening with pure angular, no material: http://plnkr.co/edit/cpLxYzEVceJ4MUGiOXi5?p=preview

**Comment by DzmitryShylovich** [comment]
@mmalerba will be fixed here https://github.com/angular/angular/pull/14443
Looks like when `placeholder` property is present IE emits change event with an empty string value.

**Comment by macjohnny** [comment]
@mhevery  thanks for closing this. Has this been backported to 2.4.x?

**Comment by DzmitryShylovich** [comment]
@macjohnny it was closed by accident. the bug is still persist

**Comment by mmalerba** [comment]
@DzmitryShylovich FYI it's more than just pristine/dirty state being wrong, I've also noticed that it can cause the initial text in the textarea to be swallowed up (demonstrated here: http://plnkr.co/edit/fOtELWM6t0YKhcvCyFAk?p=preview)

**Comment by DzmitryShylovich** [comment]
@mmalerba ok thanks. there's on open issue for this bug https://github.com/angular/angular/issues/14440
subscribe for updates

**Comment by mmalerba** [comment]
sorry about that, copied the comment to the still open bug

**Comment by aliaburas80** [comment]
did this issue solved? because I still get this error on my page.

**Comment by DelphiWorlds** [comment]
Doesn't look like it is solved, at least in 5.2.5. There is a possible workaround, here: https://stackoverflow.com/a/43756729/3164070
