### ISSUE TITLE
Using platform server, lazy loaded component flickers as the browser renders the application

### ISSUE THREAD

**Issue by Reuvenc** [angular/angular#15716]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] feature request
```

**Current behavior**
Platform server fully renders a lazy module, and the view on the browser is changed several times:
1. The html rendered on the server is shown.
2. As the application starts to bootstrap, the page is shown without the lazy loaded component.
3. As the chunk is downloaded, the lazy loaded component is rendered. 

In case of a heavy chunk, or alternatively a slow connection, it looks like the application flickers on the transition between the views.

**Expected behavior**

The transition between the server rendered page and the client side bootstrapped page should be smooth and invisible to the user.

**Minimal reproduction of the problem with instructions**

[Universal example app](https://github.com/nglibs/universal-example-app) was provided as an example in the [roadmap](https://github.com/angular/angular/issues/13822). Running the application in chrome and throttling the network should be enough for reproducing the behavior (The lazy loaded components will flicker as described above).

**What is the motivation / use case for changing the behavior?**

It makes the application look bad and unprofessional. 

I've used Angular Universal previously, and managed to solve the issue using preboot (rendered the application to a hidden div, and called preboot.complete() manually as the lazy loaded module view was initialized). I've integrated preboot to the current version and tried to use the same approach, but encountered style issues.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tried on Chrome 56, Firefox
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.2

* **Node (for AoT issues):** `node --version` =   
node v6.9.10 (I'm running LTS)

**Comment by fulls1z3** [comment]
Hi @Reuvenc, I have just noticed this post when it was referenced to #13822 and I think it might not be an issue related with Angular.

First of all, on post #13822 I had suggested to have a look at [universal-example-app](https://github.com/nglibs/universal-example-app), it could give some ideas. But I mentioned to do not consider it as a starter/seed project - because it's not perfect, might contain issues, needs improvements.

The project depends on `ngExpressEngine` and `universal-transfer-state` which are experimental modules and not parts of the official Angular app pack. These modules are just custom implementations of their equivalents from @AngularClass repository with some linting & issue resolving - so that webpack build can succeed (especially when `noEmitOnErrorsPlugin` is used).

I suppose that the Angular team will be done with merging `angular/universal` and `angular/preboot` in a near future, and then we will be able to use these modules for Universal.

Maybe it's better to copy this issue to [universal-example-app](https://github.com/nglibs/universal-example-app) repository, meanwhile I'm already working on this and similar issues to improve functionality. It's just my personal opinion, regarding the points that the issue is connected to.

**Comment by Owain94** [comment]
initialNavigation: 'enabled' should fix the flickering

`RouterModule.forRoot([
      // ROUTES HERE
    ],
    {
      initialNavigation: 'enabled'
    })`

**Comment by adrienboulle** [comment]
@Owain94 in fact it does!

**Comment by Reuvenc** [comment]
@fulls1z3 Thanks for the suggestions, actually I didn't use the example app as a seed or as a base for my project. I have an existing project (and a big one) which I'm working on, I've suggested the example app as a repo for reproduction steps as it supports platform server and the issue i'm experiencing occurs there.

@Owain94 Thanks, indeed, it fixed the lazy loaded components flickering.
But seems like something strange happens when using this configuration, when the application starts the bootstrap, the style attributes in the rendered html are not preserved, they disappear and re-injected to the DOM, what causes the page to lose the style for a glance. Any ideas? 
@fulls1z3 Maybe you encountered such behavior and this is one of the improvements that you're on?

**Comment by fulls1z3** [comment]
@Reuvenc actually that's one of the behaviors I found out but wasn't sure until I saw you reproduced the same - and yes i'm working on them, together with some DOM manipulation issues.

**Comment by Owain94** [comment]
@fulls1z3 @Reuvenc I had the same issue but only when I was using a styles javascript bundle 

I've configured my webpack to extract the css into a css bundle instead of a javascript bundle, this fixed the issue for me

**Comment by Reuvenc** [comment]
@Owain94 is it possible to preserve ViewEncapsulation constraints using css output?

**Comment by Owain94** [comment]
@Reuvenc I have no idea to be honest... I'll test it out when I'm home tonight!

**Comment by callumelgrant** [comment]
For me the re-render happens on lazy loading still after implementing @Owain94's fix, but only when you navigate to the lazily loaded route directly.

**Comment by diestrin** [comment]
Confirmed. In my app all the routes are lazy loaded, using css with default ViewEncapsulation and angular starts removing the `<style>` tags with the `ng-transition` in browser, this process takes like a second. After the bootstrap finishes, it adds the styles back.
Here's how it looks like http://take.ms/1wizt

**Comment by Reuvenc** [comment]
@diestrin Thanks for the confirmation, the snapshot you provided describes exactly the issue I'm experiencing. Is there anything new regarding this issue?

**Comment by vikerman** [comment]
The solution we had in mind for this is to wait for the lazy loaded route to finish loading before the client finishes bootstrap and starts removing and replacing things on the document.

This can be done by setting the initialNavigation option on the router to enabled - https://github.com/angular/angular/blob/5293794316cc1b0f57d5d88b3fefdf6ae29d0d97/packages/router/src/router_module.ts#L238

Does this solution work for you?

**Comment by diestrin** [comment]
@Reuvenc for the time being I created my own server transition logic
@vikerman I can test that in the afternoon. I'll let you know.
For now, take a look at how I fixed this:
Basically I copied the `withServerTransition` logic from the `BrowserModule`, but instead of remove the styles in the [APP_INITIALIZER](https://github.com/angular/angular/blob/9684d78cae5d233f0f44af4e740d4fc790790038/packages/platform-browser/src/browser/server-transition.ts#L9) I'm now running it in the `APP_BOOTSTRAP_LISTENER`.

Is there a valid reason not to do this in the bootstrap listener by default? There will be present a duplicate of the <style> for a second or two, but I can't see that affecting my performance at all.

```ts
// app.module.ts
@NgModule({
  imports: [
    // Remove serverTransition when the below issue is fixed
    ServerTransition.forRoot({ appId: 'universal' }),
    // Remove comment when https://github.com/angular/angular/issues/15716 is fixed
    BrowserModule// .withServerTransition({ appId: 'universal' })
  ]
})
```
```ts
// server-transition.module.ts
import { DOCUMENT, ɵgetDOM, ɵTRANSITION_ID } from '@angular/platform-browser';
import { APP_BOOTSTRAP_LISTENER, APP_ID, ModuleWithProviders, NgModule } from '@angular/core';

import { isBrowser } from '@wu/utils/extra-providers';

export function removeStyleTags(document: HTMLDocument): Function {
  return () => {
    if (isBrowser) {
      const dom = ɵgetDOM();

      const styles: HTMLElement[] =
        Array.prototype.slice.apply(dom.querySelectorAll(document, 'style[ng-transition]'));

      styles.forEach(el => dom.remove(el));
    }
  };
}

@NgModule({ })
export class ServerTransition {
  public static forRoot({ appId }: {appId: string}): ModuleWithProviders {
    return {
      ngModule: this,
      providers: [
        { provide: APP_ID, useValue: appId },
        { provide: ɵTRANSITION_ID, useValue: appId },
        {
          provide: APP_BOOTSTRAP_LISTENER,
          useFactory: removeStyleTags,
          deps: [DOCUMENT],
          multi: true
        }
      ]
    };
  }
}
```

**Comment by vikerman** [comment]
Ah - Thanks @diestrin  - I didn't realize this flickering is related to the styles switch.

Discussed with @alxhub who pointed out this is because when initialNavigation is enabled and the route is lazily loaded, the styles is removed assuming the bootstrap will complete synchronously, but that's the case with lazy loaded route.

The fix looks something like this - https://github.com/alxhub/angular/commit/0207c5b80e06a79c300b60c895bb007b1bd306ab

I will be cleaning this up, adding tests and will get this in.

**Comment by Reuvenc** [comment]
@diestrin Thanks for the detailed explanation. 
@vikerman Could you estimate when this fix will be merged?

**Comment by vikerman** [comment]
Will try to get it in before the next release

**Comment by julienR2** [comment]
Hi ! thanks for details explanation about this issues !
We'll wait for the bug to be fixed.

As a further info concerning this bug, I wanted to add that it happens to me too even without lazy loading route..

**Comment by MarkPieszak** [comment]
@julienR2 The flicker your noticing is from Http requests being ran (once on the server, and then again on the browser), that's by design. You'd have to transfer the state [example here](https://github.com/FrozenPandaz/ng-universal-demo/tree/master/src/modules/transfer-state) to pass down an http request within the serialized string version of the app (on the window object), and then get that call to use *that*, instead of making the request again.

**Comment by julienR2** [comment]
Thanks for the hint @MarkPieszak ! However I do use the new transferState (equivalent of the old cacheService right ?), in the appInitializer and the rest of the app..
No further requests were done on the client side, and the flickering was exactly as described (dropping styles and adding them again).

However I use the past since I organised and updated my dependencies this morning and don't have the issue again.. I was probably still on anglular/...@4.0.1 and updating to 4.1.1 seems to resolve the flicker on non-lazy-loaded routes.

Sorry for the non relevant information :/

**Comment by MarkPieszak** [comment]
No worries! Glad you got it working.
Yes it's fairly similar very CacheService, soon there will be an easier way to Transfer state as well, so keep an eye out for that :)

**Comment by kevinphelps** [comment]
@Owain94, `initialNavigation: 'enabled'` helped a lot. Thanks!
@diestrin, your solution worked nicely for my project as well. Thanks!

**Comment by vikerman** [comment]
Sorry - Didn't get it on time for yesterday's release. Will be part of the next one.

**Comment by vikerman** [comment]
This fix should be part of the next Angular release.

So to clarify this makes the client side wait for the router initialNavigation to complete before removing the server side rendered styles.

So a combination of initalNavigation: 'enabled' and this bug fix should fix the flickering for lazy loaded routes. Please reopen this issue if there are still any issues.

**Comment by julienR2** [comment]
Hi ! Thanks for the effort to solve this issue !
However I still have a trouble making it work correctly..
The pre-render of the lazy road works well, no flicker of styles, but the content of the <router-outlet flicker when the `0.client.js` (the bundle of the lazy loaded module) is loaded.

When angular hydrate the pre-rendered page and request the lazyloaded module, it loads it again.. I'm using angular `4.1.3` and `{ initialNavigation: 'enabled' }`.. 
Am I missing something ?

Thanks in advance for any hint !

**Comment by adrianolsk** [comment]
In which version will this be included?

**Comment by MrCroft** [comment]
I wish my lazy loaded component would flicker 😞 
For me, it doesn't work at all... when trying to load the page on a route that lazily loads a module, the server doesn't generate the html content. Page is blank (ok, not completely blank... I have the navigation for example, because that's not in the lazily loaded module... but it doesn't render any component that is contained in the lazily loaded module).

This is what I see in the terminal when loading the page on a route that should lazily load a module:
```
ERROR { Error: Uncaught (in promise): ReferenceError: System is not defined
ReferenceError: System is not defined
    at SystemJsNgModuleLoader.loadFactory (/mnt/d/wamp/www/pdp/packages/core/src/linker/system_js_ng_module_factory_loader.ts:67:1)
    at SystemJsNgModuleLoader.load (/mnt/d/wamp/www/pdp/node_modules/@angular/core/bundles/core.umd.js:5724:35)
    at RouterConfigLoader.loadModuleFactory (/mnt/d/wamp/www/pdp/packages/router/src/router_config_loader.ts:71:1)
    at RouterConfigLoader.load (/mnt/d/wamp/www/pdp/node_modules/@angular/router/bundles/router.umd.js:3402:52)
    at MergeMapSubscriber.project (/mnt/d/wamp/www/pdp/node_modules/@angular/router/bundles/router.umd.js:1570:74)
    at MergeMapSubscriber._tryNext (/mnt/d/wamp/www/pdp/node_modules/rxjs/src/operator/mergeMap.ts:125:21)
    at MergeMapSubscriber._next (/mnt/d/wamp/www/pdp/node_modules/rxjs/src/operator/mergeMap.ts:115:12)
    at MergeMapSubscriber.Subscriber.next (/mnt/d/wamp/www/pdp/node_modules/rxjs/src/Subscriber.ts:95:12)
    at ScalarObservable._subscribe (/mnt/d/wamp/www/pdp/node_modules/rxjs/src/observable/ScalarObservable.ts:51:18)
    at ScalarObservable.Observable._trySubscribe (/mnt/d/wamp/www/pdp/node_modules/rxjs/src/Observable.ts:216:19)
    at resolvePromise (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:770:31)
    at resolvePromise (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:741:17)
    at /mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:818:17
    at ZoneDelegate.invokeTask (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:424:31)
    at Object.onInvokeTask (/mnt/d/wamp/www/pdp/packages/core/src/zone/ng_zone.ts:257:1)
    at ZoneDelegate.invokeTask (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:423:36)
    at Zone.runTask (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:191:47)
    at drainMicroTaskQueue (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:584:35)
    at Server.ZoneTask.invoke (/mnt/d/wamp/www/pdp/node_modules/zone.js/dist/zone-node.js:490:25)
    at emitTwo (events.js:125:13)
```

**Comment by glebmachine** [comment]
+1

**Comment by CanKattwinkel** [comment]
@MrCroft did you manage to solve your issue? I'm facing the same problem. 

Reproduce with https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal), then add a lazy module. -> Server throws 'System is not defined'.

**Comment by MrCroft** [comment]
@CanKattwinkel 
No, I haven't found a solution. But I didn't look for one either, I just gave up for the time being. I was just testing SSR for a bit. Fortunately, I don't need it in a production app... yet.
I'm waiting to see what the CLI will have to offer... Hopefully in a near future release.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by glebmachine** [comment]
Hi! @vikerman do you have any news?

**Comment by Koslun** [comment]
@glebmachine This issue is for the now solved flicker bug. If you have other issues you should open up a separate issue for that. Think you'll see very little traction towards a solution until you do that.

**Comment by glebmachine** [comment]
Thank you!

**Comment by patrickmichalina** [comment]
@diestrin had the true fix for this

**Comment by vikerman** [comment]
Sorry. This bug was closed and I didn't follow updates here.

@julienR2 - Is it possible to create a small repro? Flickering is just a symptom and there could be many different root causes for that. Could be a bug or just maybe a pattern in the app that we can change and document it better.

@MrCroft - The system issue is totally different. Please open a separate bug. This sounds like some issue with the SystemJs setup.

We should be able to have some announcement on the CLI support for platform server soon.

**Comment by spiffyjr** [comment]
@vikerman I'm still getting a delay during transition. If I make my own `withServerTransition` and add a delay with `setTimeout()` I no longer get the flicker. Styles are still being removed too early.

**Comment by vikerman** [comment]
@spiffyjr - Is it possible to share a small github repro? It's difficult to say what exactly could be the problem otherwise

**Comment by julienR2** [comment]
@vikerman sorry I was away past month..
I have finished updating all my dependencies yesterday and keep getting the same behavior described above (https://github.com/angular/angular/issues/15716#issuecomment-303436451) -> lazy road works well, no flicker of styles, but when angular hydrate the pre-rendered page and request the lazyloaded module, it loads it again so the `<router-outlet>` flicker..

I was suspecting that my custom `APP_INITIALIZER` could be the issue, however no change when commenting it..

I'll try to reproduce those days in a small github, so we can investigate easier

**Comment by julienR2** [comment]
I can't get to make a repro yet, but I'm investigating comparing with universal-starter/custom-webpack (https://github.com/angular/universal-starter/tree/master/custom-webpack). This one flicker on a fresh start, but in deed doesn't flicker after adding `initialNavigation: 'enabled'` to the routerModule..

However I don't see much difference with my config yet.. I just use a Shared Module to declare all the shared component I use (could it be this ?).
I'll keep on investigating and share a repo as soon as I have one !

**Comment by naveedahmed1** [comment]
The `{initialNavigation: 'enabled'} `solution works only when we are not using Lazy Loading. When using Lazy Loading {initialNavigation: 'enabled'} prevents flickering on root url only whereas lazy loaded pages still flicker.

**Comment by patrickmichalina** [comment]
@naveedahmed1 Angular 5 beta appears to fix this somehow, but we are flicker free over here:
https://github.com/patrickmichalina/fusebox-angular-universal-starter

for an example of universal with no flicker (https://angular.patrickmichalina.com/)

**Comment by naveedahmed1** [comment]
@patrickmichalina I think issue still exists even with Angular 5 beta

**Comment by misticwonder** [comment]
So this issue was not fixed for lazy routes. Why is it closed?

**Comment by kevinphelps** [comment]
It was fixed for lazy loaded routes.

**Comment by asadsahi** [comment]
Getting flick on both home page (non-lazy) and lazy routes still with angular 5.2.0-beta.0.

I am using animations on each route navigation using this:
```
  public getState(outlet: any) {
    return outlet.activatedRouteData.state;
  }
```
This is a little easy to see when page loads with SSR and right after that it re renders with animations. I am assuming the style flicking under discussion here is same issue that I am having with running animations on each page.

**Comment by naveedahmed1** [comment]
@asad have a look at https://github.com/angular/angular/issues/15716#issuecomment-331741755.

Are you using https://github.com/angular/preboot if so, I think versions earlier than 6.0.0-beta.1 had some issue. Make sure you are using latest version (currently 6.0.0-beta.1).

**Comment by asadsahi** [comment]
@naveedahmed1 Indeed I am on preboot v6.0.0-beta.1 and enabled initialNavigation flag, here is complete AppModule

```
@NgModule({
  declarations: [
    // Components
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'ng-cli-universal' }),
    PrebootModule.withConfig({ appRoot: 'appc-root' }),
    BrowserAnimationsModule,
    BrowserTransferStateModule,
    CoreModule.forRoot(),
    OAuthModule.forRoot(),
    RouterModule.forRoot([
      { path: '', component: HomeComponent, pathMatch: 'full', data: { state: 'home' } },
      { path: 'login', loadChildren: './account/+login/login.module#LoginModule' },
      { path: 'register', loadChildren: './account/+register/register.module#RegisterModule' },
      { path: 'createaccount', loadChildren: './account/+create/create.module#CreateAccountModule' },
      { path: 'profile', loadChildren: './account/+profile/profile.module#ProfileModule' },
      { path: 'chat', loadChildren: './+chat/chat.module#ChatModule' }
    ],
      { initialNavigation: 'enabled' }),
    ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.production }),
  ],
  providers: [
    { provide: APP_DATA, useFactory: getAppData, deps: [] }
  ],
  exports: [
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by saumya04** [comment]
@diestrin I've tried implementing your workaround, but it seems to me that I don't have any `@wu` package from where I can get `isBrowser` method check.
Can you please let me know, from where I can get this `@wu`?

**Comment by saumya04** [comment]
@Owain94 After setting `initialNavigation` to `enabled` my app stops loading. Can you tell me whats making this break?

I'm using Angular - 4.3.6

**Comment by nishadmenezes** [comment]
Has this issue been resolved? I still get the flicker on Angular 5.2.

**Comment by asadsahi** [comment]
I am also having this issue while animations applied on each route navigation. SSR renders the page and then client side navigation happens with animations. I am guessing animations should not run if page is rendered from server?? Anyone has anything working with animations + SSR and share the expected behaviour?

**Comment by jasonaden** [comment]
Sounds like this is mostly solved, but not for all use cases. If there's still a specific bug here, please create a new issue with a minimal reproduction.

**Comment by hamedbaatour** [comment]
[Angularfire-Lite ](https://github.com/hamedbaatour/angularfire-lite) supports server side rendering with state transfer yet I was facing the same problem but I fixed it by modifing `main.ts` to bootstrap the app once the dom is loaded
```
//main.ts
document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppModule)
.catch(err => console.log(err));
});
```

**Comment by ravivit9** [comment]
Hi All, I am using Angular 6 with RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, initialNavigation: 'enabled' })

Still the page loads 4 times and flickers.

Anyone facing this issue still?

**Comment by SharpieX** [comment]
Hi All, I am using Angular 5.2
tried this solution RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, initialNavigation: 'enabled' }) and other suggested didnt worked out for me 
please help 

Issue can be seen here 
https://www.flightman.in/

**Comment by J4cku** [comment]
Hi,
for me the initialNavigation did the trick, but it introduced another issue.
For routes that are behind a guard (authentication) I get a loader from server and the app is never bootstrapped. If I turn initaialNavigation off - everything works fine but I get the flicker.

**Comment by lhmboyz** [comment]
The same for my case too, event when my project updated to Angular 7 not solved the problem too. Please help.

**Comment by MrCroft** [comment]
@J4cku how do you store the user info? I had to A) store it in cookies, not localStorage (since that's not available server side) and B) in my app of course I had to access cookies differently on the server vs the browser. I actually used the express request object when on the server and had a completely different implementation (from `@nguniversal/express-engine` or something like that - forgot exactly, not at my computer today). 
Just saying, because I think you didn't gave the server-side scenario too much thought and might have missed something.

**Comment by J4cku** [comment]
@MrCroft 
hey, I don't even want to transfer my session, I don't want to render my guarded routes. I just want to be able to access my AOT routes through SSR (redirecting to login for that matter).
It does work when initialNavigation is disabled on router so I don't exactly know why it stops when I enable it.

**Comment by tzjoke** [comment]
Tried all solution above, but still have flickers :( 
@J4cku @squelix have u got a solution?

**Comment by squelix** [comment]
We are using a state management, so the data are in the state so it didn't flicker now. We are using [@ngxs](https://github.com/ngxs/store) .

**Comment by elribonazo** [comment]
Hey, I could not make it work with the NgModule but found another solution:
Add this as provider in appmodule.
`{
  provide: APP_INITIALIZER,
  useFactory: function(document: HTMLDocument, platformId: Object): Function {
    return () => {
      if (isPlatformBrowser(platformId)) {
        const dom = ɵgetDOM();
        const styles: any[] = Array.prototype.slice.apply(dom.querySelectorAll(document, `style[ng-transition]`));
        styles.forEach(el => {
          // Remove ng-transition attribute to prevent Angular appInitializerFactory
          // to remove server styles before preboot complete
          el.removeAttribute('ng-transition');
        });
        document.addEventListener('PrebootComplete', () => {
          // After preboot complete, remove the server scripts
          // setTimeout(() => styles.forEach(el => dom.remove(el)));
        });
      }
    };
  },
  deps: [DOCUMENT, PLATFORM_ID],
  multi: true
}`

What is strange in my case, is that I must keep the dom.remove(el) commented to avoid flickering, it does not have any sense, but hope it helps.

Credits go to https://github.com/angular/preboot/issues/75#issuecomment-421266570

**Comment by Ismaestro** [comment]
any updates on this? 😊

**Comment by arun-maddheshia** [comment]
> Hi All, I am using Angular 5.2
> tried this solution RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, initialNavigation: 'enabled' }) and other suggested didnt worked out for me
> please help
> 
> Issue can be seen here
> https://www.flightman.in/

@SharpieX how you fix now

**Comment by Splaktar** [comment]
This issue is closed and will be auto locked soon.

I would suggest following these open, related issues:
- https://github.com/angular/universal/issues/1164
- https://github.com/angular/universal/issues/1200
- https://github.com/angular/universal/issues/1184
- https://github.com/angular/preboot/issues/75
