### ISSUE TITLE
[Animation] In Angular4, leave (* -> void) animation doesn't fire when element is destroyed by ngIf value change

### ISSUE THREAD

**Issue by jeeyun** [angular/angular#15798]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a component with an ngIf. When the ngIf is set to true, the enter animation (void -> \*\) fires. When the ngIf is set to false, the leave animation (\*\->void) doesn't fire. 

**Expected behavior**

I would expect, when the ngIf is set to false, that the leave animation for the component would fire as it used to in 2.4.x: https://plnkr.co/edit/YmxInnbLmXRYrc4onrEd

**Minimal reproduction of the problem with instructions**

This is the same code in 4.0.1, where the leave animation doesn't fire: http://plnkr.co/edit/i4PMM9XyuiEzSdfEgWO6

**What is the motivation / use case for changing the behavior?**

Consistency for enter/leave animation for component created/destroyed by ngIf.

**Please tell us about your environment:**

* **Angular version:** 4.0.1

* **Browser:** all

 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   6.9.0

**Comment by marcorinck** [comment]
possibly related to #15753

**Comment by matsko** [comment]
This will be fixed in the first 4.2 beta.

**Comment by zerefel** [comment]
4.2.0.beta.0 is out and there's nothing done for animations?

**Comment by hisham** [comment]
+1. Seems like same issue happens with *ngFor. Also might be related to #9350.

**Comment by hisham** [comment]
Actually I was able to resolve my issue using trackBy with my ngFor.

**Comment by macjohnny** [comment]
@matsko could you have a look at this? this is still an issue with 4.2.0-rc.2, see the plunkr with angular 4.2.0-rc.2: http://embed.plnkr.co/6OzKcy/

**Comment by matsko** [comment]
Alright so it turns out that this can't be fixed in a similar manner to how it worked in NG2. The reason being is because a parent node, in Angular 4, always has priority. So if inner animations exist in a parent ngIf and the ngIf has no animation then it will always be removed immediately.

There is however a way to make this work using the new `query()` and `animateChild()` features.
```ts
@Component({
  selector: 'my-app',
  template: `
    <div>
      <h2>Hello {{name}}</h2>
      <button (click)="toggle()">Toggle</button>
      <div *ngIf="show" @ngIfAnimation>
        <h3 @easeInOut>I'm inside ngIf</h3>
      </div>
    </div>
  `,
animations: [
  trigger('ngIfAnimation', [
    transition(':enter, :leave', [
      query('@*', animateChild())
    ])
  ])
  //...
]
})
class App {...}
```

Here is this working on RC2:
https://plnkr.co/edit/RJgAunJfibBKNFt0DCZS?p=preview

**Comment by matsko** [comment]
Sorry that this change came up so abruptly. It was something that was planned for 4.0.0, but due to complexities in the new features it got pushed until later and then the fix got lost in the mix of the 4.1/4.2 releases.

Once final 4.2 lands and the animation guide comes out then it will contain clear info about how all this new stuff works. Thank you guys for keeping this issue up to date.

**Comment by Geoide** [comment]
v 4.2.6 and I have the same problem :(

**Comment by dharders** [comment]
Hey @matsko 

Unfortunately your example doesn't work if the `@easeInOut` animation is inside another component (instead of the same component with a parent `@ngIfAnimation`.

The `:enter` transition always fires correctly, but the `:leave  (or * => void)` transition never fires (it's just immediately removed).

I edited your plunker to show you what I (and others) are running into, even with the latest 5.0.0-beta.0: [https://plnkr.co/edit/o5gSwIbAEB6daKHZUxVs?p=preview](https://plnkr.co/edit/o5gSwIbAEB6daKHZUxVs?p=preview)

**Comment by dharders** [comment]
Any word @matsko ? Can you please look at the plunker directly above ?

This issue still exists in the latest `5.0.0-beta.3` version.

**Comment by dharders** [comment]
Updated plunker to `5.0.0-beta.4`. Issue still present.

[https://plnkr.co/edit/o5gSwIbAEB6daKHZUxVs?p=preview](https://plnkr.co/edit/o5gSwIbAEB6daKHZUxVs?p=preview)

**Comment by dharders** [comment]
Issue still present in 5.0.0-beta.5. [updated plunker](https://plnkr.co/edit/o5gSwIbAEB6daKHZUxVs?p=preview)

Can you please take a look @matsko ? Thanks!

**Comment by staeke** [comment]
Same here. Maybe reopen this issue @matsko?

**Comment by dharders** [comment]
This was just fixed @staeke ;)

See #18305

**Comment by dharders** [comment]
Hmmm, the merge/fix was just reverted :(  We will have to wait a little longer for it to make it to the master build.

See PR #19006

**Comment by dharders** [comment]
FYI: new fix just merged to master #19532 

Should be released in next 5.0.0-rc.2 🤞

**Comment by istiti** [comment]
is this fixed ?

**Comment by dharders** [comment]
@istiti yep, 5.0.0-rc.3 recently released with the fix 🍺 

Note: you have to use the newer syntax though for it to work (i.e. query(), animateChild() etc - see above example!)

**Comment by istiti** [comment]
i don't need animateChild() and it works now:
```
 animations: [
    trigger('easeInOut', [
      transition(':enter', [
        style({
          opacity: 0
        }),
        animate("1s ease-in-out", style({
          opacity: 1
        }))
      ]),
      transition(':leave', [
        style({
          opacity: 1
        }),
        animate("1s ease-in-out", style({
          opacity: 0
        }))
      ])
    ])
  ]
```

and in template : 
```
<button (click)="show= !show">go!</button>
<p *ngIf="show"  @easeInOut>hello world</p>
```

this is awesome! :)

**Comment by dharders** [comment]
@istiti I should have specified that animateChild() is needed only if you have :leave animations in a child component and the parent is removed from the DOM. 

And yes, this is awesome ;)

**Comment by jasbro-qut** [comment]
is there any known workarounds? I'm at 4.4.6 and can't upgrade due to dependencies in my project. 
thanks

**Comment by darkbasic** [comment]
Can someone please make an example of a `:leave` animation for an element inside an ngFor?
The following doesn't work for `:leave`:


```
<mat-list-item *ngFor="let item of items">
  <div @flyInOut>{{ item }}</div>
</mat-list-item>
```

```
animations: [
    trigger('flyInOut', [
      transition(':enter', [
        style({transform: 'translateX(-100%)'}),
        animate(500, style({transform: 'translateX(0)'}))
      ]),
      transition(':leave', [
        animate(500, style({transform: 'translateX(100%)'}))
      ])
    ])
  ],
```

I'm using Angular 5.0.1.

**Comment by destus90** [comment]
@darkbasic try this https://plnkr.co/edit/KcIT69XTfB1jLG5eRdiC?p=preview

**Comment by darkbasic** [comment]
You put the animation on the block **outside** of the ngFor, while I want to animate a single item iterated by the ngFor.

**Comment by destus90** [comment]
@darkbasic it`s ok https://plnkr.co/edit/GompkLQ1F0g0HtCliYHA?p=preview

**Comment by darkbasic** [comment]
Oh so I still need `animateChild()`, from a previous comment I thought I didn't. Thanks.

**Comment by uloga** [comment]
I have following animation which should disappear on :enter but it animates (disappears) for 1s and then comes back to the original state? It would make sense to me that this should work, you have the start end end and at the end of the animation it should keep the end state and not revert to start state after animation is finished. 

```transition(':enter', [
    query('.animateMe', stagger(300, [
      style({ transform: 'translateX(0)', opacity: 1  }),
      animate('1s cubic-bezier(.75,-0.48,.26,1.52)',
      style({transform: 'translateX(100px)', opacity: 0})),
    ])),
  ]),
```

**Comment by olivermuc** [comment]
Here is the solution:

```
<parent (swipe)="swipeHandler()" #parent>
	<child *ngIf="isActive === child1" [animDirection]="parent._animateDir">
			Some content.
	</child>
```

**#parent** needed to be set and referenced in its own child comp reference.
Make sure to use setTimeout on changing the `*ngIf="isActive` variable to allow for the child comp to update the input val.
