### ISSUE TITLE
fix(router): canDeactivate should not change the url when returns false and skipLocationChange has been set to true

### ISSUE THREAD

**Issue by ramachandrann** [angular/angular#16314]
I'm submitting a ...  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Current behavior
experiencing the same issue as stated under
https://github.com/angular/angular/issues/12825

Note: #12825 was merged and then reverted in https://github.com/angular/angular/commit/3e548de99d61747fda0803b1f4120b7963a35591

Expected behavior
When we use router.navigate() with skipLocationChange: true, if canDeactivate() returns false when we navigate away from the component, the url shows up the child path

Minimal reproduction of the problem with instructions
see #12825

**Comment by Tim-SE** [comment]
Is there any information on why the fix for #12825 was reverted?  We are affected by this as well.

**Comment by pohybel** [comment]
Angular 4.3.0: problem still occurs. Are there any plans to fix it?

**Comment by Foszcz** [comment]
The problem occurs again on version 5.2.4 . Any plans to fix it?

**Comment by dottodot** [comment]
Still an issue in 6.0.7

**Comment by ricardogoncalves** [comment]
It was fixed in 7.0.0?

**Comment by miikaeru** [comment]
@ricardogoncalves Could you check that?

**Comment by ricardogoncalves** [comment]
@miikaeru I've tested with 7.0.0, but It didn't work.

**Comment by dannye** [comment]
Yes, I'm still having this issue in 7.0.3

This workaround seems to be working (not very thoroughly tested, but is working for my situation):
```
this.router.events.pipe(filter((event:Event) => event instanceof NavigationCancel)).subscribe(
  (event:NavigationCancel) => {
    this.location.replaceState(event.url);
  }
);
```

**Comment by atscott** [comment]
I tried extracting the reproduction from the linked issue and running it in v9: https://stackblitz.com/edit/angular-ivy-a8quoz?file=src%2Fapp%2Fcrisis-center%2Fcrisis-list.component.ts
I could not see the issue that was described. It appears that this may have been resolved at some point. 

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
