### ISSUE TITLE
Router Animation query empty list error

### ISSUE THREAD

**Issue by Delagen** [angular/angular#16917]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

```
Errors
`query(":enter")` returned zero elements. (Use `query(":enter", { optional: true })` if you wish to allow this.)
`query(":leave")` returned zero elements. (Use `query(":leave", { optional: true })` if you wish to allow this.)
```
**Expected behavior**
Animation

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/8Q4OGqtLtSzRi7xqyGAL?p=preview
Switch between page1 and page2

* **Angular version:** 4.2.0-rc.0

* **Browser:** Chrome (at least)
 
* **Language:** TypeScript 2.2.1 (or 2.3.2) does not matter

**Comment by dharders** [comment]
If you append an `{optional: true}` object as the last parameter of the `query()` function then the error goes away.

i.e. 
```
trigger("routeAnimation", [
   transition("page1 <=> page2", [
   query(":enter", [
      style({
         position:  "absolute",
         top:       0,
         transform: "translateX(100%)"
      }),
      animate("30s linear", style({transform: "translateX(0%)"})),
      animateChild()
   ], {optional: true}),
   query(":leave", [
      style({
         position:  "absolute",
         top:       0,
         transform: "translateX(0%)"
      }),
      animate("30s linear", style({transform: "translateX(-100%)"})),
      animateChild()
      ], {optional: true})
   ])
])
```

However, the animation still doesn't fire on route change :(

**Comment by matsko** [comment]
Yes this should be captured. Thank you for reporting this.

**Comment by Delagen** [comment]
@dharders Thanks for translate English to English )

**Comment by matsko** [comment]
Turns out this is caused due to Angular's rendering hierarchy.

A quick fix for now is to add `animations: []` to both `Page1` and `Page2`.

**Comment by Delagen** [comment]
@matsko Does not work, added for both `Page1` and `Page2`. The same error

**Comment by matsko** [comment]
This should fix the issue https://github.com/angular/angular/commit/3ab86bd66162ca94de46e90d2754fcdf96f78c51

**Comment by thaoula** [comment]
Awesome ... many thanks @matsko..

When is the next release due? Will it be another RC?

**Comment by matsko** [comment]
@thaoula  https://github.com/angular/angular/releases/tag/4.2.0-rc.1

**Comment by thaoula** [comment]
Hi @matsko,

I still get the same error with 4.2.2. 
Errors
`query(":enter")` returned zero elements. (Use `query(":enter", { optional: true })` if you wish to allow this.)
`query(":leave")` returned zero elements. (Use `query(":leave", { optional: true })` if you wish to allow this.)

Code is the same as your post on Year of Moo.

Are we missing something?

Regards,
Tarek

**Comment by M4R1KU** [comment]
I am expierencing the same error but on 4.3.0-beta.0 resp. 4.2.4.

**Comment by kykint** [comment]
The same issue on 4.2.4 (floating)

**Comment by stevenmyhre** [comment]
Same issue on 4.3.0-rc.0

Perhaps this candidate release isn't ready?

http://plnkr.co/edit/5nGn32ABLtNNb3kaAhBF?p=preview

**Comment by ClementVidal** [comment]
I have the same issue on 2.4.6.
Why this ticket is close ?

**Comment by maximus-dv10** [comment]
Same issue. Appending `{optional: true} `removes error. But still there is no animations.

> @angular/cli: 1.2.0
> node: 6.9.4
> os: win32 x64
> @angular/animations: 4.2.6
> @angular/common: 4.2.6
> @angular/compiler: 4.2.6
> @angular/core: 4.2.6
> @angular/forms: 4.2.6
> @angular/http: 4.2.6
> @angular/cdk: 2.0.0-beta.8
> @angular/material: 2.0.0-beta.8
> @angular/platform-browser: 4.2.6
> @angular/platform-browser-dynamic: 4.2.6
> @angular/router: 4.2.6
> @angular/cli: 1.2.0
> @angular/compiler-cli: 4.2.6

**Comment by matsko** [comment]
@maximus-dv10 @ClementVidal @stevenmyhre @kykint @M4R1KU this is by design. Here is an explanation: https://github.com/angular/angular/issues/18173

What should happen is that Angular should report an error when `:enter` is used inside of an `:enter` transition and vice-versa for `:leave`.

**Comment by kykint** [comment]
@matsko The main problem is that I don't use :enter inside of an :enter transition.... But I'm getting the same bug on all last versions

**Comment by matsko** [comment]
@kykint ok I see. Can you please put together a plunkr for me so I can debug?

**Comment by kykint** [comment]
@matsko Very similar example was created by stevenmyhre: http://plnkr.co/edit/5nGn32ABLtNNb3kaAhBF?p=preview 
I'll try to make my own example tomorrow.

**Comment by matsko** [comment]
@kykint based on what's going on in the provided example, this falls back on what I was saying with an enter transition occurring (when the page loads). http://plnkr.co/edit/RtcBDlGyIbqDmvDRTgdz?p=preview

See how `:enter` and `:leave` have an empty animation (they should not be quering for :enter and :leave). What happens with `* => *` is that it picks up the enter animation for that transition (when the page loads). Once #18173 goes in it will report the problem clearly with an error message.

**Comment by stevenmyhre** [comment]
@matsko I'm still new to the transitions, can you give me a hint as to how you would fix the plunker linked so it _does_ animate?

When is it valid to query for `:enter` at all?

**Comment by kykint** [comment]
btw http://plnkr.co/edit/8Q4OGqtLtSzRi7xqyGAL?p=preview - this is an example by TS. There is the same problem. And not on page load, but during app working

**Comment by serunkuma** [comment]
I am facing this same problem with angular 8.
@matsko any ideas?

**Comment by dcantu476** [comment]
I too am having this same issue. The only thing that sets my app different from the example in the documentation is that I lazy load a module. I did move everything into app.module just to see if it would fix it, and it doesn't. I'm not sure what else to try or what things to google.

**Comment by jessicajaniuk** [comment]
We're going to close this as obsolete, but if anyone is still experiencing this problem, please open a new ticket.
