### ISSUE TITLE
A required checkbox (within custom component) should always be invalid if unchecked

### ISSUE THREAD

**Issue by KatzeKahn** [angular/angular#17495]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Some months ago an issue related to required checkbox validation had been fixed and it now works as expected. See here: #11459

Unfortunately, the issue still occurs when placing the checkbox input within a custom component. 

**Form template:**
```
<form (ngSubmit)="onSubmit()" #myForm="ngForm">
    // variable 'checkboxValue: boolean' comes from controller
    <my-checkbox name="myCheckbox" [(ngModel)]="checkboxValue" required></my-checkbox> // --> always ng-valid
    <button type="submit" [disabled]="myForm.invalid">Submit</button>
</form>

Output: {{myForm.valid}} // BAD: output always true
```

**Component:**
```
@Component({
    selector: "my-checkbox",
    template: '<input [(ngModel)]="value" [attr.name]="name" [attr.id]="name" type="checkbox" [required]="required"/>',
    providers: [
        { provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => MyCheckbox), multi: true }
    ]
})
export class MyCheckbox implements ControlValueAccessor {
    @Input("name") name: string;
    @Input("required") required: boolean;
    private _innerValue: any;

    onChangeCallback: any = (_: any) => {};
    onTouchedCallback: any = () => {};

    get value(): any {
        return this._innerValue;
    };

    set value(value: any) {
        if (value !== this._innerValue) {
            this._innerValue = value;
            this.onChangeCallback(value);
        }
    }

    writeValue(value: any): void {
        if (value !== this._innerValue) {
            this._innerValue = value;
        }
    }

    registerOnChange(fn: (_: any) => {}): void { this.onChangeCallback = fn; }
    registerOnTouched(fn: () => {}): void { this.onTouchedCallback = fn; }
}
```
In that case, the validation state is NOT propagated properly to the host component. Thus, the enclosing form always remains valid even if unchecking the required checkbox. Like with the older issue, only setting ngModel to NULL would trigger correct propagation (not a desired approach).

## Expected behavior
A required checkbox validation state (ng-valid, ng-invalid) should be propagated properly to the host component. Unchecking the inner checkbox (then ngModel == false) makes host component and form invalid.

## What is the motivation / use case for changing the behavior?

Unchecking a required checkbox within a custom component should prevent the form submission. 

## Please tell us about your environment

Angular version: 2.0.0-rc.6
Browser: [all]
Language: [all]

**Comment by TylerJBrown192** [comment]
Good write-up. I am also experiencing this issue.

Angular version: 4.0.0

**Comment by TylerJBrown192** [comment]
@kara @vicb Could we get a confirmation that this bug was reintroduced in Angular 4.* please?

**Comment by OscarMelin** [comment]
Any updates? Experiencing this issue on 4.2.6.

**Comment by Fincodr** [comment]
This is still an issue with 4.4.5

**Comment by kara** [comment]
@TylerJBrown192 I don't think this has ever worked in custom value accessors, actually.  The `CheckboxRequiredValidator` is a directive that specifically selects for for `input[type="checkbox"]`. With a custom value accessor, we have no way of knowing that there happens to be a checkbox under the hood and it doesn't match the selector. If we implemented roles as suggested in https://github.com/angular/angular/issues/15875, we may be able to support this out of the box. For now, custom checkbox controls will need to provide their own validator.

**Comment by bobKasbi** [comment]
Same issue here. When customizing Checkbox in an extra component (child component), it keeps status ng-valid even if it's unchecked. When loading the component first, the status is: `ng-invalid`, checking it, changes the status to: `ng-valid`, but when unchecked, it keeps `ng-valid`.

**Comment by GuitooStephan** [comment]
Still observing the same issue in Angular version :7. Even with requiredTrue Validator, the experience is still the same. I tried writing a custom validator but the value once changed, remains the same. In my case I keep getting "on" as the value. It is killing me

**Comment by partyka1** [comment]
Still in 8. Any solutions? I've tried with hooking up RequiredTrueValidator with no success.

**Comment by partyka1** [comment]
I've created gist with example solution to validating 'required' on custom checkbox form field. Tested and working in Angular 8: https://gist.github.com/partyka1/a69c86d9d36f955947f45a129196e63d

**Comment by timhecker** [comment]
Still in 10. Any solutions?

**Comment by elenachiosa** [comment]
Issue is still present in angular 13 for ngModel with required attribute. 
Initially, the checkbox is invalid if unchecked ✔, then is valid when checked ✔, then after unchecking, the form control is still valid but should be invalid ❌.

Validators.RequiredTrue works well with Reactive Forms though.
