### ISSUE TITLE
"Develop JIT along with AOT" - Relative Paths not working

### ISSUE THREAD

**Issue by Davy-F** [angular/angular#17832]
## I'm submitting a ...
<pre><code>[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I originally posted the following issue https://github.com/angular/angular/issues/16891 once I upgraded to Angular 4 to resolve a problem I was having with relative paths.

The answer was relative paths are a "technical restriction" with JIT and I had to convert my project to support AOT. I agreed that it would be good to keep up with the times and went along with this. After some hard work, I finally got it working and relative paths did indeed work across my application - hallelujah!  

According to the [AOT compiler guide](https://angular.io/guide/aot-compiler#develop-jit-along-with-aot), we can 'develop JIT along with AOT'. Ideal, or so I thought. Unfortunately this once again triggers the [issues](https://github.com/angular/angular/issues/16891#issuecomment-305714704) I was having with relative paths in JIT.

## Expected behavior
To be able to develop JIT along with AOT, and all paths to components to be resolved successfully with each compiler.

## Minimal reproduction of the problem with instructions
Follow the steps here: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html
Unfortunately I cannot produce a plunker due to the complexity of the app, sorry! I might give it a go later if we're still none the wiser.

For example, I am using a Library of components which is imported from a private repository into node_modules. One of these components is a 'nav.component.ts' with the following code:

```
@Component({
  selector: 'navigation',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css'],
  providers:[CredentialManagementService]    
})
```

This gets the following error when running in JIT mode:

> nav.component.html Failed to load resource: the server responded with a status of 404 (Not Found)

I understand the role of the [systemjs-angular-loader](https://angular.io/guide/change-log#all-mention-of-moduleid-removed-component-relative-paths-guide-deleted-2017-03-13) to help handle these and convert them to absolute paths, but this doesn't seem to be working for imported modules. This does work fine in AOT mode though.

## What is the motivation / use case for changing the behavior?

There seems to be some confusion with JIT/AOT and the use of relative paths.

The guides suggest that we can develop JIT along with AOT, however previous issues and comments have suggested that relative paths are not supported across both environments.

Surely we don't need separate files and paths for each, as this doesn't make logical sense? 
How have others been able to do this? Will JIT eventually become defunct? 

With these in mind, should the promise of being able to develop JIT along with AOT be removed from the Angular guides if JIT do not support the same paths that AOT does?

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.5.0
- Platform: Windows

</code></pre>

**Comment by Yugloocamai** [comment]
> I understand the role of the systemjs-angular-loader to help handle these and convert them to absolute paths, but this doesn't seem to be working for imported modules. This does work fine in AOT mode though.

Not for me!  Angular ignores StyleUrls with preceeding / or ./

**Comment by Yugloocamai** [comment]
I worked around this problem by using a modified version of systemjs-angular-loader.js

changed line 42 from:
`
 urls.push('"' + basePath + match[2].substr(1) + '"');
`
to:
`
urls.push('"' + basePath.slice(1) + match[2].substr(1) + '"');
`

**Comment by Davy-F** [comment]
@Yugloocamai Glad you got it sorted. Unfortunately that fix doesn't work for my issue. I tried it with the templateURL of an imported module and the same '404' error springs up.

**Comment by dherges** [comment]
What exactly is not working? Becuase w/ [Angular CLI, you definetly can use relative paths with either JiT and AoT](https://medium.com/spektrakel-blog/angular-writing-aot-friendly-applications-7b64c8afbe3f)

**Comment by Davy-F** [comment]
@dherges Hi, apologies for the delayed response.

It's a confusing one to get your head around at first but I'm having this problem with using an Angular library that I have built. Frustratingly it's a library from a private repository so I cannot produce a plunkr for it.

The library contains many components, which have relative paths to their templates within the same folder. They need to be relative because they're imported as an external module and the absolute path might not also be the same when deployed and would be a nightmare to manage.
 
If a new app then imports the library under node_modules, Angular cannot resolve the relative paths when running the app under JIT. In AOT mode this works absolutely fine.

Hopefully that makes sense?

**Comment by chuckjaz** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Davy-F** [comment]
Hi @chuckjaz. Why? I'm a bit flabbergasted by this because it's a point I've had to raise twice on here and I really do believe it is a flaw with the current version of Angular.

You **_cannot_** develop in JIT alongside AOT, because relative paths are not supported with imported modules. It's making development in Angular a bit of a nightmare for me.

**Comment by tytskyi** [comment]
@Davy-F do i understand correctly that you have problem with resolution path from the library under `node_modules`?

**Comment by Davy-F** [comment]
Hi @tytskyi, that's correct.

The App structure is like this:

![image](https://user-images.githubusercontent.com/19592376/28457028-6579505a-6dfc-11e7-8b33-eb9a54e6a055.png)

The project **package.json** then has a dependency to an Angular library, taken from a private repository:
```
  "dependencies": {
    "@angular/animations": "^4.2.2",
    "@angular/common": "^4.2.2",
    "@angular/compiler": "^4.2.2",
    ...
    "commonlibrary": "git+https://privaterepo.visualstudio.com/AppTemplate/_git/CommonLibrary",
    "
```

The Common Library contains components that we have built. An example of this is a Table.Component. This has the following path to the templateUrl which is in the same folder as the ts file:

```
@Component({
  selector: 'table-cmp',
  templateUrl: './table.component.html',
...
```
Please note the relative path here.

The table component from the library would then get imported in the main app project:

`import {TableComponent} from 'egresscommon/src/components/table/table.component';`


If the project is compiled under AOT, this works correctly. However under development mode in JIT, the relative path for the Table.Component cannot be resolved, causing a 404 Not Found error. This is because the **systemjs-angular-loader.js** doesn't resolve the paths within `node_modules`.

Thank you.

**Comment by tytskyi** [comment]
@Davy-F i see. For being able to consume library from node_modules it should be already AOT compiled and follow `Angular Package Format v4.0` (https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx)

This way it works. 

You can look how to structure the library using those generators (i tried only first):
- https://github.com/jvandemo/generator-angular2-library
- https://github.com/tinesoft/generator-ngx-library
- https://github.com/dherges/ng-packagr

If you cannot convert your library to  `Angular Package Format v4.0` due to to for example budget question. Then i am sorry, but i don't know the solution.

**Comment by Davy-F** [comment]
@tytskyi Thank you for that.

I used the Yeoman generator to create the library and that is working correctly under AOT. However when developing, it would be beneficial to compile with JIT (alongside AOT) as the Angular documentation suggests that it should work fine. 

Seems that there are a few similar issues about this on the [Yeoman Generator github](https://github.com/jvandemo/generator-angular2-library) so I'll have a look there, however I feel like this is a universal issue of the framework and should be fixed within the systemjs-angular-loader to make it a painless experience switching between the two compilers.

The only way around this for the moment is to either compile only in AOT (which in development mode takes a long time) or have inline templates (which is ugly and not ideal if you're working with complicated templates).

I am just trying to bring this to the Angular dev teams attention.

**Comment by tytskyi** [comment]
@Davy-F i am still don't quite understand you setup. 
I have the library bundled in AOT and installed under `node_modules`. And then i am able to use the library in main app using dev-mode (JIT) of angular-cli.

Lets clarify. 

> The table component from the library would then get imported in the main app project:
`import {TableComponent} from 'egresscommon/src/components/table/table.component';`

Does it mean that you just create components in the "library". But you do not create **there** `NgModule` that exports those components. But instead what you do: you import components directly into main app and define them in `declarations` array of your main app `NgModule`?

**Comment by Davy-F** [comment]
@tytskyi
Hmm... That's what I'm trying to achieve and I believe the setup I have is correct.

Here is the structure of the Library:

![image](https://user-images.githubusercontent.com/19592376/28460234-123c5060-6e09-11e7-8594-a7e0c09ec680.png)


The library is bundled using AOT and the components are also in the NgModule. 
E.g.
```
//Angular Components
import {NgModule, CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA, ErrorHandler}      from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {CommonModule} from "@angular/common";
import {HttpModule} from '@angular/http';
import {RouterModule } from '@angular/router';

//Library Common
import {TableComponent} from './components/table/table.component';
... //other components go here

@NgModule({
  imports: [ BrowserModule, CommonModule, HttpModule, RouterModule, FormsModule, ReactiveFormsModule],
  declarations: [ TableComponent ],   
  providers: [  ],                  
  schemas: [ CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA ]
})
export class LibraryCommonModule { }

```

How do you import the bundled library into your project? Maybe that's where I've been going wrong... 

I appreciate your help.

**Comment by tytskyi** [comment]
@Davy-F your `LibraryCommonModule` should declare and export components. Then your `AppModule` should should import `LibraryCommonModule`.

You should not declare components (and other entities) in 2 modules.

I really encourage you to try follow "Quick Start" on https://github.com/jvandemo/generator-angular2-library#quick-start. Then "Building your library" and then "Consuming your library"

It will generate demo library. Then you can try to consume it in your app an use `<sample-component></sample-component>` from there.

Observe the structure of generated demo. In `src` folder the most important are: `index.ts`, `package.json`, `tsconfig.(es5|spec).json`. For the component (etc) you for sure can use subfolders or not as you want. 
But the main trick is in `index.ts`. See how NgModule is declared and see how things are re-exported.

**Comment by Davy-F** [comment]
@tytskyi Thank you. I've rebuilt my library module so now it is only declared once in my AppModule.
The library compiles fine, but I then run into issues when consuming the library - https://github.com/jvandemo/generator-angular2-library/issues/163. This AOT compatible library business is a tough nut to crack.
