### ISSUE TITLE
Angular v5 ngc compiler: Error encountered in metadata generated for exported symbol 'Subscription'

### ISSUE THREAD

**Issue by robisim74** [angular/angular#18867]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Building an Angulary library using _5.0.0-beta.4 ngc compiler_, I'm getting the following error:
```
Error: Error: C:/Users/Roberto/Documents/GitHub/angular-library-starter/node_modules/rxjs/Subscription.d.ts:21:1: Error encountered in met
adata generated for exported symbol 'Subscription':
 C:/Users/Roberto/Documents/GitHub/angular-library-starter/node_modules/rxjs/Subscription.d.ts:22:12: Metadata collected contains an error
 that will be reported at runtime: Only initialized variables and constants can be referenced because the value of this variable is needed
 by the template compiler.
  {"__symbolic":"error","message":"Variable not initialized","line":21,"character":11}
    at C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\tsc-wrapped\src\collector.js:658:27
    at Array.forEach (native)
    at validateMetadata (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\tsc-wrapped\src\collector.js:646:
42)
    at MetadataCollector.getMetadata (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\tsc-wrapped\src\coll
ector.js:503:17)
    at LowerMetadataCache.getMetadataAndRequests (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\compiler
-cli\src\transformers\lower_expressions.js:169:39)
    at LowerMetadataCache.ensureMetadataAndRequests (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\compi
ler-cli\src\transformers\lower_expressions.js:147:27)
    at LowerMetadataCache.getMetadata (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\compiler-cli\src\tr
ansformers\lower_expressions.js:139:21)
    at CompilerHost.upgradeVersion1Metadata (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\compiler-cli\
src\compiler_host.js:236:45)
    at CompilerHost.getMetadataFor (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\compiler-cli\src\compi
ler_host.js:195:30)
    at StaticSymbolResolver.getModuleMetadata (C:\Users\Roberto\Documents\GitHub\angular-library-starter\node_modules\@angular\compiler\bu
ndles\compiler.umd.js:25829:62)
```

## Minimal reproduction of the problem with instructions
Download the following repo: https://github.com/robisim74/angular-library-starter

Upgrade to Angular 5.0.0-beta.4 and run `npm run build`.

## What is the motivation / use case for changing the behavior?
_Up to Angular 5.0.0-beta.3 it worked without problems. The library does not use itself `rxjs/Subscription`._

The only way to avoid the error seems to be to set `strictMetadataEmit` to _false_, but it is not recommended.

## Environment

<pre><code>
Angular version: 5.0.0-beta.4

</code></pre>

Thanks.

**Comment by steveblue** [comment]
Confirmed this is an issue in `5.0.0-beta.6` and the issue is not seen in `5.0.0-beta.3`. This issue blocks the ability to build libraries per the spec in https://github.com/steveblue/angular2-rollup

**Comment by actra-gschuster** [comment]
Same error here, sticking to beta-3 currently.

**Comment by steveblue** [comment]
I am hoping this issue is escalated for 5.0.0-RC.0

**Comment by pschmoek** [comment]
Error persists in 5.0.0-beta.7

**Comment by crisbeto** [comment]
Some extra info: it seems to have started in beta.4 and it can be worked around by disabling the `strictMetadataEmit`.

**Comment by tommueller** [comment]
Still having this issue exporting a utitlity class looking like this:

```typescript
export class JsUtils {
    private static entityMap = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        '\'': '&#39;',
        '/': '&#x2F;'
    };
    public static escapeHtml(source: string): string {
        return String(source).replace(/[&<>"'\/]/g, (s) => this.entityMap[s]);
    }
}
```
The problem is within the return line in the `escapeHtml`-method. If I remove it, it works fine.

**Comment by mohyeid** [comment]
This issue persist with 5.1.0-beta.1. Using ng build work but fails with ngc:

Error: Error: D:/Developer/Projects/GIT/Angular Universe/libs/app-universe/src/app-universe.module.ts:22:1: Error encountered in metadata generated for exported symbol 'AppUniverseModule':
 D:/Developer/Projects/GIT/Angular Universe/libs/app-universe/src/app-universe.module.ts:49:10: Metadata collected contains an error that will be reported at runtime: Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler.
  {"__symbolic":"error","message":"Variable not initialized","line":48,"character":9}
    at D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\metadata\collector.js:663:27
    at Array.forEach (<anonymous>)
    at validateMetadata (D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\metadata\collector.js:651:42)
    at MetadataCollector.getMetadata (D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\metadata\collector.js:508:17)
    at LowerMetadataCache.getMetadataAndRequests (D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:263:39)
    at LowerMetadataCache.ensureMetadataAndRequests (D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:209:27)
    at LowerMetadataCache.getRequests (D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:204:21)
    at D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:146:36
    at D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\typescript\lib\typescript.js:2592:86
    at reduceLeft (D:\Developer\Projects\GIT\Angular Universe\libs\app-universe\node_modules\typescript\lib\typescript.js:2269:30)

**Comment by mohyeid** [comment]
I fixed my issue with providing initial value for module variable as below:

export class AppUniverseModule {
  static config: any = null; // THIS WAS THE FIX
  static fromConfig(config: any): ModuleWithProviders {
    AppUniverseModule.config = config;
    return {
      ngModule: AppUniverseModule
    };
  }

**Comment by BenevidesLecontes** [comment]
I'm having the same issue, even with the latest beta
```
static set date(date: any) {
    ValidationService._date = date;
  }
```

**Comment by mohyeid** [comment]
@BenevidesLecontes  The error was describing itself for me, so I just initialized the variable. I am not sure where the date property lives in your code, but did you try giving null as an initial value?

**Comment by BenevidesLecontes** [comment]
@mohyeid it's initialised, tried null/undefined but the error remains. And the problem isn't the variable date, is the set accessor, even if i comment this line  `ValidationService._date = date;`, the error remains.

**Comment by matheo** [comment]
I had the `Expression form not supported` error, and it was an inline typing, and it was solved exporting an interface and using it to type that parameter.

**Comment by iamrakesh** [comment]
@tommueller Try below code

```Js
export class JsUtils {
    private static entityMap = {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        '\'': '&#39;',
        '/': '&#x2F;'
    };
    public static escapeHtml(source: string): string {
       let regEx = /[&<>"'\/]/g; 
       return String(source).replace(regEx, (s) => this.entityMap[s]);
    }
}
```

**Comment by NicolasThierion** [comment]
Got this problem.
Added `// @dynamic` before the class that declares static method: 

```typescript
// @dynamic
export class SomeClass {
    public static get() { return 'someValue'; } 
}
```
I believe that static methods within classes are used ie for "MyModule.forRoot()", and angular thinks you are defining a module. As your function would not be compatible with AOT, it compilation fails, and the `// @dynamic` directive is like "don't worry Angular, this class is not intented to be used for bootstapping some modules."

**Comment by rtm** [comment]
I am getting the `expression form not supported` error for simply using `Date` as a type:

    class Foo {
      bar: Date;
    }

**Comment by ochezeau** [comment]
After upgrading my application to angular 6.0.0-rc.1 and rxjs 6.0.0-rc.0, it seems that the problem has come back when i use ngc.
If i add // @dynamic on node_modules/rxjs/internal/nSubscription.d.ts, it fixes the problem

**Comment by speige** [comment]
+1 for recurrence on angular 6.0.0-rc.1 and rxjs 6.0.0-rc.0

**Comment by luchillo17** [comment]
Hey @ochezeau i have an Angular 5 project with same issue, static fields in an injectable service in a library, but the `// @dynamic` comment does nothing in my case, do i really need to update `ngpackagr` version?:

![image](https://user-images.githubusercontent.com/9698639/50455764-3129c280-091e-11e9-8919-a5718fce8e55.png)

**Comment by tanzeelrana** [comment]
I have the same issue as @luchillo17 :(

**Comment by arghya-uipath** [comment]
The issue is still there with `@angular/cli: ~8.0.2`

**Comment by chakrabar** [comment]
The issue is still there with @angular/cli: ~8.0.2

**Comment by zmoshansky** [comment]
Issue was present in a library project compiled with  "@angular/cli": "8.2.0" and resolved by using `//@dynamic` per https://github.com/angular/angular/issues/18867#issuecomment-357484102.

It'd be helpful if the compiler could provide a more insightful error message.

**Comment by omar-dulaimi** [comment]
> Got this problem.
> Added `// @dynamic` before the class that declares static method:
> 
> ```ts
> // @dynamic
> export class SomeClass {
>     public static get() { return 'someValue'; } 
> }
> ```
> 
> I believe that static methods within classes are used ie for "MyModule.forRoot()", and angular thinks you are defining a module. As your function would not be compatible with AOT, it compilation fails, and the `// @dynamic` directive is like "don't worry Angular, this class is not intented to be used for bootstapping some modules."

Thanks a bunch!
This solution also fixes  "Expression form not supported" that I faced while upgrading from 6 to 8

**Comment by KingDarBoja** [comment]
There is some official documentation were the above fix is being mentioned? I do think it should be pointed out or atleast provide a better error message on the compiler.

Cheers!
