### ISSUE TITLE
BUG: Animations cause tests to fail on PhantomJs after upgrade to ng5

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#20415]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After upgrade to Angular 5 tests keeps failing on animations with following error.
```
Error: The animation trigger "flyInOut" has failed to build due to the following errors:
         - The provided animation property "transform" is not a supported CSS property for animations
```

This happens only on PhantomJs, that means on our build server tests keep failing. With Angular 4 same code without any changes was working also on PhantomJS. In Chrome tests are passing without any problem.

## Expected behavior

Testing components which contains animations should work on all browsers.

## Minimal reproduction of the problem with instructions
Animation looks like this.

```ts
/**
 * Fly in animation
 */
export const flyInAnimation: AnimationReferenceMetadata = animation(
[
    style(
    {
        opacity: '{{fromOpacity}}',
        transform: 'translateX({{fromX}})',
        display: '{{display}}',
        position: '{{position}}'
    }),
    animate('{{duration}}', style(
    {
        opacity: '{{toOpacity}}',
        transform: 'translateX(0)'
    }))
], {params: <FlyInParams>{fromOpacity: 0, toOpacity: 1, position: 'absolute', display: 'block', fromX: '25%', duration: '400ms ease-in'}});
```
I have imported `NoopAnimationsModule`.

## What is the motivation / use case for changing the behavior?
I want to have working automated tests on server, where GUI browser is not allowed.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [X] PhantomJS 2.1.1
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform:  Windows

Others:

</code></pre>

**Comment by loicsalou** [comment]
+1

**Comment by ghillert** [comment]
Related discussion https://github.com/angular/material2/issues/7101

**Comment by josephliccini** [comment]
This fails not only in PhantomJS, but in Safari <= 8. Would be good to update the browser support page if these are not supported anymore (https://angular.io/guide/browser-support)

An easy way to repro is to use Browserstack => Yosemite => Safari 8 (latest) => go to https://angular.io and see app crash.

**Comment by trotyl** [comment]
@josephliccini From [browser-support](https://github.com/web-animations/web-animations-js/blob/dev/docs/support.md#browser-support) of `web-animations-js` polyfill, it's documented that only `Safari (Mac) 9+` can be supported.

It seems valid to add it besides:

Feature | Polyfill | Browsers (Desktop & Mobile)
--|--|--
Animations | Web Animations | All but Chrome and Firefox<br>Not supported in IE9<br>**Also mention safari here**

**Comment by emilio-martinez** [comment]
I'm facing the same problem. Below is sample component metadata and then my stack trace. The same error reported above can be seen in the first couple lines. Worth noting that this is happening for every component that uses `transform` within the animation metadata.

In my case, I believe this is a regression issue. Only happened after upgrading to Angular 5 (5.0.5). Web Animations Polyfill version didn't change. The context for the error, as mentioned above, is for PhantomJS 2.1.1 where tests were passing fine before. Testing the components in the browsers in practice doesn't surface any errors or issues; it's just isolated to unit tests.

```ts
@Component({
  ...
  animations: [
    trigger('contentAnimation', [
      transition(':enter', [
        animate(
          '1000ms cubic-bezier(0.35, 0, 0.25, 1)',
          keyframes([
            style({ opacity: 0, transform: `translate3d(0,0px,50px)`, offset: 0 }),
            style([AUTO_STYLE, { offset: 1 }])
          ])
        )
      ])
    ]),
    ... 
  ]
})
```

Stack trace

```
Error: The animation trigger "contentAnimation" has failed to build due to the following errors:
	 - The provided animation property "transform" is not a supported CSS property for animations in src/test.ts (line 45078)
	registerTrigger@webpack:///node_modules/@angular/animations/esm5/browser.js:5541:4 <- src/test.ts:45078:3899
	webpack:///node_modules/@angular/platform-browser/esm5/animations.js:298:48 <- src/test.ts:37768:379
	forEach@[native code]
	createRenderer@webpack:///node_modules/@angular/platform-browser/esm5/animations.js:297:34 <- src/test.ts:37768:325
	createRenderer@webpack:///node_modules/@angular/core/esm5/core.js:14777:4 <- src/test.ts:6759:2547
	createComponentView@webpack:///node_modules/@angular/core/esm5/core.js:13361:0 <- src/test.ts:6366:852
	callWithDebugContext@webpack:///node_modules/@angular/core/esm5/core.js:14754:0 <- src/test.ts:6749:1762
	debugCreateComponentView@webpack:///node_modules/@angular/core/esm5/core.js:14084:0 <- src/test.ts:6564:5467
	createViewNodes@webpack:///node_modules/@angular/core/esm5/core.js:13470:16 <- src/test.ts:6381:2692
	callViewAction@webpack:///node_modules/@angular/core/esm5/core.js:13882:28 <- src/test.ts:6502:72
	execComponentViewsAction@webpack:///node_modules/@angular/core/esm5/core.js:13791:27 <- src/test.ts:6485:15
	createViewNodes@webpack:///node_modules/@angular/core/esm5/core.js:13478:29 <- src/test.ts:6384:25
	createRootView@webpack:///node_modules/@angular/core/esm5/core.js:13343:0 <- src/test.ts:6360:407
	callWithDebugContext@webpack:///node_modules/@angular/core/esm5/core.js:14754:0 <- src/test.ts:6749:1762
	debugCreateRootView@webpack:///node_modules/@angular/core/esm5/core.js:14044:0 <- src/test.ts:6545:4039
	create@webpack:///node_modules/@angular/core/esm5/core.js:10984:13 <- src/test.ts:5613:1836
	initComponent@webpack:///node_modules/@angular/core/esm5/testing.js:1086:55 <- src/test.ts:8522:2977
	invoke@webpack:///node_modules/zone.js/dist/zone.js:392:31 <- src/test.ts:41527:1159
	onInvoke@webpack:///node_modules/zone.js/dist/proxy.js:92:86 <- src/test.ts:42008:2752
	invoke@webpack:///node_modules/zone.js/dist/zone.js:391:40 <- src/test.ts:41527:1058
	onInvoke@webpack:///node_modules/@angular/core/esm5/core.js:4639:16 <- src/test.ts:2765:30205
	invoke@webpack:///node_modules/zone.js/dist/zone.js:391:40 <- src/test.ts:41527:1058
	run@webpack:///node_modules/zone.js/dist/zone.js:172:12 <- src/test.ts:41511:4305
	run@webpack:///node_modules/@angular/core/esm5/core.js:4449:4 <- src/test.ts:2651:24117
	createComponent@webpack:///node_modules/@angular/core/esm5/testing.js:1089:61 <- src/test.ts:8522:3181
	createComponent@webpack:///node_modules/@angular/core/esm5/testing.js:810:4 <- src/test.ts:8468:12971
	webpack:///lib/components/marquee-multi/marquee-multi.spec.ts:236:40 <- src/test.ts:53113:56
	invoke@webpack:///node_modules/zone.js/dist/zone.js:392:31 <- src/test.ts:41527:1159
	onInvoke@webpack:///node_modules/zone.js/dist/proxy.js:92:86 <- src/test.ts:42008:2752
	invoke@webpack:///node_modules/zone.js/dist/zone.js:391:40 <- src/test.ts:41527:1058
	run@webpack:///node_modules/zone.js/dist/zone.js:172:12 <- src/test.ts:41511:4305
	webpack:///node_modules/zone.js/dist/jasmine-patch.js:104:37 <- src/test.ts:42057:134
	webpack:///node_modules/@angular/core/esm5/core.js:7544:21 <- src/test.ts:4172:11
	webpack:///node_modules/@angular/core/esm5/testing.js:93:16 <- src/test.ts:8174:60
	invoke@webpack:///node_modules/zone.js/dist/zone.js:392:31 <- src/test.ts:41527:1159
	onInvoke@webpack:///node_modules/zone.js/dist/async-test.js:49:45 <- src/test.ts:41908:162
	onInvoke@webpack:///node_modules/zone.js/dist/proxy.js:91:17 <- src/test.ts:42008:2634
	invoke@webpack:///node_modules/zone.js/dist/zone.js:391:40 <- src/test.ts:41527:1058
	run@webpack:///node_modules/zone.js/dist/zone.js:172:12 <- src/test.ts:41511:4305
	webpack:///node_modules/@angular/core/esm5/testing.js:88:28 <- src/test.ts:8173:16
	webpack:///node_modules/zone.js/dist/async-test.js:38:24 <- src/test.ts:41905:154
	invokeTask@webpack:///node_modules/zone.js/dist/zone.js:425:36 <- src/test.ts:41527:2125
	runTask@webpack:///node_modules/zone.js/dist/zone.js:192:57 <- src/test.ts:41516:427
	invokeTask@webpack:///node_modules/zone.js/dist/zone.js:527:30 <- src/test.ts:41529:1828
	invoke@webpack:///node_modules/zone.js/dist/zone.js:488:53 <- src/test.ts:41529:1050
	timer@webpack:///node_modules/zone.js/dist/zone.js:2044:20 <- src/test.ts:41725:1746
	TypeError: undefined is not an object (evaluating 'marqueeComp._setAsideIndex') in src/test.ts (line 53162)
	webpack:///lib/components/marquee-multi/marquee-multi.spec.ts:289:18 <- src/test.ts:53162:24
	invoke@webpack:///node_modules/zone.js/dist/zone.js:392:31 <- src/test.ts:41527:1159
	onInvoke@webpack:///node_modules/zone.js/dist/proxy.js:92:86 <- src/test.ts:42008:2752
	invoke@webpack:///node_modules/zone.js/dist/zone.js:391:40 <- src/test.ts:41527:1058
	run@webpack:///node_modules/zone.js/dist/zone.js:172:12 <- src/test.ts:41511:4305
	webpack:///node_modules/zone.js/dist/jasmine-patch.js:104:37 <- src/test.ts:42057:134
	webpack:///node_modules/@angular/core/esm5/core.js:7544:21 <- src/test.ts:4172:11
	webpack:///node_modules/@angular/core/esm5/testing.js:93:16 <- src/test.ts:8174:60
	invoke@webpack:///node_modules/zone.js/dist/zone.js:392:31 <- src/test.ts:41527:1159
	onInvoke@webpack:///node_modules/zone.js/dist/async-test.js:49:45 <- src/test.ts:41908:162
	onInvoke@webpack:///node_modules/zone.js/dist/proxy.js:91:17 <- src/test.ts:42008:2634
	invoke@webpack:///node_modules/zone.js/dist/zone.js:391:40 <- src/test.ts:41527:1058
	run@webpack:///node_modules/zone.js/dist/zone.js:172:12 <- src/test.ts:41511:4305
	webpack:///node_modules/@angular/core/esm5/testing.js:88:28 <- src/test.ts:8173:16
	webpack:///node_modules/zone.js/dist/async-test.js:38:24 <- src/test.ts:41905:154
	invokeTask@webpack:///node_modules/zone.js/dist/zone.js:425:36 <- src/test.ts:41527:2125
	runTask@webpack:///node_modules/zone.js/dist/zone.js:192:57 <- src/test.ts:41516:427
	invokeTask@webpack:///node_modules/zone.js/dist/zone.js:527:30 <- src/test.ts:41529:1828
	invoke@webpack:///node_modules/zone.js/dist/zone.js:488:53 <- src/test.ts:41529:1050
	timer@webpack:///node_modules/zone.js/dist/zone.js:2044:20 <- src/test.ts:41725:1746
```

**Comment by emilio-martinez** [comment]
I think this definitely either an undocumented breaking change or a regression issue. Tested patch versions from 5.0.5 down to 5.0.0, but all suffer the same issues. One more item of note:

Before I didn't have the web animations polyfill when running tests, so presumably they wouldn't be needed currently either. People in the thread have mentioned the polyfill should fix this, but even after adding the polyfill to my tests there is no change. The errors mentioned above still persist.

**Comment by matsko** [comment]
@emilio-martinez these validations are disabled if they are run in a non-browser environment (no DOM). But in this case since `opacity` was detected then this means that there is in-fact a browser present (in this case headless webkit).

This PR should fix that problem: https://github.com/angular/angular/pull/19055

**Comment by kukjevov** [comment]
That is great, because i had to put tests to skip list for now and it does not look good. 

One more question when this PR will make it to the version, so we can test it?

**Comment by UberMeatShield** [comment]
Thanks!   Was just starting to use some of the angular material and the CI exploding was an awkward problem.   I am using 5.1, eagerly awaiting the patches :)

**Comment by kukjevov** [comment]
Any news here? I am using Angular 5.1.2 and tests are still failing :).

**Comment by kkajdd** [comment]
Any updates as it is failing for when we use angular 5.0.3? No use even after upgrading to 5.1?

**Comment by kkajdd** [comment]
Sorry. After updating to 5.1.3 and angular/cli to 1.6.3 resolved the issue.
Thanks

**Comment by JimDrury** [comment]
It may be a problem if you're using Jest to run your tests.
I added the following to my jestGlobalMocks.js and it fixed it

`Object.defineProperty(document.body.style, 'transform', {value: () => ({enumerable: true, configurable: true})});`

**Comment by kukjevov** [comment]
Ok tested in 5.1.3 looks fine :). 

Thank you
