### ISSUE TITLE
checkBindingNoChanges() attempting to check an index that does not exist

### ISSUE THREAD

**Issue by brian428** [angular/angular#21788]
## I'm submitting a...
<pre><code>
[X] Bug report  
</code></pre>

## Minimal reproduction of the problem with instructions
@lishichao1002 was kind enough to provide a repro case at http://plnkr.co/edit/FcuEqLLp8UeS5JXinsGi?p=preview which is similar to what I'm seeing (the error seems limited to cases where visibility of a component is toggled).

To see the error:

1. Open the above Plunker
2. Open the Chrome console
3. Press "Open OK" to see that the overlay appears when it is opened with a direct function call
4. Press "Open Appear Error" to see the `Cannot read property 'name' of undefined` error in `checkBindingNoChanges()` when a binding is used to display the overlay.

## Environment

<pre><code>
Angular version: 5.2.2

Browser:
- [X] Chrome (desktop) version 64.0.3282.119
 </code></pre>

There seems to be a bug or unhandled error problem related to `checkBindingNoChanges()` in `/core/src/view/util.ts`.

The function looks like this:

```javascript
export function checkBindingNoChanges(view, def, bindingIdx, value) {
    var /** @type {?} */ oldValue = view.oldValues[def.bindingIndex + bindingIdx];
    if ((view.state & 1 /* BeforeFirstCheck */) || !devModeEqual(oldValue, value)) {
        var /** @type {?} */ bindingName = def.bindings[def.bindingIndex].name;
        throw expressionChangedAfterItHasBeenCheckedError(Services.createDebugContext(view, def.nodeIndex), bindingName + ": " + oldValue, bindingName + ": " + value, (view.state & 1 /* BeforeFirstCheck */) !== 0);
    }
}
```

During unit testing, I'm intermittently getting an error from `checkBindingNoChanges()`: `Cannot read property 'name' of undefined at checkBindingNoChanges`

I was able to trigger this while "break on exceptions" was on, and took the following screenshot. `checkBindingNoChanges()` tries to look up the binding name via `def.bindings[def.bindingIndex].name`. But since `def.bindingIndex` is currently 20, this evaluates to `def.bindings[20].name`. But `def.bindings` only has 10 elements in it, which results in the error I'm seeing.

Unfortunately, I have no real way to try and build a repro case for this, since I have no idea how Angular is getting into this state. But something seems to be getting out of sync somewhere, possibly the compiler? Should there at least be a check to make sure the index that is being checked exists?

![image](https://user-images.githubusercontent.com/140338/35412946-e68ba836-01eb-11e8-8324-d0eafcd8b115.png)

**Comment by travisolbrich** [comment]
Funny enough I just started running into this now too. I just updated from Chrome 63.0.3239.84 to 64, and this issue wasn't present before.

**Comment by Ketec** [comment]
Same. Thought my code had failed - but it's a simple 
`[ngClass]="{'mat-down': allToggleOpen, 'mat-right': !allToggleOpen}"`
on a <i></i>

**Comment by tarquinrex** [comment]
I'm getting exact same problem, version 63 of Chrome so I don't think that's the issue.

**Comment by brian428** [comment]
I should note that I seem to only run into this during unit testing. When running the app, everything seems fine so far. Out of curiosity, are you other folks also only seeing this during testing?

**Comment by BenevidesLecontes** [comment]
I'm having this issue too, with angular 5.2.2 and latest chrome. @brian428 it occurs even if i'm not testing.

**Comment by alexzuza** [comment]
See https://github.com/angular/angular/issues/21765

**Comment by lishichao1002** [comment]
I also met this problem。
```
GwImgPreviewComponent.html:9 ERROR TypeError: Cannot read property 'name' of undefined
    at checkBindingNoChanges (util.js:126)
    at checkNoChangesNodeInline (view.js:557)
    at checkNoChangesNode (view.js:530)
    at debugCheckNoChangesNode (services.js:563)
    at debugCheckDirectivesFn (services.js:469)
    at Object.View_GwImgPreviewComponent_0._co [as updateDirectives] (GwImgPreviewComponent.html:9)
    at Object.debugUpdateDirectives [as updateDirectives] (services.js:446)
    at checkNoChangesView (view.js:367)
    at callViewAction (view.js:722)
    at execComponentViewsAction (view.js:671)
```
I write a plunker to display this question [http://plnkr.co/edit/FcuEqLLp8UeS5JXinsGi?p=preview](http://plnkr.co/edit/FcuEqLLp8UeS5JXinsGi?p=preview)

**Comment by brian428** [comment]
Thanks @lishichao1002, I updated the original issue to include your Plunker.

**Comment by vicb** [comment]
Could you please update the issue description to give the steps to reproduce the issue with the plunker. Thanks.

**Comment by brian428** [comment]
Done, let me know if that covers it.

**Comment by vicb** [comment]
@brian428 thanks ! Looking at it now.

**Comment by vicb** [comment]
@brian428 @lishichao1002 Could you please make sure https://github.com/angular/angular/pull/21814 fixes the issue - I guess you have a legit issue in your code but you should see the correct error message with the fix.

**Comment by Ketec** [comment]
@vicb Updated to latest angular, still have the issue. Or has this not reached release yet (5.2.2)?

Message is still the same, pointing to the `bindingName = def.bindings[def.bindingIndex].name;`

It's a simple element:

**Comment by pkozlowski-opensource** [comment]
@Ketec you can check if the fix was released or not by checking the fix commit (https://github.com/angular/angular/commit/2af19c96f215794260c22057f0f9b9a93cccdb00). 

If you check the commit page in GitHub you will see that it is only available in master, so not released yet.

**Comment by brian428** [comment]
Thanks, @vicb. Looks like the change has the lookup index use `bindingIdx` instead of `def.bindingIndex`, which seems like it would make a big difference. From the debug screenshot I sent, that would change things to do `def.bindings[2].name` instead of `def.bindings[20].name`. Which is obviously critical, since the former is a valid index while the latter is not!

Is there a way to actually test this before a new version is pushed to NPM? I think there's a way to point the dependency to Github in the package.json, but I'm not sure I've ever needed to do that. I'll Google around and see if I can find the answer.

**Comment by ChaiMinChun** [comment]
Facing the same problem too. By the way, i use ChangeDetectorRef as a workaround to fix this

![image](https://user-images.githubusercontent.com/10117740/35671028-1cd792ae-0775-11e8-8ee9-1189d728b31e.png)
 Using  http://plnkr.co/edit/FcuEqLLp8UeS5JXinsGi?p=preview provided by @lishichao1002

**Comment by stevedeighton** [comment]
Upgrading to 5.2.9 fixed this for me.

**Comment by bertjan** [comment]
+1, upgrade to 5.2.10 fixes it for me too (I was on 5.2.5)
