### ISSUE TITLE
Relative URL support in annotations

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2383]
# GOAL

support loading resources into the components in a relative way for re-usability.

## JavaScript

CommonJS modules standards publishes the `module.id`, which can be passed into the `@View` Annotation.

```javascript
@Component(...)
@View({
  moduleId: module.id, // commonJS standard
  templateUrl: 'my-component.html',
  styleUrls: ['my-component.css'] 
})
class MyComponent {
}
```

## Dart

In dart the user does not have to explicitly set the `moduleId` instead we can extract the location from the library path:  `MyComponent.owner.uri.path`

See: [uri_mapper](https://github.com/angular/angular.dart/blob/f9406a4a08671307d051172953e164f1c6cd52ac/lib/core_dom/type_to_uri_mapper_dynamic.dart)

## In-lining

Later we could add a pre-deploy step which will inline the URLs into the annotations directly.

**Comment by mhevery** [comment]
dup of #2194

**Comment by choeller** [comment]
So I'm not entirely sure if I understood the suggestion completely, but from a users point of view this seems to add some more boilerplate to the application code. When having to add

```javascript
  moduleId: module.id,
```
to every `@View` annotation, wouldn't it be possible to handle that by the framework? IMO relative URLs should be standard for components. Or am I getting anything wrong here?

**Comment by vicb** [comment]
> IMO relative URLs should be standard for components. Or am I getting anything wrong here?

That's the plan, but relative to where ? This is why we need to have the path to the component.

**Comment by choeller** [comment]
Ok, 

I get that, but when you write

```javascript
@View({
  moduleId: module.id, // commonJS standard
 ...
}
```
you are "in the component" aren't you? So I don't get, why the framework couldn't say smth. like. 

"When we declare a component (so I'm speaking of the file containing the class that is annotated with `@View`) we handle all URLs declared, relative to that file." 

I'm not into the technical details and when `module.id` gives you access to that information that's perfect - I'm just complaining, about having to add that to every Annotation I write, because it adds one more point of failure and IMO is boilerplate that should not be written by the user.

**Comment by vicb** [comment]
> we handle all URLs declared, relative to that file

That's the plan again...

And `module.id` is the way to get the path to the file.

Currently I don't see any better way to achieve this but any other simpler way is welcome.

**Comment by choeller** [comment]
So it's pretty easy for me to argue, as I'm not into the technical details, but couldn't that `module.id` be added automatically by the framework, when evaluationg the `@View` Annotation?

**Comment by tbosch** [comment]
Sadly no. As our @View annotation is defined in another module, it would
get the module where it is defined when it reads out module.id (i.e.
angular2/src/core/annotations_impl/view.js).

**Comment by jakemac53** [comment]
For elements written in TS which want to compile to both Dart and JS, would we just remove the `moduleId: module.id` during the transpile? Do we have the necessary hooks to do that?

**Comment by mhevery** [comment]
@jakemac53: yes just remove for dart
@choeller: I would love to drop the `module.id` from the `@View` but unfortunately, it is technically not possible. The only place where the information is stored is in the `module.id` and it is only visible to the application file. :-(

**Comment by vicb** [comment]
> Having said that I would love to hear a technical solution which would remove the dep on module.id.

you should try tweeter ?

**Comment by vicb** [comment]
random thought: stack traces ?

**Comment by vicb** [comment]
random thoughts (cont'd):

```
// Dart has to take a compile time ct
enum module {
  id
}

// JS has to be a fn (if we want to use stack traces)
class Module {
    get id() {
        return this.process(new Error().trace);
    }
}

```

**Comment by jakemac53** [comment]
@vicb we shouldn't need the module.id at all in dart

**Comment by vicb** [comment]
@jakemac53 yep we don't "need" it but we want the ts code to transpile to dart, don't we ?

**Comment by jakemac53** [comment]
@vicb yes, but I think we want to just remove it entirely during the transpile (if reasonable). Alternatively we could just make it be a no-op?

**Comment by vicb** [comment]
`enum` is the way I've found to make it a compile time constant no-op, is there a better way ?

**Comment by jakemac53** [comment]
Ah I wasn't sure if that was what you meant with the enum or not. I think that is probably fine.

**Comment by tbosch** [comment]
@vicb: Stack traces won't work in production, if the code is concatenated,
as reading Error.stack does not support stack traces.

**Comment by tbosch** [comment]
@vicb This also does not work in Safari with SystemJS: SystemJS uses `eval` to load the scripts, and uses `//@sourceURL` to let the eval show up as normal file in the inspector and for stack traces. However, Safari does not seem to support this...

**Comment by vicb** [comment]
@tbosch 
- I fail to see how concatenated code would be an issue, also see the discussion in the standup channel,
- `eval` is probably an issue,
- do you have some examples of how `module.id` would work ?

**Comment by tbosch** [comment]
Using `module.id`:

```
@View({
  baseUrl: module.id
})
export class MyComp {}
```

SystemJS and commonJS will provide a global `module` that is local to the module that is being evaluated.

**Comment by vicb** [comment]
I have tried in the unit tests context and it doesn't work. There does not send to be a lot of doc about it on the web.

Let's try to chat later today. I should be available from 1PM PST.

**Comment by naomiblack** [comment]
Moving to alpha-31 -- this needs a doc outlining possible approaches. @vicb @tbosch

**Comment by vicb** [comment]
I won't have time to work on this before August, please find details of what has been tried in [this document](https://docs.google.com/document/d/1qlIJ6jWa-e83omMEKoosdA3cij9n8IEvIHiJ0i4MkaU/edit?usp=sharing)

_I should be available to answer questions in the coming weeks_

**Comment by TiagoBraga39** [comment]
First of all, it's pretty easy for me to argue, as I'm not looking into the technical details, but why do we need the module Id?
This was about relative URLs and I don't understand why do we need the module Id.

Every time I need to use a component I need to import it as:
```javascript
import { MyComponent } from './my-component/my-component.js';
```
That was a relative URL (could be an absolute). Can't we save it on a stack?
So:
1. Import Component
2. Save URL on a stack (or maybe save with a global variable: $path_to_component ?)
3. Compile the URLs paths given the saved URL.

Too much abstract / theoretical?
Sorry for knowing all the technical details.

Best regards,
Tiago Braga

**Comment by rolandjitsu** [comment]
@TiagoBraga39 consider this scenario:
```js
// components.js
export { TheComponent } from 'components/thecomponent.js';
```
```js
// components/thecomponent.js
export class TheComponent {}
```
```js
// app.js
import { TheComponent } from 'components';
```
In this case, when you import `TheComponent` from `components.js`, there will be no way of knowing that path. Does this make sense?

**Comment by TiagoBraga39** [comment]
What about interpolation?
Or when exporting also save?

**Comment by pkozlowski-opensource** [comment]
Putting back to backlog as I don't think I will have time to work this in .36 / .37 timeframe

**Comment by Pajn** [comment]
Can't `baseUrl: module.id` be automatically added as a build step?

**Comment by mhevery** [comment]
@Pajn, whatever we come up with needs to work without a build step as well.

**Comment by rolandjitsu** [comment]
@mhevery I am not sure what is the status on this, but I can see that the `@Component` API has a `moduleId` that I assume we can use to help do the loading relative. I compiled to CommonJS with `moduleId: module.id` but when it tries to load in the browser I get a:
```js
XMLHttpRequest cannot load package:http:/localhost:3000/app/components/todo_item/todo_item.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.t.get @ angular2.min.js:16e.normalizeTemplate @ angular2.min.js:12e.normalizeDirectiveMetadata @ angular2.min.js:24(anonymous function) @ angular2.min.js:24map @ es6-shim.js:1101e._compileComponentRuntime @ angular2.min.js:24(anonymous function) @ angular2.min.js:24e.createBeginComponent @ angular2.min.js:12e.visitElement @ angular2.min.js:12e.visit @ angular2.min.js:10(anonymous function) @ angular2.min.js:10forEach @ es6-shim.js:1095n @ angular2.min.js:10e.compileComponentRuntime @ angular2.min.js:12e._compileCommandsRuntime @ angular2.min.js:24(anonymous function) @ angular2.min.js:24n.run @ angular2.min.js:1(anonymous function) @ angular2.min.js:10(anonymous function) @ angular2.min.js:1k @ angular2.min.js:1A @ angular2.min.js:1I @ angular2.min.js:1(anonymous function) @ angular2.min.js:1r @ angular2.min.js:10n.run @ angular2.min.js:1(anonymous function) @ angular2.min.js:10(anonymous function) @ angular2.min.js:1h @ angular2.min.js:1
angular2.min.js:21 EXCEPTION: Failed to load package:http:/localhost:3000/app/components/todo_item/todo_item.html
```
Is this not going to work at this point, if so why do we have a `moduleId` on the component?

**Comment by tbosch** [comment]
Sorry, but this is still work in progress...

**Comment by rolandjitsu** [comment]
@tbosch thanks, looking forward to a solution.

**Comment by ewinslow** [comment]
Are we sure that angular is the right place to solve this? Shouldn't the module system be responsible for this?

**Comment by tbragaf** [comment]
@ewinslow Probably.
What if I use another module loader? Same happens?

**Comment by ewinslow** [comment]
I don't understand your question

**Comment by tbragaf** [comment]
I was wondering if the systemjs was responsible for this (since everyone uses it I guess). If so, does the same happen with other loaders?

**Comment by pkozlowski-opensource** [comment]
This got fixed by 28860d35b2a3bc17743ff3b34c6514311763b54c

**Comment by evanplaice** [comment]
@pkozlowski-opensource Just loaded beta-2 and tried `module.id` with no luck. FYI, I'm using System.js via JSPM. 

Fortunately, I found a workaround.

*Note: The project file structure is organized by-feature. The component in question will be extracted into a separate project for reuse; relative paths are essential for this to work.*

*File structure:*
- app
  - resume
    - modern
      - components
        - modern.css
        - modern.html
        - modern.js

The workaround uses [plugin-text][plugin-text], a text import add-on for System.js.

*Source:*
```javascript
import { Component, View, ViewEncapsulation } from 'angular2/core';
import { MODERN_DIRECTIVES } from '../modern';

import template from './modern.html!text';
import fontAwesome from 'font-awesome/css/font-awesome.min.css!text';
import style from './modern.css!text';

@Component({
  selector: 'resume',
  inputs: [ 'resume' ]
})
@View({
  // moduleId: module.id, // NOPE
  // templateUrl: 'app/resume/modern/components/modern.html', // absolute path of stylesheet
  // styleUrls: [ 'app/resume/modern/components/modern.css' ], // absolute path of stylesheet
  template: template,
  styles: [ style, fontAwesome ],
  directives: [ MODERN_DIRECTIVES ],
  encapsulation: ViewEncapsulation.Native
})
export class ModernComponent {
  constructor () {
    // console.log('resume');
  }
}
```
*Note: font-awesome is installed as an external JSPM dependency, that's why it isn't co-located with the component.*

The `plugin-css` module imports text files the same way System.js imports Javascript. In this case, they're loaded as text and saved to variables that are used to set the template and styles in the view metadata.

[plugin-text]: https://github.com/systemjs/plugin-text

**Comment by tbragaf** [comment]
@pkozlowski-opensource 
I can't make this to work... Does anyone have any sample with ES6 and SystemJS?
According to them, __moduleName would work, but it doesn't because it is being parsed to $__moduleContext.id which is undefined, since $__moduleContext evaluates to the moduleName

Thank you!

**Comment by cescoferraro** [comment]
As of  "angular2": "2.0.0-beta.14" this is still not working. It breaks with things like routerlink and ngformcontrol inside the html. @evanplaice solution works great though.

**Comment by cecotw** [comment]
@cescoferraro i thought so too, but I think it works when you include a trailing / in your base href: 
<base href="@Url.Content("~/Example/Angular/")" />  >>> works
<base href="@Url.Content("~/Example/Angular")" />  >>> fails

**Comment by cecotw** [comment]
Nevermind, that grabs the literal page and appends the content in a cascade.

**Comment by cescoferraro** [comment]
@cecotw turns out there was a mistake on my gulp html minification task solved by #8001 . I am on a golang backend so am loading the html files through http. Not sure if I can user relative imports. I think I have had the concepts all messed up on my head.
