### ISSUE TITLE
Service worker breaks web app on Edge

### ISSUE THREAD

**Issue by robisim74** [angular/angular#27261]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/service-worker

### Is this a regression?

I don't know if it happened with previous versions.

### Description

Using service worker breaks the web app on Edge browser for desktop the first time it is loaded. No errors, but it seems busy and does not perform any operation (like http requests) for a while (even a few minutes in complex apps). Then it begins to work.

## 🔬 Minimal Reproduction

Steps:
- Open Edge browser for desktop
- Clean the browser cache (important!) and restart the browser
- Open https://angular.io/
- Because AIO has only static contents it seems to works: try to refresh the page and you'll see a blank page for a while.

## 🔥 Exception or Error
<pre><code>
No errors in console.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 8.11.1
OS: win32 x64
Angular: 7.1.0
</code></pre>

**Anything else relevant?**

Only on Edge browser: Microsoft EdgeHTML 17.17134

The issue seems related to PWAs built with Angular because PWAs that do not use Angular seem to work properly, for example: https://pwa.rocks/

Thanks.

**Comment by gkalpak** [comment]
If I understand correctly, the issue you are reporting is that apps using `@angular/service-worker` are slow to load on Edge. Is that correct?
I tried with angular.io (on EdgeHTML 18.17763) and I could really reproduce it :confused:

**Comment by robisim74** [comment]
@gkalpak _I could really reproduce it_ or do you mean: I could _not_ really reproduce it?

In the second case, what kind of repro should I provide? This is what happens to angular.io when I refresh on Edge with the clean cache:

![image](https://user-images.githubusercontent.com/14012361/49025606-564ed800-f19c-11e8-9b0d-ed163b9be42f.png)

I see a blank page for about 30 seconds.

Here you can find a my app in production: https://feedingthehouse.com

If the app is loaded...
- Tap `Get started`
- Type a location & tap Search
- Nothing happens: after 60 seconds you will get a timeout error. 

The app seems busy: does not perform operations, in this case did not make the request to Google Maps Geocoding API.
Try also to refresh the page.

As connection speed, I have at the moment 4.77 Mbps: but this is not a problem with other browsers (By the way: it's weird that we have a different version of Edge, I'll check).

**Comment by gkalpak** [comment]
Yes, I meant I could NOT reproduce it, sorry. (I updated the original message.)
I do get a "request could not be processed error" with your app (on Edge), but angular.io loads normally (i.e. within a couple of seconds).
Maybe it is an issue with Edge's SW. Possibly something that was improved from version 17 to 18, but not entirely fixed? No idea.

If you can pinpoint what exactly is causing the issue (e.g. is it some specific kind of request?) and create a minimal reproduction, I'd be happy to investigate.

**Comment by robisim74** [comment]
There were problems with Windows October update: so I still have Edge v17 and I don't have v18 yet.

Ok, I'll try to create a repro.

**Comment by robisim74** [comment]
@gkalpak I found the problem, but I can not reproduce it in a repro, because it would take too much time. Let me explain.

The problem on Edge is _the pre-caching of static files during the Service Worker's install phase_.

In my real app I have 15 chunks and a lot of assets totaling around 15 MB, and I'm using a _prefetch strategy_. This is not a problem for other browsers, but apparently it's a problem for Edge. And while it tries to cache them, the app is busy (and therefore does not even perform external http requests).

At the moment, I can improve performance by trying to reduce assets, and by adopting a _lazy_ strategy, at least to allow the app to work.

At this point I no longer think that the problem is of Angular, but exclusively of Edge. If you agree with this hypothesis, I would close this issue and open an issue directly on Edge.

Thanks.

**Comment by gkalpak** [comment]
That is weird, because (a) initialization of asset/data groups happens asynchronously (so should happen after the page has fully loaded) and (b) only one resource is fetched at a time (so no matter how many groups/resources you have the SW should be able to handle more requests).

It definitely sounds like an issue with Edge. Hopefully one that is fixed (or improved upon) on the latest version.
I am going to close this. Can you, please, post the link to the Edge issue here (for future reference)?

**Comment by robisim74** [comment]
@gkalpak  Yes it's strange: but locally I could follow step by step what happens: while adding files to the cache during installation, when it finds a file > 1 MB (like the main bundle), it becomes dramatically slow and the app does not work.

Thanks for you support.

This is the issue on EdgeHTML issue tracker:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19733696/

**Comment by gkalpak** [comment]
Interesting! Thx for posting the issue link 👍 

(BTW: On `localhost`, initialization happens eagerly rather than lazily. On non-localhost origins, the initialization starts with a few secs delay (5s iirc).)

**Comment by robisim74** [comment]
@gkalpak I reduced the size of the app (including assets) to around 4 MB (bringing out larger static files) and adopted a _lazy_ strategy for `installMode `and `updateMode`.

Now the app in production works, but the problem still exists.
