### ISSUE TITLE
[Ivy] Compile Error with ngx-charts

### ISSUE THREAD

**Issue by vdumbrav** [angular/angular#30512]
# 🐞 bug report

### Affected Package
Ivy Template Compiler

###  Is this a regression?
  ```
"angularCompilerOptions": {
    "enableIvy": true // no work
    "enableIvy": false // work
  }
```

### Description

Doesn't compile project

## 🔬 Minimal Reproduction

https://github.com/vdumbrav/angular-ivy-ngx-charts

## 🔥 Exception or Error
https://i.ibb.co/z5VZn7M/Screenshot-2019-05-16-16-42-06.png
https://pastebin.com/PRVaP7n9

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 8.0.0-rc.4
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/pwa                      0.12.4
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

**Anything else relevant?**

**Comment by ericmartinezr** [comment]
Please report this to the owner of the lib. It's their responsibility to make their lib to work with something not yet finished. Angular team doesn't mantain that lib.

**Comment by vdumbrav** [comment]
> Please report this to the owner of the lib. It's their responsibility to make their lib to work with something not yet finished. Angular team doesn't mantain that lib.

ok, thanks

**Comment by JoostK** [comment]
Actually, this might be an issue with ngcc.

**Comment by spock123** [comment]
@ericmartinez why the downvote?

**Comment by vdumbrav** [comment]
@kara @jasonaden
**swimlane** has fixed the error in version 12.0.1 (ngx-chart)

**Comment by vascofernandes** [comment]
I had the same issue before, but with 9.0.0-next.1 my project compiles just fine.

**Comment by vascofernandes** [comment]
my project also compiles with 9.0.0-next.2.

**Comment by gkalpak** [comment]
Based on [ngcc-validation/infra/passing.json#L141][1] and @vascofernandes' report, it sounds like the problem with `@swimlane/ngx-charts` has been solved. Closing...

[1]: https://github.com/mgechev/ngcc-validation/blob/64986dc36/infra/passing.json#L141

**Comment by vascofernandes** [comment]
I have an update.

It seems the application compiles fine with Ivy, but it does not run in the browser with Ivy at version 9.0.0-next.3.

> ERROR Error: "Template error: Can't bind to 'xScale' since it isn't a known property of 'g'."


This is reproducible:

https://stackblitz.com/edit/vertical-bar-chart-box89u

1- Just download the project to your machine
2 - npm install
3 - ng serve
4 - See the browser console

Is Ivy able to handle SVG properly?

Regards

**Comment by vascofernandes** [comment]
To provide some more info: 

> ERROR Error: "Template error: Can't bind to 'xScale' since it isn't a known property of 'g'."


These are the files that are important:

https://github.com/swimlane/ngx-charts/blob/master/src/bar-chart/bar-vertical.component.ts#L32

```
<svg:g
          ngx-charts-x-axis
          *ngIf="xAxis"
          [xScale]="xScale"
```

The `xScale` is defined by the `ngx-charts-x-axis` directive:

https://github.com/swimlane/ngx-charts/blob/master/src/common/axes/x-axis.component.ts#L15


Regards

**Comment by JoostK** [comment]
This likely has the same root cause as described in https://github.com/angular/angular/issues/32078#issuecomment-520218977.

**Comment by vascofernandes** [comment]
The issue is still present in Angular 9.0.0-next.9 with Ivy enabled

**Comment by vdumbrav** [comment]
@vascofernandes No, this issues is fixed, please recheck my reproduction repo https://github.com/vdumbrav/angular-ivy-ngx-charts

**Comment by vascofernandes** [comment]
@vdumbrav unfortunately is does not work.

I pulled your repository, and ran it. 
It does not work correctly.
The browser console displays a lot of warnings:

> Can't bind to 'colors' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'series' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'innerRadius' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'activeEntries' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'outerRadius' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'gradient' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'tooltipDisabled' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'tooltipTemplate' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'tooltipText' since it isn't a known property of 'g'. core.js:13141
> Can't bind to 'animations' since it isn't a known property of 'g'. core.js:13141

**Comment by vdumbrav** [comment]
@vascofernandes It is warning, not critical :)

**Comment by vascofernandes** [comment]
yes, but the problem is that, things do not render correctly.

Try render a ngx-charts-bar-vertical.

**Comment by vdumbrav** [comment]
@vascofernandes I tried, not work (

**Comment by vascofernandes** [comment]
The issue is still present in 9.0.0-rc.0.

**Comment by JoostK** [comment]
This is caused by a bug in the template compiler, see #32061, for which I opened a fix in #33555.

I have _not_ targeted that PR to fix this issue, as I have not confirmed that there aren't additional issues with ngcc that may still cause breakages.

**Comment by alxhub** [comment]
After @JoostK's fixes,`ngx-charts` is showing as fixed in our validation repo. Please feel free to file a new issue if there are still problems with the library :)
