### ISSUE TITLE
Add default/optional parameters to support easy upgrade on ViewChild/ContentChild breaking changes

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#30751]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
we have a large application with large number of references to ViewChild/ContentChild decorators. with latest v8 these decorators are modified with breaking change to include {static: true/false} parameter. can we make this as a optional/default parameter so we do not have to make large set of changes across our application and depended libraries. (we do use depended libraries which also reference ViewChild/ContentChild and it will be really hard to migrate all the depended libraries to new format)

### Describe the solution you'd like
Make {static: true/false} parameter optional or use default value = false. 

### Describe alternatives you've considered
we are considering alternative to use `@ViewChild('foo', <any>{static: false})` on all our existing v7 codebase to mitigate the upgrade complexity (still not tested or finalized). but we are still blocked on doing same steps in libraries we are depending on (not in our control).

**Comment by trotyl** [comment]
> Make {static: true/false} parameter optional or use default value = false.

Making any static default value will also become breaking change, as the previously runtime has a dynamic default value based on usage, which is worse as not even awared by user.

**Comment by mlakmal** [comment]
> > Make {static: true/false} parameter optional or use default value = false.
> 
> Making any static default value will also become breaking change, as the previously runtime has a dynamic default value based on usage, which is worse as not even awared by user.

i was not aware of this being dynamic earlier. yes it will not be ideal (unless we have it like before by default) but user will have option to override based on their requirement.

at-least having default/optional value would allow us to start progressing on upgrade validation instead of being blocked on this issue (since this breaks, and not being able to update external library code we are now blocked until all dependencies are corrected).

**Comment by alxhub** [comment]
We cannot unfortunately have a default/optional value, for the reason that @trotyl mentioned above: currently the runtime interprets no value as the dynamic case. It must continue to do so, to support library code compiled without a value for `static`. Thus changing this interpretation would break existing libraries.

You shouldn't need to wait for libraries to update for this reason - setting `static` in your application only should be enough to upgrade to 8 without breaking. Is that not the case? If so, please provide a reproduction.

**Comment by Errors4l** [comment]
@alxhub This related issue (https://github.com/angular/angular/issues/30685) was closed, but the underlying issue still seems to be present. ContentChild now requires static to be true or false in preparation for Angular 9. The template (html) for said ContentChild may be used with or without an `ngIf` condition in higher components.

In our scenario we have a grid component that has optional ContentChild components used to conditionally show buttons in a grid (i.e. edit/delete row). In some grids, we are using ngIf conditions while in other grids we're not. Using `static: false` only works when adding `*ngIf="true` to the grids that do not already have a condition.
If needed, I'll try to set up a project this weekend to reproduce the issue (as the project isn't open source).

A [workaround](https://github.com/angular/angular/issues/30685#issuecomment-496568034) was provided in the comments, but this doesn't seem like an ideal solution for cases where dynamic resolution is preferred.

Is this the proper way to work with `ContentChild` decorators that can be both static and dynamic depending on usage, or does this hint towards a bad component structure that should be changed?

**Comment by Errors4l** [comment]
Here's two projects with the same code. The Angular 8 version here uses `static: false`, because in some use cases the ContentChild has an `*ngIf` condition which won't resolve with `static: true`. 

Although the code works fine in the dynamic mode, moving away from automatic resolution now means the first use grid without `*ngIf` will be initialized on the `AfterContentInit` lifecycle hook rather than right away `OnInit`. Although harder to notice with so little code than in our larger project, this does make the content 'pop in' opposed to the rest of the content. This can be seen here: https://streamable.com/91sti

| Version | Link |
|---|---|
| 7.2.15 | https://stackblitz.com/edit/angular-y6sh6z |
| 8.0.0 | https://stackblitz.com/edit/angular-vdpsy3 |

**Comment by mlakmal** [comment]
@Errors4l we are getting the same issue on our app, glad you got the example code (i didn't had time to create a plunkr for this yet).

**Comment by Errors4l** [comment]
@mlakmal If this issue is stopping your progress you can use the workaround in the issue I linked prior to last comment. You can have two separate `ContentChild` properties (one for static `true` and one for `false`) and return them in a getter with the `||` operator. I know it's not the same as Angular doing this automagically like it used to, but for the most part it works the same.

Keep in mind that the workaround uses a getter, which could be worse depending on your use case. If you're using the property in your template it'll have to call the getter each change detection cycle because Angular can't tell if the value has changed. Might this be a problem you could adopt a similar structure using ContentChild setters instead. Something like this:

```ts
  _labelChild: MatLabel;
  @ContentChild(MatLabel, {static: false})
  set _labelChildNonStatic(val: MatLabel) { this._labelChild = val; }  
  @ContentChild(MatLabel, {static: true})
  set _labelChildStatic(val: MatLabel) { this._labelChild = val;  }
```

**Comment by mlakmal** [comment]
thanks i am going to give this a shot. we have more than 100 occurrences in our code-base and have to review closely. i haven't seeing this issue in our external vendor libs yet (fingers crossed that it will not have this issue per alex comment above )

**Comment by maximelafarie** [comment]
I completely agree with this issue. Moreover, if you look into the code we can read this was expected to be optional (line 8038 in `code.d.ts` file):

> **static** - whether or not to resolve query results before change detection runs (i.e.
     return static results only). _**If this option is not provided**_, the compiler will **fall back
     to its default behavior**, which is to use query results to determine the timing of query
     resolution. If any query results are inside a nested view (e.g. *ngIf), the query will be
     resolved after change detection runs. Otherwise, it will be resolved before change detection
     runs.

**Comment by trotyl** [comment]
> If I look into the code I can read that this was expected to be optional

That's true, it should definitely be optional, and that's always happening: https://github.com/angular/angular/pull/32582, https://github.com/angular/angular/pull/32686, https://github.com/angular/angular/pull/32720

Making it required in v8 and optional again v9 is for warning about this breaking change, as the fallback behavior in v7 and v9 are different.

**Comment by pkozlowski-opensource** [comment]
The mentioned flag is optional in v9, so this issue got fixed via #32686
