### ISSUE TITLE
ivy-ngcc doesn't transform UMD bundles correctly

### ISSUE THREAD

**Issue by gregmagolan** [angular/angular#31394]
# 🐞 bug report

### Affected Package

 The issue is caused by ivy-ngcc tool

### Is this a regression?

no

### Description

ivy-ngcc transforms UMD bundles incorrectly. In particular, the symbol `Injectable` ends up as undefined in the transformed UMD bundle.

```
    AriaDescriber.decorators = [
        { type: core.Injectable, args: [{ providedIn: 'root' },] },
    ];
    /** @nocollapse */
    AriaDescriber.ctorParameters = function () { return [
        { type: undefined, decorators: [{ type: core.Inject, args: [common.DOCUMENT,] }] }
    ]; };
    /** @nocollapse */ AriaDescriber.ngInjectableDef = core.ɵɵdefineInjectable({ factory: function AriaDescriber_Factory() { return new AriaDescriber(core.ɵɵinject(common.DOCUMENT)); }, token: AriaDescriber, providedIn: "root" });
    return AriaDescriber;
```

in `node_modules/@angular/cdk/bundles/cdk-a11y.umd.js.__ivy_ngcc_bak` gets transformed to

```
/*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(AriaDescriber, [{
        type: Injectable,
        args: [{ providedIn: 'root' }]
    }], function () { return [{ type: undefined, decorators: [{
                type: Inject,
                args: [common.DOCUMENT]
            }] }]; }, { _document: [], describe: [], removeDescription: [], ngOnDestroy: [], _createMessageElement: [], _deleteMessageElement: [], _createMessagesContainer: [], _deleteMessagesContainer: [], _removeCdkDescribedByReferenceIds: [], _addMessageReference: [], _removeMessageReference: [], _isElementDescribedByMessage: [], _canBeDescribed: [], _isElementNode: [] });
    return AriaDescriber;
```

in `node_modules/@angular/cdk/bundles/cdk-a11y.umd.js` where `type: Injectable,` is undefined when run in the browser:

```
Uncaught ReferenceError: Injectable is not defined
```

I would guess it should be `type: core.Injectable` since `core` is the `@angular/core` UMD dependency.

`@angular/cdk/bundles/cdk-a11y.umd.js` is just an example but same thing happens in other bundles transformed.

## 🔬 Reproduction

Clone the `wassim/ivy` branch of my fork of angular-bazel-example (https://github.com/gregmagolan/angular-bazel-example/tree/wassim/ivy) and run `yarn install`. `ivy-ngcc` is run in the `postinstall` step and you can inspect the resulting transofmed bundles under node_modules.

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
The same also happens with `@angular/*` umd bundles.

I think the problem is located here
https://github.com/angular/angular/blob/21835af70cf0535273270be827633471d9ec465d/packages/compiler-cli/src/ngtsc/annotations/src/metadata.ts#L124-L127

If I check for property access then it works for me:

```
 function decoratorToMetadata(decorator) {
  const identifier = ts.isPropertyAccessExpression(decorator.identifier.parent) ? decorator.identifier.parent : decorator.identifier
  // Decorators have a type.
  var properties = [
    ts.createPropertyAssignment('type', ts.updateIdentifier(identifier)),
  ];
```

@alxhub Can you please take a look at this?

**Comment by petebacondarwin** [comment]
I'll take a look.

**Comment by petebacondarwin** [comment]
Hopefully https://github.com/angular/angular/pull/31426 should fix this.

**Comment by gregmagolan** [comment]
@petebacondarwin Thanks for the fix. I have good news and bad news. Will start with the good 🚀 

**Good**) Your fix which (landed in master & 8.1.x branch) fixed the issue observed for all of the angular bundles. The file ivy-ngcc `node_modules/@angular/cdk/bundles/cdk-a11y.umd.js` file now has:
```
    /** @nocollapse */ AriaDescriber.ngInjectableDef = core.ɵɵdefineInjectable({ factory: function AriaDescriber_Factory() { return new AriaDescriber(core.ɵɵinject(common.DOCUMENT)); }, token: AriaDescriber, providedIn: "root" });
AriaDescriber.ngInjectableDef = ɵngcc0.ɵɵdefineInjectable({ token: AriaDescriber, factory: function AriaDescriber_Factory(t) { return new (t || AriaDescriber)(ɵngcc0.ɵɵinject(common.DOCUMENT)); }, providedIn: 'root' });
/*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(AriaDescriber, [{
        type: core.Injectable,
        args: [{ providedIn: 'root' }]
    }], function () { return [{ type: undefined, decorators: [{
                type: core.Inject,
                args: [common.DOCUMENT]
            }] }]; }, { _document: [], describe: [], removeDescription: [], ngOnDestroy: [], _createMessageElement: [], _deleteMessageElement: [], _createMessagesContainer: [], _deleteMessagesContainer: [], _removeCdkDescribedByReferenceIds: [], _addMessageReference: [], _removeMessageReference: [], _isElementDescribedByMessage: [], _canBeDescribed: [], _isElementNode: [] });
    return AriaDescriber;
``` which correctly has `type: core.Injectable,`

**Bad**) The @ngrx umd bundles still have the same error originally observed in the angular bundles

```
        ActionsSubject = tslib_1.__decorate([
            core.Injectable(),
            tslib_1.__metadata("design:paramtypes", [])
        ], ActionsSubject);
        return ActionsSubject;
```

in `node_modules/@ngrx/store/bundles/store.umd.js.__ivy_ngcc_bak` is transformed to

```
ActionsSubject.ngInjectableDef = ɵngcc0.ɵɵdefineInjectable({ token: ActionsSubject, factory: function ActionsSubject_Factory(t) { return new (t || ActionsSubject)(); }, providedIn: null });
/*@__PURE__*/ ɵngcc0.ɵsetClassMetadata(ActionsSubject, [{
        type: Injectable
    }], function () { return []; }, { next: [], complete: [], ngOnDestroy: [] });
        return ActionsSubject;
```

in `` which has `type: Injectable` again and it fails in the browser at runtime.

There is a slight difference in that the ngrx bundle, which has `core.Injectable(),` while the issue observed with the cdk bundle `node_modules/@angular/cdk/bundles/cdk-a11y.umd.js.__ivy_ngcc_bak` had `type: core.Injectable,`.

**Comment by petebacondarwin** [comment]
I think the difference is that one uses the static property style of decoration and the other uses the call helper style.

```js
    AriaDescriber.decorators = [
        { type: core.Injectable, args: [{ providedIn: 'root' },] },
    ];
```

vs

```js
        ActionsSubject = tslib_1.__decorate([
            core.Injectable(),
            tslib_1.__metadata("design:paramtypes", [])
        ], ActionsSubject);
```

I guess we only fixed it for the static property style.

**Comment by JoostK** [comment]
I can confirm this was only fixed for the static properties syntax, not the `__decorate` syntax. I included a fix in #31614 which contains some more fixes to deal with decorators correctly.

**Comment by gregmagolan** [comment]
Confirmed that all the UMD bundles used by angular-bazel-example (including @ngrx which was using `core.Injectable()`) are correctly transformed now. Tested in https://github.com/angular/angular-bazel-example/pull/505. Thanks @petebacondarwin @JoostK!
