### ISSUE TITLE
ngc --watch ignores changes in templates (ivy)

### ISSUE THREAD

**Issue by stefanocke** [angular/angular#31982]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.1.2
(But, due to https://github.com/angular/angular/pull/31322, it only worked on every second change of a template.)

### Description

- I run ngc in watch mode. Output directory is out-tsc.
- Ivy is enabled.
- I change a component's template.
- ngc says "File change detected. Starting incremental compilation."
- However, the template change does not result in an according change in the *.js file in out-tsc directory.
- For changes in *.ts files, it works.

## 🔬 Minimal Reproduction
Example project is at: https://github.com/stefanocke/angular-cli-app-with-rollup
Please run:

npm i
npm run ngc-app-watch

Then, change app.component.html and look for app.component.js in tsc-out.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 10.16.0
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3

</code></pre>

**Anything else relevant?**
Ivy is enabled

**Comment by alxhub** [comment]
This is fixed in #31932 :D

**Comment by alxhub** [comment]
Also closing as a duplicate.

**Comment by stefanocke** [comment]
@alxhub , thank you.  Is  it supposed to be part of Angular 8.2.2 ?  It seems not to work yet.

**Comment by stefanocke** [comment]
@alxhub , it is still not working with 9.0.0-next.3
See [https://github.com/stefanocke/angular-cli-app-with-rollup](https://github.com/stefanocke/angular-cli-app-with-rollup) (steps tor reproduce see above)

Would you please reconsider / reopen?
