### ISSUE TITLE
Module @angular/common/common has no exported member 'ɵNgStyleImpl'. Did you mean 'ɵNgStyleR2Impl'?

### ISSUE THREAD

**Issue by JandroMejia97** [angular/angular#34963]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common and @angular/flex-layout

### Is this a regression?  

 Yes, the previous version in which this but not present was 8.2. 

### Description

 After migrating from Angular 8.2 to Angular 9, in the previous version I did not have this problem.

## 🔬 Minimal Reproduction

 The error appears after executing the `ng build --prod` command.

## 🔥 Exception or Error
```bash
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts:9:19 - error TS2724: Module '"path/node_modules/@angular/common/common"' has no exported member 'ɵNgStyleImpl'. Did you mean 'ɵNgStyleR2Impl'?

9 import { NgStyle, ɵNgStyleImpl, ɵNgStyleR2Impl } from '@angular/common';
```

## 🌍  Your Environment

**Angular Version:**
```bash
Angular CLI: 9.0.0-rc.10
Node: 12.8.0
OS: win32 x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cdk                      9.0.0-rc.8
@angular/cli                      9.0.0-rc.10
@angular/fire                     5.3.0
@angular/flex-layout              8.0.0-beta.27
@angular/material                 9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.10
@nguniversal/builders             9.0.0-rc.1
@nguniversal/common               9.0.0-rc.1
@nguniversal/express-engine       9.0.0-rc.1
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.5
```

**Anything else relevant?**

I am using VSCode as IDE and npm as package manager

**Comment by AndrewKushnir** [comment]
Thanks for reporting the issue @JandroMejia97. It looks like the problem appeared because `ɵNgStyleImpl` symbol [referenced by flex-layout package](https://github.com/angular/flex-layout/blob/ec7b57eb6adf59ecfdfff1de5ccf1ab2f6652ed3/src/lib/extended/style/style.ts#L18) was excluded from exported set in ["@angular/common" package](https://github.com/angular/angular/pull/34616/files#diff-73be8595226f56218c5052fb216aa5d1R13). We'll perform further investigation and keep this thread updated.

**Comment by victorlucss** [comment]
+1

**Comment by dimitri-bret** [comment]
I've tested with all package on angular 9 rc-11 and the  i got the same issue with flex-layout 8.0.0-beta.27.

**Comment by DutchKevv** [comment]
Appears to have been fixed by https://github.com/angular/flex-layout/commit/8099fca501e57de3580e6e2db125b2c904cfb684

**Comment by CaerusKaru** [comment]
Yes, this was fixed by the above commit and this issue can be closed (it probably should've been redirected to flex-layout in the first place, since this isn't really an Ivy issue).

**Comment by gkalpak** [comment]
Thx, @CaerusKaru! Can you also post here which version of `@angular/flex-layout` will include the fix?

**Comment by CaerusKaru** [comment]
It will be in the v9 release for Flex Layout, which should be cut either today or tomorrow.

**Comment by DutchKevv** [comment]
I;m still getting the error after upgrading to the latest flex-layout version

`error-handler.provider.ts:10 NullInjectorError: StaticInjectorError(AppModule)[DefaultFlexDirective -> StyleUtils]: 
  StaticInjectorError(Platform: core)[DefaultFlexDirective -> StyleUtils]: 
    NullInjectorError: No provider for StyleUtils!
    at NullInjector.get (http://localhost:4200/vendor.js:40304:27)
    at resolveToken (http://localhost:4200/vendor.js:54785:24)
    at tryResolveToken (http://localhost:4200/vendor.js:54711:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:54552:20)
    at resolveToken (http://localhost:4200/vendor.js:54785:24)
    at tryResolveToken (http://localhost:4200/vendor.js:54711:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:54552:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:66988:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:67848:16)
    at resolveDep (http://localhost:4200/vendor.js:68373:45)`

Anyone has a solution at hand? Thanks!

**Comment by gkalpak** [comment]
What version of `flex-layout` do you have?

**Comment by DutchKevv** [comment]
@angular/animations                ^9.0.0-rc.10  →        ^9.0.0-rc.13 
 @angular/cdk                         9.0.0-rc.8  →          9.0.0-rc.9 
 @angular/cli                       ^9.0.0-rc.10  →        ^9.0.0-rc.12 
 @angular/common                     9.0.0-rc.10  →         9.0.0-rc.13 
 @angular/compiler                   9.0.0-rc.10  →         9.0.0-rc.13 
 @angular/core                       9.0.0-rc.10  →         9.0.0-rc.13 
 @angular/flex-layout              8.0.0-beta.27  →       9.0.0-beta.28 
 @angular/forms                      9.0.0-rc.10  →         9.0.0-rc.13 
 @angular/material                    9.0.0-rc.8  →          9.0.0-rc.9 
 @angular/material-moment-adapter     9.0.0-rc.8  →          9.0.0-rc.9 
 @angular/platform-browser           9.0.0-rc.10  →         9.0.0-rc.13 
 @angular/router                     9.0.0-rc.10  →         9.0.0-rc.13 
 typescript                                3.7.5  →  3.8.0-dev.20200201 
 @angular-devkit/build-angular     0.900.0-rc.10  →       0.900.0-rc.12 
 @angular/compiler-cli               9.0.0-rc.11  →         9.0.0-rc.13 
 @angular/language-service           9.0.0-rc.11  →         9.0.0-rc.13 
 @types/node                              13.5.1  →              13.7.0

this is the diff from running OK, and up until I get the errors (reverting to 9.0.0.rc.10 works for me).

FlexLayout version 9.0.0-beta.28 also doesn't work with me

**Comment by gkalpak** [comment]
Looking at the error message again, this seems to be a different error. This issue was about missing `ɵNgStyleImpl`, while yours, @DutchKevv, is about not being able to find `StyleUtils` (which is [provided by `flex-layout`][1]).

I was going to suggest opening an issue on the `flex-layout` issue tracker, but I see you did that already :smiley:: angular/flex-layout#1186

[1]: https://github.com/angular/flex-layout/blob/f8e9d75e6/src/lib/core/style-utils/style-utils.ts#L16-L17

**Comment by dimitri-bret** [comment]
@DutchKevv  Do you have 
```JSON
{"enableIvy": false}
```
 in the ```angularCompilerOptions``` in your tsconfig.json file?
I had the same error, and removing this flag (which is true by default in Angular 9) solved the issue for me.
