### ISSUE TITLE
IVY LazyLoaded component doesnt use Module, where  is declared in 

### ISSUE THREAD

**Issue by montella1507** [angular/angular#35576]
Common usecase where you want to load component that depends on providers. You have:
1) Lazy loaded component
2) Module in the same file with providers and declaration of Lazy Loaded component

[city-quiz.zip](https://github.com/angular/angular/files/4230528/city-quiz.zip)

1. npm i
2. ng serve
3. click Start quiz
4. ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[BlackMagic -> BlackMagic -> BlackMagic]:

Note:
BlackMagic is class provided in QuizCardModule.
QuizCardComponent is Lazy loaded component and depends (constructor DI) on BlackMagic
QuizCardComponent is lazy loaded in app.component ln36
const quizCardFactory = this.cfr.resolveComponentFactory(QuizCardComponent); const {instance} = this.quizContainer.createComponent(quizCardFactory, null, this.injector);
it doesnt work even without this.injector
4) When you break code on this line:
const {instance} = this.quizContainer.createComponent(quizCardFactory, null);

you would see, that component is bound NOT TO QuizCardModule but to AppModule.

From what i have read in tutorials regarding Ivy and Lazy loading of components, QuizCardComponent should use as main injector that one from QuizCardModule and NOT AppModule.

**Comment by mlc-mlapis** [comment]
@montella1507 I looked at the source code and the line `.createComponent(quizCardFactory, null, this.injector);` is correct and `this.injector` represents the root injector, because it was resolved on the `AppComponent` level through DI.

It looks like that the used syntax:
```
@Injectable()
export class BlackMagic {}
```
+ `providers` metadata in `QuizCardModule` doesn't work as expected. I am not sure it this was mentioned somewhere as a breaking change for Angular 9.

But the syntax:
```
@Injectable(
  {providedIn: 'any'}
)
export class BlackMagic {}
```
without `providers` metadata in `QuizCardModule` works as expected.

**Comment by montella1507** [comment]
Yes however Even providers from imported.modules dont work... If they Are in providers array of.NgModule

**Comment by mlc-mlapis** [comment]
@montella1507 What do you mean by that. How would you access them if they are not singletons?

**Comment by mlc-mlapis** [comment]
@montella1507 Because there is no possibility of `exports` providers from such modules.

**Comment by montella1507** [comment]
Well the problém Is mainly with injecting of pipes...  To constructor - to use IT from code.

**Comment by mlc-mlapis** [comment]
@montella1507 And maybe this is the origin of the problem even in your case described above in combination with Angular 9 code base.

**Comment by mlc-mlapis** [comment]
@montella1507 Ah, ... what do you mean by `injecting of pipes`? Did you mean `services/providers` in fact?
> Well the problém Is mainly with injecting of pipes... To constructor - to use IT from code.

**Comment by montella1507** [comment]
Loook..
Before Ivy..
1)  you have Lazy loaded module with loadChildren "magic"
2) found component in NgModule by selector
3) resolved component factory 
4) created component with THAT Lazy loaded module injector - So IT behaved exactly thé samé way as if you used it in ,,normal way" in another component template..

IT was consistent - didnt matter if u use it normal.way or via lazy loading... And now in ivy?

A) if component used normally - it will get instances provided in module, where the component is declared (injector of that module will.be used)

B) if lazy loaded, app module injector is used (not that module) and you will not get instances provided in That module providers array.

**Comment by mlc-mlapis** [comment]
@montella1507 **But I agree with you that there is the issue** with using `providers` metadata declarations in the latest Angular 9.0.2. We showed it exactly above.

Now you have two options:

* Either use the following syntax without `providers` metadata (it means the actual trendy syntax because it is tree-shakable):
```
@Injectable(
  {providedIn: 'any'}
)
export class BlackMagic {}
```
* or wait for the reaction from the Angular core team on the issue described above + time till the moment this issue will be corrected (there is a question about its priority).

**Comment by mlc-mlapis** [comment]
@montella1507 Also the name of this issue is probably not correct because it is not about the fact that there is not the child injector on the lazily-loaded component/module, it is there, but the problem is that tokens defined by the `providers` metadata are not added into it.

> IVY LazyLoaded component doesn't use Injector of Module, where is declared in

So the better name can be probably:
`Child injector is not extended by metadata providers in lazily-loaded component`

**Comment by mlc-mlapis** [comment]
Maybe related to: https://github.com/angular/angular/issues/35580

**Comment by KhaydarshinAleksandr** [comment]
I think a similar issue was described here: https://github.com/angular/angular/issues/35268

**Comment by montella1507** [comment]
@KhaydarshinAleksandr  i dont think so.. 

I lazy-load  ModuleWithProviders  + Component in one file.  So i have APP -> LAZY_Module+Provider+Component   
= Common in several tutorials  - for example here https://netbasal.com/welcome-to-the-ivy-league-lazy-loading-components-in-angular-v9-e76f0ee2854a

He has  something WTF. :-)

**Comment by montella1507** [comment]
@mlc-mlapis  problem is, we will never have provideIn for pipes, directives, components... so you just cannot use lazy loaded component that depends on Pipe in constructor atm.

**Comment by montella1507** [comment]
@mlc-mlapis  check this PR of mine please:
https://github.com/wags1999/angular-hmr-lazy-components/pull/3/files

this is how was it done before IVY - notice that you were using MODULE's injector:
https://github.com/wags1999/angular-hmr-lazy-components/pull/3/files#diff-40c6d985c5d617e25d816796d01f9fabR31

so you had created Component from Lazy loaded module with Injector of that module - so everything behaved like you have lazy loaded component via Router Lazy routes...   Like a charm.

Don't you know how to make this code working on IVY?? I Can lazy lode Module, but.. it is instance class without any methods, without declarations etc...

**Comment by montella1507** [comment]
@mlc-mlapis  but you are propably right, problem is with providers metadata... even if i change code to this:

   const { QuizCardModule } = await import('./quiz-card/quiz-card.component');
    const compiledModule = this.compiler.compileModuleAndAllComponentsSync(QuizCardModule);
    const factory = compiledModule.componentFactories.find(x => x.selector == 'quiz-card');
    const { instance } = this.quizContainer.createComponent(factory, 0);

to resolve component from module i am still not able to get BlackmMagic provider....

So it has nothing to do with Injector... LazyLoaded module do not provide providers metadata.

**Comment by michaelz** [comment]
I use [AGM](https://github.com/SebastianM/angular-google-maps) on my site in a lazy-loaded module. Since the migration to Angular 9, when I load the map, I have the following error: 
```
R3InjectorError(AppModule)[MapsAPILoader -> MapsAPILoader -> MapsAPILoader]: 
  NullInjectorError: No provider for MapsAPILoader! 
```

Any chance this issue is related ? The workaround was to load the module manually in app.module.ts, thus disabling the lazyload feature. Could this be fixed by an update to the AGM Module ?

**Comment by mlc-mlapis** [comment]
@michaelz Yep, I think that's the same sort of problems.

Using `providedIn` syntax instead of `providers` metadata solves the problem, like
`@Injectable({providedIn: 'any'}) ... ` or `@Injectable({providedIn: 'root'}) ... `, but you need access to modify that module, which is the situation not available immediately for third party modules.

**Comment by montella1507** [comment]
To be honest... with come of Angular Component's locality, provideIn: any etc i think there is only one reason for module existence... providers... and if you wanna keep NgModules, thre is only one reason for existence (because of provideIn of injectables) = providers array.  IF they do not work correctly, there is no reason for NgModules anymore (and we can just import barel index.ts files with reexports of components...) 

That new style of lazy loading (loading component and module is resolved by declaration of this component) iws kind of magic anyway... even bigger magic than loadChildren: () => syntax

**Comment by solymosi** [comment]
I ran into the same or at least a very similarly-looking issue when manually lazy-loading a module using the `ɵcreateInjector` method. It seemed like this method did not set up the `NgModuleRef` properly, causing e.g. `ComponentFactoryResolver` to use the wrong injector.

After looking around in the Angular source code I have put together the following class for dynamically loading modules:

```typescript
import { Injectable, Type, NgModuleRef, ɵNgModuleFactory as NgModuleFactory, Injector } from '@angular/core';
import { Observable, from } from 'rxjs';
import { map } from 'rxjs/operators';

export type ModuleImportFunc<T> = () => PromiseLike<Type<T>>;

@Injectable({
  providedIn: 'root'
})
export class ModuleLoaderService {
  constructor(
    private injector: Injector,
  ) { }

  loadRef<T>(loader: ModuleImportFunc<T>): Observable<NgModuleRef<T>> {
    return from(
      loader().then(type => new NgModuleFactory(type).create(this.injector)),
    );
  }

  load<T>(loader: ModuleImportFunc<T>): Observable<T> {
    return this.loadRef(loader).pipe(
      map(ref => ref.instance),
    );
  }
}
```

This seems to properly set up DI for the loaded module, including providers from modules imported by the lazy-loaded module.

**Comment by montella1507** [comment]
Will try with example in ZIP filé above

Stáhněte si Outlook pro Android<https://aka.ms/ghei36>

________________________________

**Comment by mlc-mlapis** [comment]
@solymosi Yep, the manual creating of a module instance and passing the injector can be the way. But still, the issue should be resolved. It's a bit surprising for me that this issue still lays out of the attention of the Angular core team.

**Comment by montella1507** [comment]
> @solymosi ... it's a bit surprising for me that this issue still lays out of the attention of the Angular core team.

yeah, but manually lazy loading of components / modules is not so common in angular community...  and there are issues with way bigger area of  impact.

**Comment by solymosi** [comment]
> Will try with example in ZIP filé above

No need, I already did it.

First, I had to expose the component type on the module and export the module:

```typescript
@NgModule({
  declarations: [QuizCardComponent],
  imports: [CommonModule, MatCardModule, MatButtonModule],
  providers: [BlackMagic]
})
export class QuizCardModule {
  componentType = QuizCardComponent;
}
```

Then, after copy-pasting the loader service class into `module-loader.service.ts`, all that was needed in `AppComponent` is the following:

```typescript
  showNewQuestion() {
    this.lazyLoadQuizCard().subscribe();
  }

  startQuiz() {
    this.lazyLoadQuizCard().subscribe(() => this.quizStarted = true);
  }

  private lazyLoadQuizCard(): Observable<void> {
    return this.moduleLoader.loadRef(
      () => import('./quiz-card/quiz-card.component').then(m => m.QuizCardModule)
    ).pipe(
      tap(ref => {
        const factory = ref.componentFactoryResolver.resolveComponentFactory(ref.instance.componentType);
        const {instance} = this.quizContainer.createComponent(factory, null, ref.injector);
        instance.question = this.quizservice.getNextQuestion();
        instance.questionAnswered.pipe(
          takeUntil(instance.destroy$)
        ).subscribe(() => this.showNewQuestion());
        (instance as any).ngOnChanges({
          question: new SimpleChange(null, instance.question, true)
        });
        this.quizStarted = true;
      }),
      mapTo(undefined)
    );
  }
```

...and it works:

![image](https://user-images.githubusercontent.com/199790/76515896-b41f3600-645a-11ea-8d1d-8369e270c6fe.png)

**Comment by lucaswxp** [comment]
@solymosi Thanks, this solves it!

**Comment by JoostK** [comment]
This looks like the same problem as #35759 for which I commented on how to make it work: https://github.com/angular/angular/issues/35759#issuecomment-601444856.

It describes the same approach as presented by @solymosi without depending on private API (the outcome is exactly the same, though).

I did not look into this issue further at this point, so I can't comment on how this could be a regression compared to ViewEngine.

**Comment by mc-lovin** [comment]
Thanks @JoostK @solymosi

**Comment by Mihail04** [comment]
@solymosi Hi. i have close problem like the @montella1507. 

NullInjectorError: R3InjectorError(AppModule)[DynamicLoaderService -> DynamicLoaderService -> DynamicLoaderService]

I load module from library, and inside this module declarete component who uses DynamicLoaderService. DynamicLoaderService i provide in appModule, and he also from library.

If i add  providedIn: 'any' or 'root', error is gone, but DynamicLoaderService is not be singalton. In component from lazyLoadModule createts new instance DynamicLoaderService.

i tried use ɵcreateInjector and NgModuleFactory, but result the same.

**Comment by mlc-mlapis** [comment]
@[**montella1507**](https://github.com/montella1507) Previously I missed the most important fact, that you were loaded only a component (and not that lazily loaded module, as I supposed by an unexplained reason), as `const {QuizCardComponent} = await import('./quiz-card/quiz-card.component');` It's the crucial difference. Lazy loading only a component is the limited case focused usually on the situation when all dependencies starts on that component level. If there are more wider dependencies, started from the module level, you have to lazy load that module and then instantiate a concrete component from that module.

So this issue was an issue in fact and I think that it's possible to close it.

**Comment by mrVers** [comment]
Thanks for all the comments in this thread, it made things a bit more clear on my end. In my case I was trying to lazy-load a component inside a bootstrap modal window, but needed the module loaded first as it had external dependencies. 

This is my take on component/module lazy loading:

```
@ViewChild('listing', { read: ViewContainerRef }) listingContainer: ViewContainerRef;
  listingData: any;
  listingInstance: any;

  constructor(
    private compiler: Compiler,
    private injector: Injector
  ) {
  }

  ngOnInit() {
    this.lazyLoadListing();
  }

  async lazyLoadListing() {
    const m = await import(/* webpackPrefetch: true */'../../../listing/listing.module');
    const c = await import(/* webpackPrefetch: true */'../../../listing/listing.component');

    // compile listing-module
    this.compiler.compileModuleAsync(m.ListingModule).then(moduleFactory => {
      const moduleRef = moduleFactory.create(this.injector);
      const componentFactory = moduleRef.componentFactoryResolver.resolveComponentFactory(c.ListingComponent);

      // create listing component
      this.listingContainer.clear();
      const { instance } = this.listingContainer.createComponent(componentFactory);

      // saving the instance so I am able to access the generated component, inject data and call its functions 
      this.listingInstance = instance;

      // update component data
      this.listingInstance.listing = this.listingData;
    });
  }
```

Hope this makes things easier for people having the `NullInjectorError` error when lazy-loading components.
