### ISSUE TITLE
ES6 template literal expressions not working past v9

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#35584]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ^8

### Description

Using a template literal expression used to work until Angular 9, for as long as the template lived in the TS source not in HTML (_obviously_).

Since Angular 9 that does not work any longer in one scenario. I am mostly focusing on library builds here:

**Working**
- build library with Angular 9 Ivy & serve the Angular 9 application
- build library with Angular 8 View Engine & serve the Angular 8 application
- build library with Angular 8 View Engine & serve the Angular 9 application (`ngcc`)

**Not working**
- build library with Angular 9 View Engine (`ng build lib --prod`) & serve the Angular 9 application (`ngcc`)

## 🔬 Minimal Reproduction

In any Angular workspace create a library and do the following:

```ts
const enum Demo {
  First
}

@Component({
  template: `
    Static variable: ${ Demo.First  }
  `
})
export class DemoComponent {}
```

## 🔥 Exception or Error
```
error NG1010: template must be a string
```

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.0.3
Node: 12.15.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       9.0.1
@angular/cli                       9.0.3
@angular/material                  9.0.1
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.0.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

**Anything else relevant?**

I am not 100% sure this was ever officially supported, even though I would have hoped so, since it is native ES6 feature. If it wasn't supported, please close the issue.

Interesting observation is, that View Engine compiled library from Angular 8 is correctly processed by `ngcc`, while View Engine from Angular 9 surprisingly fails.

---

**EDIT**: Seems like an easy reproduction mentioned above is not reproducible any more. I can still reproduce it, if I use literal expressions while binding to input, e.g.: `[title]="${variable}"`.

Reproduction:
- Clone: https://github.com/klemenoslaj/template-literal-expressions-issue
- Execute: `yarn && yarn reproduce`

Resulting in error:

```
dist/example/fesm2015/example.js:29:19 - error NG1010: template must be a string

29         template: `
                     ~
30     <button [title]="${ButtonType.Button}">Button</button>
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
31   `
   ~~~
dist/example/fesm2015/example.js:39:24 - error NG6001: The class 'ExampleComponent' is listed in the declarations of the NgModule 'ExampleModule', but is not a directive, a component, or a pipe.
```

**Comment by paresh-bhave** [comment]
Hi @klemenoslaj ,

I tried to reproduce above issue but I couldn't. Application ran successfully. Details below:

`DemoComponent` from demo library module:

```javascript
import { Component, OnInit } from '@angular/core';

const enum Demo {
  First
}

@Component({
  selector: 'lib-demo',
  template: `
    <p>
    Static Variable: ${ Demo.First }
    </p>
  `,
  styles: []
})
export class DemoComponent implements OnInit {
  constructor() { }
  ngOnInit(): void {
  }
}

```

I built the demo library with `ng build demo --prod` option and then used it in AppComponent like this. (served with --aot)

```javascript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <lib-demo></lib-demo>
  `
})
export class AppComponent {}
```
 
My output:
Static Variable: 0

Environment:
```
Angular CLI: 9.0.3
Node: 10.16.3
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cli                       9.0.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

As far as I know, ES6 template literal expressions always worked for me and like you said, it's an ES6 feature so I'm not sure if this issue is related to Angular 9.

**Comment by klemenoslaj** [comment]
@paresh-bhave thanks for the investigation. I will double-check later today on my side and will report the results. I will provide the repository if I manage to reproduce it still.

**Comment by klemenoslaj** [comment]
@paresh-bhave interestingly it is still broken for me.

Can you please confirm you built library project, not in the application (_it works in the application for me as well_)? As I wrote in the issue, library build fails:

>build library with Angular 9 View Engine (ng build lib --prod) & serve the Angular 9 application (ngcc)

**Comment by paresh-bhave** [comment]
@klemenoslaj  I apologise for the delay.. I couldn't get a chance to verify this. Yes, I can confirm that I built the library project. I see your updated comment and glad it's resolved for you.

**Comment by petebacondarwin** [comment]
Is the latest on this issue that the following is not working?

> build library with Angular 9 View Engine (ng build lib --prod) & serve the Angular 9 application (ngcc)

**Comment by paresh-bhave** [comment]
@petebacondarwin I believe it's working and there is no issue with the library build. @klemenoslaj was facing certain issue with template literal expression but as per my investigation it doesn't seem to be related Angular 9.

**Comment by petebacondarwin** [comment]
Thanks for the info. I will close this issue. Please open a new issue if there are still any unresolved problems.

**Comment by klemenoslaj** [comment]
@petebacondarwin it is a misunderstanding. The issue is still there, please have a look at my edit.

As I wrote the initial, easy reproduction is fixed, however the template literal within binding is still broken.

Please check the repo I have provided in an edit...

**Comment by petebacondarwin** [comment]
This does appear to be a valid bug when we are trying to convert an ES5 expression to a string before parsing it as a template. E.g.

```
"abc" + MyEnum.Value + "def"
```

At the moment this does not get evaluated to a string. (It works in ngtsc because that is working directly with the template string literal (backticked string).

Tracking as FW-1951

**Comment by paresh-bhave** [comment]
> @petebacondarwin, @paresh-bhave misunderstood me, sorry for being unclear :(. The issue is still there, please have a look at my edit.
> 
> As I wrote the initial, easy reproduction is fixed, however the template literal within the binding as shown in an issue is still broken.
> 
> Please check the repo I have provided in an edit.
> Can we please re-open this issue? I don't want to copy paste.
> 
> **EDIT**
> 
> @petebacondarwin Thanks for re-opening, and sorry for the confusion caused.

I apologise for the confusion as well

**Comment by dewwwald** [comment]
I recently mused an idea. See tweet here

https://twitter.com/dewwwald/status/1243532118413791233

Was wondering if a new feature is in order as I find this method where template is included in the file  using string to be something that I don't like.

`<div #dataWarehouse="import('./data-warehouse.enum')">
{{dataWarehouse.MyEnum.Yes}}
{{http://dataWarehouse.MyEnum.No}}
</div>`

The idea is that using an angular-esk sintax one might be able to import an enumerable.

I know there are some security concerns, nothing that can't be solved during compilation though.

**Comment by distributev** [comment]
**_When I build for prod I get the same_** 

**_error NG1010: template must be a string_**

followed by a 

**_error NG6001: The class 'YYYComponent' is listed in the declarations of the NgModule 'YYYModule', but is not a directive, a component, or a pipe_**.

**_I use Angular 9.1.0_**

My code looks like 

```
import leftMenuTemplate from '!!raw-loader!./templates/_left-menu.html';

@Component({
  selector: 'yyy-component',
  template: `
    <aside class="main-sidebar">
      <section class="sidebar">${leftMenuTemplate}</section>
    </aside>
   `
})

```
**_When I build for development everything works fine._**

Since things are working fine when I do the development build I went to angular.json in the production section and tried to play with the "optimization": true, "aot": true and "buildOptimizer": true - I switched off these settings one by one but the compilation error was still persisting every time one of the three was false and the other two were true.

I managed to get the compilation working when in angular.json production section I have

```
 "production": {
              "optimization": true,
              "aot": false,
              "buildOptimizer": false
}
```

**Comment by klemenoslaj** [comment]
@distributev this works fine when compiled in development mode, because it's using the Ivy engine.

The problem is, when you compile the library for the release with `--prod` ViewEngine will be used and then on the consumer end `ngcc` will compile that library from ViewEngine to Ivy again.
I think here is the problem.

However as I wrote above, with ViewEngine from Angular 8 everything works fine.

**Comment by klemenoslaj** [comment]
Thanks everyone involved for the effort so far!

---

@kara looking at the changelog, the commit cbc25bb was included in the already published version `9.1.1`, correct?

I just updated my reproduction repository, and unless I am missing something, the original issue is still not fixed.

I created the branch in the original repo with Angular updated to version `9.1.1`.

**Reproduction**:

Clone: https://github.com/klemenoslaj/template-literal-expressions-issue
Checkout: `reproduce-with-angular-9.1.1`
Execute: `yarn && yarn reproduce`

Triggering `yarn reproduce` (_an alias for library production build and `ng serve`_) still throws the same error as before.

**Comment by JoostK** [comment]
Hi @klemenoslaj,

thanks for letting us know, this was indeed part of 9.1.1. I'll look at it again, sorry for the inconvenience!

**Comment by JoostK** [comment]
Oh, there were actually two bugs and I only fixed one. The remaining one is a bit more complex, it would seem.

TypeScript emits enums in JavaScript as follows:
```js
var Example;
(function (Example) {
    Example["Value"] = "Title";
})(Example || (Example = {}));
```

Therefore, it's no longer syntactically an enum, and ngcc needs specialized support to make sense of this structure.

The whole template literal was a distraction, although there was a bug there as well. That part got fixed in cbc25bbf31b84b0d350af7f92c15cfcba183d7c9, the enum inspection did not. Sorry for not actually verifying the fix with your repro, I should have done that!

**Comment by distributev** [comment]
I updated myself to 9.1.1 and I can confirm this error is still happening and I get the same errors as before. Please check the scenario I described above for more details on my environment.

**Comment by klemenoslaj** [comment]
@JoostK 

> Therefore, it's no longer syntactically an enum, and ngcc needs specialized support to make sense of this structure.

Does that mean that some potentially more complex custom constructs wouldn't work either?

> Sorry for not actually verifying the fix with your repro, I should have done that!

Thanks for your hard work :+1: As it seems like this was a tricky situation.

**Comment by JoostK** [comment]
@klemenoslaj ngcc supports a lot of syntax that is specific to a certain emit format. E.g. classes don't look like classes in ES5, module imports don't look like modules in UMD etc. but ngcc is still able process them as such. Some of this work is supported [by TypeScript through project Salsa](https://github.com/microsoft/TypeScript/issues/4789), but also a lot of heavy lifting to make it all work is done in ngcc itself.

Support for enums is not done as part of project Salsa and we don't currently handle it specially in ngcc, so it fails to work. Any other syntax that is emitted into JavaScript in a different way than the original source code may also need special handling to make it appear as the original code, but this is only really needed for when it is part of code that must be statically evaluated at compile time.

**Comment by JoostK** [comment]
Hi @klemenoslaj and @distributev,

I opened a draft PR that implements support for enums. I was able to confirm this resolves the problem in @klemenoslaj's repro project, but you can try it yourselves by replacing the `@angular/compiler-cli` version with the PR's artifact:

```diff

-    "@angular/compiler-cli": "9.1.1",
+    "@angular/compiler-cli": "https://678189-24195339-gh.circle-artifacts.com/0/angular/compiler-cli-pr36550-41edc95309.tgz",
```

Please let me know whether that resolves your issue. The fix may not be part of the next release, but once we do get it released it would be good to know whether it works for you :-) Thanks in advance!

**Comment by klemenoslaj** [comment]
Hi @JoostK, the issue is partially resolved :+1: Thanks a lot!

---

I did found out that the `enum` without the initializer or `enum` initialized with numbers won't work.

**Works**
```ts
enum Example {
  Value = "Title"
}

template: `
  ${Example.Value}
`
```

**Doesn't work**
```ts
enum Example {
  Value
}

template: `
  ${Example.Value}
`
```

**Doesn't work**
```ts
enum Example {
  Value = 1
}

template: `
  ${Example.Value}
`
```

I created a new branch for this reproduction.

**Reproduction**:

Clone: https://github.com/klemenoslaj/template-literal-expressions-issue
Checkout: reproduce-without-initializer
Execute: `yarn && yarn reproduce`

**Comment by JoostK** [comment]
@klemenoslaj Thanks for testing! And indeed, the emitted JS is different for those variants so we need to handle that as well. I can get that sorted out in the PR, shouldn't be too much trouble.

While working on this yesterday I noticed a bug for numeric enums even for the original TypeScript code, so there's some more work to be done in this area.

**Comment by distributev** [comment]
Hi @JoostK, do you think your PR will handle my situation as well?

**Comment by JoostK** [comment]
@distributev Your issue appears to be unrelated to the issue with enums that is being fixed in #36550, so no. I was under the assumption that you were having the same issue as reported here, but upon reading your comment I don't think it is. I think it's the custom loader you're using, in which case it may be related to #30721. Without more info I couldn't say for sure, though.

**Comment by JoostK** [comment]
@klemenoslaj These new artifacts resolve the issue with numeric enums:

```diff
-   "@angular/compiler-cli": "~9.1.1",
+   "@angular/compiler-cli": "https://679046-24195339-gh.circle-artifacts.com/0/angular/compiler-cli-pr36550-81a5ec1478.tgz",
```

Note however that ngcc is now smarter than ngtsc itself, as ngtsc doesn't yet handle numeric enums correctly.

**Comment by sourcekraft** [comment]
@JoostK the error message I get it is exactly the same as the one noted in this issue - I believe the custom loader works fine and it is loading the content fine, the issue appears when angular is evaluating the template (leftMenuTemplate comes populated with the correct data from the loader). You could ignore my custom loader and you could assume that leftMenuTemplate contains a string and the problem still appears. 

This issue was raised as _ES6 template literal expressions not working past v9_ and I believe that #36550 should fix that - the enums are part of the problem.

As I noted earlier, if I build the code above with the default angular.json development configuration everything compiles fine and the application works perfectly at runtime - if I build the same application with the default angular.json production configuration at compile time it spits out the same error messages mentioned in this thread

**Comment by JoostK** [comment]
@sourcekraft Are you @distributev at the same time?

If it's not the custom loader, it might be the default export. I don't see any enums in the example from @distributev, so I don't see how enums are part of the problem? If you wish, you can test with the PR's artifact to test it out on your project, see my previous comment.

**Comment by distributev** [comment]
Sorry @JoostK I was logged in and commented with a different user.

The issue is called

_ES6 template literal expressions not working past v9_

and as you can see the title is not mentioning anything about enums. Indeed, @klemenoslaj gave an example with an enum however I believe the issue is wider and goes beyond the enum example which happened to be the first example.

The title describes exactly the situation I exemplified.

**Comment by JoostK** [comment]
@distributev This issue brought up two issues as identified for now:

1. String concatenation with enum values is not working
2. Enum values cannot be resolved in ngcc

The first issue occurs when using the `+` operator on strings, which is how template literal expressions appear in JavaScript that ngcc needs to process. This was addressed in #36461 and has been released in 9.1.1, but this fix was not sufficient as it exposed issue 2. The second issue is being addressed in #36550 which has not yet been released.

Both of these problems are surrounding the usage of enums, so although the title doesn't mention that, it has been the root cause of the reported issue. If you are seeing the same error, it may be caused by the usage of enums in which case #36550 may fix it, but if you're not using any enums and are still seeing the same error, then its root cause is unknown and it should be considered a different issue.

If you can provide a minimum repro, preferably a Github repo, I can establish the root cause for you and determine how best to proceed.

**Comment by distributev** [comment]
@JoostK Thank you for your help and for your hard work. 

I believe the issue can be reproduced with the simple scenario I described above. You could hard-code the leftMenuTemplate as a plain string to be used in the interpolation and the issue will still appear.

**Comment by JoostK** [comment]
@distributev I did some tests with the following snippet:

```ts

const leftMenuTemplate = '<span>Test</span>';

@Component({
  selector: "app-example",
  template: `<aside class="main-sidebar">
      <section class="sidebar">${leftMenuTemplate}</section>
    </aside>`,
})
export class ExampleComponent {
}
```

This works just fine using Angular 9.1.1 without #36550, both when targeting ES2015 vs ES5, and ngtsc (app) vs ngcc (library).

**Comment by distributev** [comment]
Did you do the angular.json production build? Production build configuration is what it is failing - if you build for development it will work fine.

**Comment by JoostK** [comment]
@distributev Works fine either way. If you say development build, that probably has `aot` set to `false`. The values for `optimization` and `buildOptimizer` options should be irrelevant.

**Comment by sourcekraft** [comment]
Strange, it might be from the raw-loader then but I don't see how raw-loader would work in the development build and fail the compilation in the production build. 

I gave more details in my first post what I mean with 'development' and 'production' build configuration (basically what angular.json offers by default)

@JoostK Thank you for your help!

**Comment by klemenoslaj** [comment]
> Did you do the angular.json production build? Production build configuration is what it is failing - if you build for development it will work fine.

Can you try to make a TS file exporting your template as string instead? Then import and use this string in your component template instead, to validate if raw-loader has something to do with it.

I am proposing this, because I am using it (not extensively tho) in one of my projects and it works fine.
