### ISSUE TITLE
For structural directives with empty attribute the corresponding @Input-method is not called

### ISSUE THREAD

**Issue by yankee42** [angular/angular#35726]
# 🐞 bug report

### Is this a regression?

Yes, this works at least in angular 7.1, 8.2.9

### Description

When using a structural directive, but with an empty attribute, the corresponding setter for that property is not called. This might be intentional and not a bug, however it would then be an API-change which I did not find anything in the migration guide about and it is also inconsistent with the behaviour of non-structural directives.

## 🔬 Minimal Reproduction

The following example is a custom directive which uses `*appShow` to show some content and `*appShow="false"` to hide the content. The directive itself is of course rather useless, however it is the simplest showcase I came up with. The test fails on angular 9.0.0 and 9.0.2, but passes at least on 8.2.9 and on 7.1.0:

```typescript
import { Component, DebugElement, Directive, Input, Predicate, TemplateRef, ViewContainerRef } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';

@Component({
    template: `
        <div *appShow>
            <p id="show">This should show</p>
        </div>
        <div *appShow="false">
            <p id="noShow">This should hide</p>
        </div>`
})
class TestShowDirectiveComponent {
}

@Directive({
    selector: '[appShow]'
})
class ShowDirective {

    constructor(private templateRef: TemplateRef<any>,
                private viewContainer: ViewContainerRef) {}

    @Input()
    set appShow(show: boolean | '') {
        if (show !== false) {
            this.viewContainer.createEmbeddedView(this.templateRef);
        } else {
            this.viewContainer.clear();
        }
    }
}


fdescribe('AppShowDirective', () => {
    let fixture: ComponentFixture<TestShowDirectiveComponent>;

    beforeEach(() => {
        TestBed.configureTestingModule({
            imports: [],
            declarations: [TestShowDirectiveComponent, ShowDirective],
        });

        fixture = TestBed.createComponent(TestShowDirectiveComponent);
        fixture.detectChanges();
    });

    function elementExists(selector: Predicate<DebugElement>): boolean {
        return fixture.debugElement.queryAll(selector).length === 1;
    }

    it('should show only content without param', () => {
        expect(elementExists(By.css('#show'))).toBe(true);
        expect(elementExists(By.css('#noShow'))).toBe(false);
    });
});
```
## 🌍  Your Environment

**Angular Version:**
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 12.15.0
OS: linux x64

Angular: 9.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.2
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by Achilles1515** [comment]
To support Ivy,

https://angular.io/guide/template-typecheck#input-setter-coercion

So given your example, it would be:
`static ngAcceptInputType_appShow: boolean|'';`

**Comment by JoostK** [comment]
@Achilles1515 This is not a type checking issue, so your suggestion would unfortunately not resolve this issue.

**Comment by Achilles1515** [comment]
> @Achilles1515 This is not a type checking issue, so your suggestion would unfortunately not resolve this issue.

Got it. I think the example code wouldn't have compiled because of the type checking issue I mentioned, but the OP example code was edited to fix it.

Issue Reproduction:
https://ng-run.com/edit/9EPxg6s3vxgozYYliPPN

**Comment by kara** [comment]
It looks like the problem here is that we're not generating the property instruction for the first `div`, so the runtime doesn't know to set the input property to undefined.

**Comment by iwantwin** [comment]
I've just upgraded a project van angular 8 to angular 10 and bumped into this issue. Took a while before finding this issue. I managed to work around the issue by just rebuilding the custom structural directive to always require an @Input parameter, which might help other people bumping into this issue as well.

However this is intended to be a temporary workaround, is there any new on when we can expect this bug to be fixed? And is there any way for me to support to help fix this issue? (@AndrewKushnir I saw you working on a PR to fix this?)

**Comment by douglasward** [comment]
I have just bumped into this whilst upgrading our project as well. 

@kara or @AndrewKushnir is this a problem with all inputs for structural directives? I have created a demo where all inputs other than the input named the same as the directive selector are *not* triggered: https://stackblitz.com/edit/angular-hghkms

Is this the same issue as described above or should I open a new one?

**Comment by AndrewKushnir** [comment]
@douglasward, I've just looked at the repro and the behavior seems to be the same in Ivy and ViewEngine (I see 3 log entries in both cases). Could you please check the behavior once again and share more info on how to reproduce the error?

**Comment by douglasward** [comment]
@AndrewKushnir yes, with the package verisons in that example the behaviour seems to be the seem withIvy and ViewEngine. But the behaviour is still wrong isn't it? I think there should be 4 console log entries not 3.

I downgraded the versions to match the ones in our project and there with ivy enabled I could get the 4 console logs to appear: https://stackblitz.com/edit/angular-aez5m4

**Comment by AndrewKushnir** [comment]
Hi @douglasward, thanks for providing additional information.

Structural directives support inputs from the [microsyntax expression](https://angular.io/guide/structural-directives#microsyntax) defined for a given directive, all other attrs/props are not considered valid inputs. There was a problem in early versions of Ivy (and I believe 9.1.0 was affected as well) where this was not the case and structural directives also used other attrs/props as inputs. This was fixed and now the behavior is consistent between ViewEngine and Ivy, so having 3 `console.log`s is the correct behavior.

I had a look at the [Structural Directives](https://angular.io/guide/structural-directives) guide and while it talks about the microsyntax, I believe we can add a couple sections there to cover:
- the fact that only microsyntax expression is used to get inputs from
- an example on how to define multiple inputs

You can also look at the [NgIf directive](https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_if.ts) (*ngIf) which has a number of inputs derived from the microsyntax expression.

Thank you.

**Comment by douglasward** [comment]
Thank you ever so much, @AndrewKushnir. I was not aware that *only* the microsyntax expression works for structural directives - I have updated our project and everything now works as expected!

Should I create a new issue regarding updating the documentation?

**Comment by AndrewKushnir** [comment]
Hi @douglasward,

> Should I create a new issue regarding updating the documentation?

Yeah, that'd be great, thanks!

Please let us know if you have a chance and want to create a PR for it too, we'll be glad to help review and land it.

Thank you.

**Comment by guzmanoj** [comment]
@AndrewKushnir I think this is still not working as expected. Please have a look here https://stackblitz.com/edit/angular-35jrwu
This is just a dummy example, the structural directive should render the element no matter what. However, it fails for the first case just because the applied `*appFoo` directive is empty.
I have also tried the approach described here: https://angular.io/guide/template-typecheck#input-setter-coercion
But adding such static property (`ngAcceptInputType_appFoo`) to the class doesn't seem to work either.
Disabling Ivy in the `tsconfig` solves the issue though.
By the way, it looks like someone else has found a way to fix it but his PR is lost in time (1-year-old) https://github.com/AndrewKushnir/angular/commit/86d5041c40dd9418d461925018231c84d0673a96

**Comment by AndrewKushnir** [comment]
Hi @guzmanoj, the mentioned fix (that you refer to) was put on hold due to the fact that it'd slightly increase payload size of the generated code (more info needs to be included) and more investigation is needed to assess the impact. As a temporary solution, you can try adding the logic into either directive's constructor or use `ngOnInit` lifecycle hook and check for the case when directive was initialized, but no input provided.

**Comment by alxhub** [comment]
We're going to close this as something we don't intend to fix.

`*appShow` is Angular-specific "microsyntax", and is not intended to behave the same as a value-less attribute (that is, it's semantically different than `<input disabled>`).

Instead of relying on side-effectful setters, component authors can use `ngOnInit` to handle the case where the input has not been set.
