### ISSUE TITLE
Angular 14 unnecessarily warning about not animatable properties?

### ISSUE THREAD

**Issue by diegovilar** [angular/angular#46602]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

It seems Angular 14 is warning about the presence of not animatable style attributes in a `transition()` call *whether or not* the implementation sets them as part of an `animate()` call.

In the following implementation, styles set in ```query(":enter, :leave")``` are preparation styles to be applied for the duration of the transition but are not set up to be animated. Still I get a warning about `position` and `overflown` not being animatable.

```typescript
transition("* => fade", [
  style({ position: "relative" }),

  query(":enter, :leave", [style({
    position: "absolute",
    inset: "0 0 0 0",
    overflow: "hidden",
  })]),

  query(":enter", [style({ opacity: 0 })]),
  query(":leave", [animateChild()]),

  group([
    query(":enter", [animate("150ms ease-out", style({ opacity: 1 }))]),
    query(":leave", [animate("50ms", style({ opacity: 0 }))]),
    query("@*", [animateChild()]),
  ]),
]);
```

The `animate()` calls above are specific about which attributes are to be animated, so they are not trying to animate towards all the attributes of the destination state.

Am I wrong in my understanding of how transitions in Angular work or is the compiler being unnecessarily critic in the new version?

### Please provide the exception or error you saw

```true
The animation trigger "ngxRouterAnimation" has built with the following warnings:
 - The following provided properties are not animatable: position, overflow
   (see: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.15.1
Package Manager: pnpm 7.3.0 
OS: linux x64

Angular: 14.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@angular/cli                    14.0.2
@schematics/angular             14.0.2
ng-packagr                      14.0.2
rxjs                            7.5.5
typescript                      4.7.4
webpack                         5.73.0
```

**Comment by dario-piotrowicz** [comment]
Thanks for tagging me @AndrewKushnir :slightly_smiling_face: 

Yeah I indeed added the check in PR https://github.com/angular/angular/pull/45212

@diegovilar it is not that the code is being more critic, I added that functionality to provide a better experience for developers so that if they see that something is not being animated then they can easily identify what is going wrong.
So regardless on the warnings, if your code worked on prior to Angular 14, it will work exactly the same in 14, as the only difference is the warning being shown (note that it is also a dev only warning, there is no effect in production at all).

Anyways the thing is that in when the `style` function is evaluated it is in the context of animations, there is no distinction between `style` being called on it's own or being part of an animation (and personally I am not sure there should be such distinction), it could be tricky to implement but I could give it a shot if needed :slightly_smiling_face: 

One very simple alternative would be to add an optional options parameter to the `style` function, something like `ignoreNonAnimatableProps` to suppress the warning, or something similar :thinking: 

Anyways personally I think that `style` should only be used as part of an animation implementation and not to set styles to elements, for that trigger callbacks could be used instead (it would be more verbose I know :sweat:), using `style` inside animations to set some non animatable props feels a bit like a misuse of the function to me.

**Comment by diegovilar** [comment]
> @diegovilar it is not that the code is being more critic, I added that functionality to provide a better experience for developers so that if they see that something is not being animated then they can easily identify what is going wrong. So regardless on the warnings, if your code worked fine prior to Angular 14, it will work exactly the same in 14, as the only difference is the warning being shown (note that it is also a dev only warning, there is no effect in production at all).
> 
> Anyways the thing is that in when the `style` function is evaluated it is in the context of animations, there is no distinction between `style` being called on it's own or being part of an animation (and personally I am not sure there should be such distinction), it could be tricky to implement but I could give it a shot if needed 🙂
> 
> One very simple alternative would be to add an optional options parameter to the `style` function, something like `ignoreNonAnimatableProps` to suppress the warning, or something similar 🤔

@dario-piotrowicz I see how tricky it could be to improve the code to detect if the developer is really trying to animate not animatable properties. Probably unnecessary too. 

The new warnings do provide a better experience for the developers, as was your intention, but when warnings keep being issued even when a developer analyzed them and decided that they are not applicable, they end up obfuscating newer warnings and those might slip by, thus worsening the experience. Your idea of allowing the developer to explicit disable the warnings for a `style()` call sounds great. They would be warned, would analyze the code and either fix it or disable the warning if there is nothing to fix, kinda like locally disabling a eslint rule for a line.

**Comment by dario-piotrowicz** [comment]
@diegovilar I implemented the check for actually providing the warning only if the animation is trying to animate them

As you can see here, it does the trick (I copied your animations code but I applied a random html to it since you didn't provide one):
![before](https://user-images.githubusercontent.com/61631103/176916258-c1f0d7e4-1d77-4b0b-a4c3-d7b61141302e.gif)
![after](https://user-images.githubusercontent.com/61631103/176916264-43bb7e38-6ad8-428f-91c8-1ccdec2766e7.gif)

It has the drawback to be run when you play the animation instead of at build time, so you get the warning each time the animation runs instead of just when the component gets generated. This makes sense from the implementation point of view because it makes it easy to check if for an animation a non-animatable property is going to be animated.
Hopefully it's not too bad? I guess we shall see what reviewers say on the PR :) 

Maybe this could be somehow also done on the animation build time but that I think would introduce a lot of complexity (and thus would be much more prone to bugs I'd imagine)

**Comment by diegovilar** [comment]
Fantastic, @dario-piotrowicz! Sorry for the delay, was on the road 🙂

Just read the discussion on your PR and I hope it gets merged soon. Thanks again for the great work 🤗

**Comment by dario-piotrowicz** [comment]
@diegovilar the PR got merged and I just checked, version 14.0.6 includes the fix, please try to see if you can update to that and see if it's all good now :blush:

**Comment by dionatan-g** [comment]
This PR didnt fix all the false positive warnings.

For example here, I have warnings:

```
export const collapse: AnimationTriggerMetadata = trigger('collapseAnimation', [
  state('expanded', style({ height: '*', visibility: 'visible' })),
  state('hidden', style({ height: 0, overflow: 'hidden', borderTopWidth: '0', visibility: 'hidden' })),
  transition('expanded => hidden', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),
  transition('hidden => expanded', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),
]);
```

For me to remove the overflow hidden, I would have to set the style manually with the same delay as the animation.

**Comment by dario-piotrowicz** [comment]
@dionatan-g, I'm going to reply in the issue you've created :+1: 

(adding it here if anyone is following this thread: https://github.com/angular/angular/issues/46928)
