### ISSUE TITLE
Allow customization of HTTP Cache Transfer 

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#50117]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

One of the most interesting features of Angular's hydration is HTTP Cache Transfer which currently caches responses of all GET/HEAD HTTP requests.
The current limitation is that there doesn't seem any built-in way of overriding the [behavior](https://github.com/angular/angular/blob/47c093a7391e550bfb01cff57a6fc712f3342d14/packages/common/http/src/transfer_cache.ts#L35) except using the `withNoHttpTransferCache()` feature when calling `provideClientHydration()` in order to totally disable the feature.

It would be nice if we could override this behavior for the following use cases:
- A. caching other HTTP methods _(e.g. "Safe" use of POST for batching or sending large query strings, maybe even GraphQL which would probably need its own custom transfer)_ and in that case the key computation will also be different.
- B. disabling the cache transfer for some specific requests or origins:
  - B.0. state transfer is handled manually _(e.g. in order to reduce the amount of transferred data as the HTTP response can be way larger than the data really needed)_
  - B.1. private network or internal APIs but publicly hosted SSR
  - B.2. device-specific response (e.g. tracking & debugging... get my IP address... (then it shouldn't be a GET request 😉) )
  - B.3. emit cached response + new request (e.g. in SSG cases, we might want to fetch fresh data in case SSG-ed is not up-to-date).

### Proposed solution

IMO, not all of these use cases should be handled by Angular's hydration's HTTP cache transfer.

Allowing per-request opt-out would be enough to let developers customize the behavior for unconventional requests using `TransferState`.

This could be done globally using a feature:
```ts
provideClientHydration(withHttpTransferCache({filter: req => !req.url.startsWith('https://internal')}));
```

and per request
```ts
http.get('/my-ip-address', {cacheTransfer: false}); // we'll have to figure out a better naming for this
```

### Alternatives considered

Disable the feature using `withNoHttpTransferCache()` and implement our own transfer logic like before using `TransferState`.

Right now, we can easily mimic the current behavior which is here: https://github.com/angular/angular/blob/47c093a7391e550bfb01cff57a6fc712f3342d14/packages/common/http/src/transfer_cache.ts#L35-L90

The modularity of the current design (thanks to the `TransferState` primitive) and the workaround described here is sufficient enough to reduce the priority of this issue drastically...

👉 ... making it an interesting opportunity for a community initiative 😉😉 👈

**Comment by jsaguet** [comment]
We're using different domains on server and browser to make our API calls. The consequence is that the transfer cache never reuse our API calls

With the previous implementation (`TransferHttpCacheModule`) we had the following logic to handle this:
- From our code, we call endpoints with /key/endpoint.
- The old transfer cache interceptor uses the /key/endpoint url as the key for our request
- We then use another interceptor to translate /key to the proper domain. 
The actual request made is therefore private-domain.com/endpoint on server and public-domain.com/endpoint on browser

With the new implementation, this is not possible anymore because the transfer cache interceptor function is provided with the `HTTP_ROOT_INTECEPTOR_FNS` which is always executed last in the interceptor chain.
So in our case, the cache key is different on server and browser when the transfer cache interceptor executes so there is never a match.

The issue might be a bit different than allowing customization of the transfer cache.

I think this is caused by the new http client design:
- why are we using 2 different injection tokens `HTTP_INTERCEPTOR_FNS` and  `HTTP_ROOT_INTERCEPTOR_FNS`?
- why isn't HTTP_INTERCEPTOR_FNS exposed publicly? Why can be rephrased as "Why do we have to use `provideHttpClient(withInterceptors(...))` to provide interceptors instead of providing HTTP_INTERCEPTOR_FNS directly?" 
This causes encapsulation problems where we need to use provideHttpClient multiple times if we want to provide interceptors from a library.

I'm willing to open a separate issue if necessary.

**Comment by docaohuynh** [comment]
@jsaguet I got the same problem when using different domains on server and browser to make our API calls. Hydration is not working
Have you found solution to deal with that?

**Comment by jsaguet** [comment]
Unfortunately, I had to disable the new http transfer cache with `provideClientHydration(withNoHttpTransferCache())` and continued using `TransferHttpCacheModule` that is based on `HTTP_INTERCEPTOR` token.

**Comment by michielkikkert** [comment]
I'd love to have granularity here. I'd propose 2 mechanisms on the HttpClient itself  as additional configuration option. 
Similar to the other requests here, my production URL is different than the URL I use to generate the site, as my data is only available locally. Idea is to be able to control the caching key at the calling station instead of a global option. The challenge for me is that SSR needs an absolute path - so local generation has a different domain than the production site. 

// Proposal:

const path = myPath; // could be '/product/123'
http.get(path, {transferStateKey: makeStateKey(path)}); 

That would allow to have relative paths as matching state keys instead of absolute paths (which are used now).

As bonus: an additional key to ignore HTTP transfer state on http level. Something like:
http.get(path, {skipTransferState: true})

Thanks for considering! The hydration and bonus transfer states are excellent (performance) features. With some additional configuration options like above - usability of the feature would become even better I think!

**Comment by zip-fa** [comment]
Hi. I am expereincing lack of customization of `makeCacheKey` function with my new SSR-first setup (thanks to application builder!).
I am going to use angular's SSRed app inside Docker container, so it can easily be scaled inside k8s. My container has direct access to backend HTTP REST API without any proxying.
My angular app send requests to `/api/something`. This route is being proxied on nginx's side:

```
upstream unit-backend {
	server app:9000;
}

upstream frontend-en {
	server frontend-en:4000;
}

server {
	listen 80;
	listen [::]:80;
	server_name test-domain.com;

        location ~ ^/en {
            proxy_pass http://frontend-en;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_redirect off;
        
            rewrite /en/(.*) /$1 break;
        }
        
	location ^~ /api {
              proxy_pass http://unit-backend;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
}
```

Because express server doesn't know about /api routes, it will give 404 errors everytime server tries to send some requests to my API. This can be easily solved with request interceptor & minor modifications of `server.ts`:

express.tokens.ts

```
export const SSR_API_HOST = new InjectionToken<string>('SSR_API_HOST');
```

server.ts:

```
commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: req.originalUrl,
        publicPath: browserDistFolder,
        providers: [
          { provide: APP_BASE_HREF, useValue: req.baseUrl },
          { provide: REQUEST, useValue: req },
          { provide: RESPONSE, useValue: res },
          { provide: SSR_API_HOST, useValue: ssrApiHost }
        ]
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
```

interceptor.ts:

```
private readonly ssrApiHost = inject(SSR_API_HOST, { optional: true });

if(this.ssrApiHost) {
  request = request.clone({
    url: `${ this.ssrApiHost }${ request.url }`
  });
}
```

Because of how `makeStateCache` creates cache key, it will never be consistent with server's response. Please allow us to modify it's behaviour, so we can intercept it's call and make custom cache keys.

My proposed solution is to add option to `provideClientHydration()`:

```
providers: [
  provideClientHydration({
    transferStateCacheMaker: (request: HttpRequest<any>): string => request.url
  })
]
```

Thanks!

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/52029

**Comment by jsaguet** [comment]
I believe the use case of different domains/path between server and browser API calls is not resolved yet.
More generally, we're still lacking a way to customize the cache key somehow.
