### ISSUE TITLE
Massive overhead with flushAnimations even with NoopAnimationsModule on Universal

### ISSUE THREAD

**Issue by davidstellini** [angular/angular#51289]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

When using the NoopAnimationsModule on Universal, my flame chart looks like this:

<img width="1632" alt="image" src="https://github.com/angular/angular/assets/4324419/7886e70b-1fa8-432c-b9a4-336e7302ac58">

Note the massive overhead on the flushAnimations.

I wrote a monkey patch just to test:

```
let patched = true;
if (!patched) {
	const originalFlush = ɵAnimationEngine.prototype.flush;
	ɵAnimationEngine.prototype.flush = function(...args: any[]): any {};

	patched = true;
}
```

The page still renders on Universal - to be honest I didn't see any differences with JS disabled - but this time the burndown chart looks like this:

<img width="1727" alt="image" src="https://github.com/angular/angular/assets/4324419/65dbd732-f0cf-4a9a-a061-6c3bfd97ca78">

The render completes in about half the time, and most of that time is idle time (waiting for API / async operations to complete). I would say it's possibly around a 10x difference in our case.

Is this normal behaviour, or perhaps something that might be wrong with the project? 

### Please provide the exception or error you saw

```true
No error
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.9
Node: 18.16.1
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      13.3.11
@angular/flex-layout            14.0.0-beta.41
@angular/google-maps            13.2.6
@nguniversal/builders           15.2.0
@nguniversal/express-engine     14.2.3
@schematics/angular             15.2.9
rxjs                            7.8.0
typescript                      4.8.4
webpack                         5.74.0
```

**Comment by JoostK** [comment]
The error that is being thrown in that slow path is coming from domino, which got completely rewritten in https://github.com/angular/domino/pull/10 to an extent where I don't think the error occurs anymore, which should significantly reduce the overhead (exceptions are expensive, especially creating a stack trace as seen in the profiler trace).

Angular 16 switched to this version of domino.

**Comment by davidstellini** [comment]
Will test it out on Angular 16 and let you know,  thanks for the info!

But just to clarify, I don't understand why flushAnimations has to run at all on SSR or anything animations related for that matter, when I added in a NoopAnimationsModule?

**Comment by JoostK** [comment]
There's indeed swallowed errors, you can tell from all the yellow blocks in the first screenshot.

It's a good point that animations don't necessarily need to be flushed in the regular way, not when using NoopAnimationsModule nor especially on the server.

**Comment by JeanMeche** [comment]
One common misconception is that the `NoopAnimationsModule` doesn't render the animation. But it actually does, it just doesn't play them. 

For example: 

```
    trigger('openClose', [
      // ...
      state('open', style({
        height: '200px',
        opacity: 1,
        backgroundColor: 'yellow'
      })),
      state('closed', style({
        height: '100px',
        opacity: 0.8,
        backgroundColor: 'blue'
      })),
      transition('open => closed', [
        animate('1s')
      ]),
      transition('closed => open', [
        animate('0.5s')
      ]),
    ]),
  ],
```

The default renderer wouldn't handle the styles of the states, the AnimationRenderer does.

**Comment by Davste93** [comment]
Thanks @JeanMeche. Is there a way to disable angular animations entirely on SSR then, similar to that patch, for projects where SSR rendering time is important?

Especially if we are using stuff like material where we don't have control over triggers, etc.

**Comment by JeanMeche** [comment]
Currently there is no way to disable it but we could discuss the possibility of adding that feature.

**Comment by pkozlowski-opensource** [comment]
@davidstellini did you manage to test / profile with Angular v16? As pointed out by @JoostK, the slowdown was coming mostly from exceptions and this should be fixed in v16. 

We need to understand the real-life impact of animations on your app to decide if any additional optiomizations need to be done during SSR.

**Comment by davidstellini** [comment]
> @davidstellini did you manage to test / profile with Angular v16? As pointed out by @JoostK, the slowdown was coming mostly from exceptions and this should be fixed in v16.
> 
> We need to understand the real-life impact of animations on your app to decide if any additional optiomizations need to be done during SSR.

I did but iirc even though it was much better and the issue was fixed, it was still performing worse than the hack I mentioned earlier for the project I tested it on. But I don't have the numbers anymore.

I guess running animations on the SSR version still had a render time cost.

**Comment by CarlosTorrecillas** [comment]
To add my 2 cents here I have to say that when checking some other performance problems in SSR I found that animation code gets run as I was said before. The transitions are not though which is a good thing.

But what I still don’t get is why do they have to run in the first place. What I mean is that being on the server, to me, would mean that we should disable them at all since they don’t make add any value, do they?

In my view there should be another sort of module or provider to completely disable them and do a truly noop. I also misunderstood the concept of NoopAnimationModule. Maybe that’s a bit confusing since I guess most of the users don’t want any overhead introduced by any animation server side. At least that’s my view  here. Perhaps a new DisableAnimationsModule would be a good one?

**Comment by JoostK** [comment]
Animation states need to be evaluated though, as otherwise elements wouldn't have the correct styles applied that correspond with their respective animation state. This is relevant even for SSR content, as otherwise the served content would be missing styles that are supposed to be present on an element.

**Comment by Davste93** [comment]
> Animation states need to be evaluated though, as otherwise elements wouldn't have the correct styles applied that correspond with their respective animation state. This is relevant even for SSR content, as otherwise the served content would be missing styles that are supposed to be present on an element.

Perhaps that's up to the consumer to decide, and at least the option should be there. I believe different projects have different priorities and in cases when rendering time is more important than animations or a missing style - this should be an option. Especially since we can't conditionally remove animations if they're triggered within libraries.  So there's currently no way to do this other than monkey patch the library.

In fact, I'm going to post the updated version - this one cuts down the rendering time even more than the one posted earlier, by effectively mocking internals:

```
export { AppServerModule } from './app/app.server.module';

ɵAnimationEngine.prototype.registerTrigger = function(componentId: string, namespaceId: string, hostElement: any, name: string, metadata: any): void {};

ɵAnimationEngine.prototype.register = function(namespaceId: string, hostElement: any): void {};

ɵAnimationEngine.prototype.destroy = function(namespaceId: string, context: any): void {};

ɵAnimationEngine.prototype.onInsert = function(namespaceId: string, element: any, parent: any, insertBefore: boolean): void {};

ɵAnimationEngine.prototype.onRemove = function(namespaceId: string, element: any, context: any, isHostElement?: boolean): void {};

ɵAnimationEngine.prototype.disableAnimations = function(element: any, disable: boolean): void {};

ɵAnimationEngine.prototype.process = function(namespaceId: string, element: any, property: string, value: any): void {};

ɵAnimationEngine.prototype.listen = function(namespaceId: string, element: any, eventName: string, eventPhase: string, callback: (event: any) => any): () => any {
	return () => {};  // Return a noop function for cleanup
};

ɵAnimationEngine.prototype.flush = function(microtaskId?: number): void {};

Object.defineProperty(ɵAnimationEngine.prototype, 'players', {
	get: function() {
		return [];
	}
});

ɵAnimationEngine.prototype.whenRenderingDone = function(): Promise<any> {
	return Promise.resolve();
};
```
