### ISSUE TITLE
Official tutorial issue - Image missing in examples

### ISSUE THREAD

**Issue by Klerith** [angular/angular#52794]
### Describe the problem that you experienced

The official tutorial shows that we can copy/paste into the ```db.json``` file...

But you are copy/pasting the this.baseUrl which doesn't work when you get the code from the json-server.

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/first-app/http

### Add a screenshot if that helps illustrate the problem

<img width="900" alt="Screenshot 2023-11-10 at 1 28 25 PM" src="https://github.com/angular/angular/assets/3438503/7562b576-45ea-4b8b-934e-191c5f97f4ef">

### Provide any additional information here in as much as detail as you can

```true
We can just copy paste the full URL like this:

db.json


{
  "locations": [
    {
      "id": 0,
      "name": "Acme Fresh Start Housing",
      "city": "Chicago",
      "state": "IL",
      "photo": "https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg",
      "availableUnits": 4,
      "wifi": true,
      "laundry": true
    },
    {
      "id": 1,
      "name": "A113 Transitional Housing",
      "city": "Santa Monica",
      "state": "CA",
      "photo": "https://angular.dev/assets/tutorials/common/brandon-griggs-wR11KBaB86U-unsplash.jpg",
      "availableUnits": 0,
      "wifi": false,
      "laundry": true
    },
    {
      "id": 2,
      "name": "Warm Beds Housing Support",
      "city": "Juneau",
      "state": "AK",
      "photo": "https://angular.dev/assets/tutorials/common/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg",
      "availableUnits": 1,
      "wifi": false,
      "laundry": false
    },
    {
      "id": 3,
      "name": "Homesteady Housing",
      "city": "Chicago",
      "state": "IL",
      "photo": "https://angular.dev/assets/tutorials/common/ian-macdonald-W8z6aiwfi1E-unsplash.jpg",
      "availableUnits": 1,
      "wifi": true,
      "laundry": false
    },
    {
      "id": 4,
      "name": "Happy Homes Group",
      "city": "Gary",
      "state": "IN",
      "photo": "https://angular.dev/assets/tutorials/common/krzysztof-hepner-978RAXoXnH4-unsplash.jpg",
      "availableUnits": 1,
      "wifi": true,
      "laundry": false
    },
    {
      "id": 5,
      "name": "Hopeful Apartment Group",
      "city": "Oakland",
      "state": "CA",
      "photo": "https://angular.dev/assets/tutorials/common/r-architecture-JvQ0Q5IkeMM-unsplash.jpg",
      "availableUnits": 2,
      "wifi": true,
      "laundry": true
    },
    {
      "id": 6,
      "name": "Seriously Safe Towns",
      "city": "Oakland",
      "state": "CA",
      "photo": "https://angular.dev/assets/tutorials/common/phil-hearing-IYfp2Ixe9nM-unsplash.jpg",
      "availableUnits": 5,
      "wifi": true,
      "laundry": true
    },
    {
      "id": 7,
      "name": "Hopeful Housing Solutions",
      "city": "Oakland",
      "state": "CA",
      "photo": "https://angular.dev/assets/tutorials/common/r-architecture-GGupkreKwxA-unsplash.jpg",
      "availableUnits": 2,
      "wifi": true,
      "laundry": true
    },
    {
      "id": 8,
      "name": "Seriously Safe Towns",
      "city": "Oakland",
      "state": "CA",
      "photo": "https://angular.dev/assets/tutorials/common/saru-robert-9rP3mxf8qWI-unsplash.jpg",
      "availableUnits": 10,
      "wifi": false,
      "laundry": false
    },
    {
      "id": 9,
      "name": "Capital Safe Towns",
      "city": "Portland",
      "state": "OR",
      "photo": "https://angular.dev/assets/tutorials/common/webaliser-_TPTXZd9mOo-unsplash.jpg",
      "availableUnits": 6,
      "wifi": true,
      "laundry": true
    }
  ]
}


```
```

**Comment by millerraycell** [comment]
Question: On the tutorial the mention for the url is the "/assets" folder, which leads me to think the dev should have the pic locally, is even mentioned that 

![image](https://github.com/angular/angular/assets/39956685/5daa63f5-0c11-4f1f-8f2d-6696e2a8e7e7)

So i'm quite unsure which should be the correct expected url, just the "/assets" and provide a link for the download, or the full url as is mentioned on the description

**Comment by Klerith** [comment]
Yea, but I'm talking about the last step, where you use "json-server" to deploy your data... this is not Angular, but you use it to serve the "placeholder" data in the db.json file, in order to create a fake restful server.

However, when you asked to copy and paste, you paste code from angular to the db.json file witch will cause in errors when you try to show the image url.

**Comment by jnizet** [comment]
The posted error probably comes from the fact that you used regular quotes:

```
'${this.url}'
```

instead of backticks:

```
`${this.url}`
```

The interpolation only works when using template strings, delimited by backticks.

**Comment by JeevanMahesha** [comment]
@twerske / @MarkTechson The fix I have implemented will still result in a 404 error. The proper solution is to provide a valid image URL in the 'photo' property. Please advise on where to obtain the correct image URL.

**Comment by michermd** [comment]
I had the same issue and waiting for a response. However you ca just hardcode the URL in the db.json to finish the last step of the tutorial.
```{
      "id": 0,
      "name": "Acme Fresh Start Housing",
      "city": "Chicago",
      "state": "IL",
      "photo": "https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg",
      "availableUnits": 4,
      "wifi": true,
      "laundry": true
    },```

**Comment by monacodelisa** [comment]
"HTTP in Angular" is video Part 8 of the "Learning Angular" playlist on YT. 
I went back to Part 4 to see how the images are handled and users (sorry I mean people following the tutorial) 
are not downloading the images, so they do not have them locally. 

Since the images are available at - https://angular.dev/assets/tutorials/common/....
it might be nice to add the full path in the db.json file that is to be copied, 
and also to - https://goo.gle/homes-app-listings

This way people following the tutorial will have one less thing to think about :)

**Comment by monacodelisa** [comment]
For Angular.dev (browser)
db.json file 
- even if "photo": "${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg", 
is changed to "photo": `${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,
still won't work since this is a .json file and ${this.baseUrl} is not defined there.

If the file is being copied directly we can assume (maybe) that the zip files have not been downloaded (images not available locally), therefore it's probably best to use the full image path - "https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg", this full path can also be added to the links on github that people watching the tutorials on YT use to build the app - https://goo.gle/homes-app-listings

For local setup (zip file)
for local set-up images would be downloaded as a zip file with the code,
so maybe only there would be nice to include a db.json file in the root dir,
with a relative path following the provided file structure.

**Comment by JeanMeche** [comment]
To give some insight on the issue. Currently the build script (`yarn docs:build`) does not produce an artifact that contains those images.

**Comment by matthewjheaney** [comment]
If you fix the baseUrl:

  readonly baseUrl = 'https://angular.io/assets/images/tutorials/faa';

Then the full URL of the photo is:

https://angular.io/assets/images/tutorials/faa/example-house.jpg

and this is indeed a valid URL for the photo.

However, when you run `ng serve` the application runs but it gets CORS errors when attempting to render the image.

What is the intended fix for the CORS issues?

The URL fix was made here:

https://github.com/angular/angular/pull/51014

The repo changes are here:

https://github.com/thomasturrell/angular/commit/7e11c709fbcb4e5e873e2786e4c45d9ef1db15d2

But this doesn't solve the CORS problem.  What was intended here for tutorial users?

**Comment by matthewjheaney** [comment]
Note that the tutorial page here:

https://angular.dev/tutorials/first-app/08-ngFor

still has the incorrect URL:

`readonly baseUrl = 'https://angular.dev/assets/tutorials/common'`

While the corresponding page here:

https://angular.io/tutorial/first-app/first-app-lesson-08

has the correct URL:

`readonly baseUrl = 'https://angular.io/assets/images/tutorials/faa';`

**Comment by furtivite** [comment]
I have a similar problem. I have replaced the standard URL of the image from

```
readonly baseUrl = 'https://angular.dev/assets/tutorials/common'
```

to

```
readonly baseUrl = 'https://angular.io/assets/images/tutorials/faa';
```

Now I have a picture that opens if I click on a link in an already assembled site. But at the same time, the picture is not displayed in localhost

![CORS](https://github.com/angular/angular/assets/50330458/a7b58c9b-58ed-4e03-9dc6-15b49aa4abe3)

As far as I understand, the problem is in CORS. It would be great if the instructions immediately had information on how to avoid the problem.

**Comment by bencodezen** [comment]
For some additional context:

"Images are either missing from the deployment(https://angular.dev/assets/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg) or the path is wrong."

- Credit to Leonardo Ortiz for the context

**Comment by komura-c** [comment]
It appears to be fixed now. The image was hosted with a`Cross-Origin-Resource-Policy` header at the following URL.
```ts
...
  readonly baseUrl = "https://angular.dev/assets/images/tutorials/common";

  housingLocationList = [
    {
      id: 0,
      name: "Acme Fresh Start Housing",
      city: "Chicago",
      state: "IL",
      photo: `${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,
      availableUnits: 4,
      wifi: true,
      laundry: true,
    },
...
```
<img width="531" alt="スクリーンショット 2024-07-04 0 43 09" src="https://github.com/angular/angular/assets/37304826/1a2b3b39-fbf6-495e-a987-733d0b0641c6">
