### ISSUE TITLE
Add more info to Angular Hydration warning message when app not stable within 10 seconds

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/angular#52912]
### Description

Currently whenever you try to use Angular hydration and your client side app is not stable within 10 seconds, you get a warning that looks like this:

```
NG0506: Angular hydration expected the ApplicationRef.isStable() to emit `true`, but it didn't happen within 10000ms. Angular hydration logic depends on the application becoming stable as a signal to complete hydration process. Find more at https://angular.io/errors/NG0506
```

The problem is that it can be extremely hard to figure out at times what exactly is keeping your application unstable.

### Proposed solution

The NgZone keeps track of microtasks and macrotasks so perhaps we can get something from what is being tracked in the NgZone to report to the user what exactly is keeping the application unstable.

### Alternatives considered

Currently to debug this I either just keep commenting out stuff until the warning goes away to narrow in on what may be causing the issue or use a global patch like this one from @yharaskrik:

```
const o = window.setTimeout;

(window as any)['setTimeout'] = function (handler: TimerHandler, timeout?: number, ...args: any[]) {
    console.trace();
    return o(handler, timeout, ...args);
};

const i = window.setInterval;

(window as any)['setInterval'] = function (handler: TimerHandler, timeout?: number, ...args: any[]) {
    console.trace();
    return i(handler, timeout, ...args);
};
```

**Comment by zip-fa** [comment]
There is much easier way to find what’s preventing your app from being stable. I encountered same issue and found old trick to catch every running macrotask. Original script was not working with never versions of angular, so i modified it (and lost original source to be honest).

Put this to your app.component.ts:

```
const ngZone = ɵglobal.Zone;
const TaskTrackingZone = ngZone.current._parent?._properties?.TaskTrackingZone;

if(!TaskTrackingZone) {
  return;
}

inject(ApplicationRef).isStable.subscribe(stable => {
  this.printNgZone(TaskTrackingZone, 0);
  console.log('Is stable:', stable);
});

this.printNgZone(TaskTrackingZone, 2000);

private printNgZone(zone: any, delay: number): void {
  this.ngZone.runOutsideAngular(() => {
    setTimeout(() => {
      // Print to the console all pending tasks
      // (micro tasks, macro tasks and event listeners):
      console.debug('👀 Pending tasks in NgZone: 👀');
      console.debug({
        microTasks: zone.getTasksFor('microTask'),
        macroTasks: zone.getTasksFor('macroTask'),
        eventTasks: zone.getTasksFor('eventTask')
      });

      // Advice how to find the origin of Zone tasks:
      console.debug(
        👀 For every pending Zone Task listed above investigate the stacktrace in the property 'creationLocation' 👆
      );
    }, delay);
  });
}
```

dont forget to import `zone.js/dist/task-tracking` to your main.ts, and dont forget to enable debug output in your console. Happy hacking!

**Comment by zip-fa** [comment]
Don’t forget that Angular wants to get rid of zone.js, so you will not need this hack soon.

**Comment by jeffwhelpley** [comment]
As a follow up, I did eventually figure out what was causing the app to remain unstable, but to do it I had to literally just uncomment code and re-test until I narrowed in on the exact source. For me it ended up as this piece of code:

```
            this.router.events.subscribe({
                next: (val) => {
                    if (val instanceof ActivationEnd) {
                        this.activatedRoute$.next(val.snapshot);
                        this.activatedRoute = val.snapshot;
                    }
                },
                error: (err: any) => {
                    this.log.error(err);
                },
                complete: () => {},
            });
```

Which was no longer an issue once I wrapped this inside a `this.zone.runOutsideAngular()`. But my specific root cause is not the point of this GitHub issue. This GitHub issue is to try and add something that will allow developers to debug this issue much easier than the painful hours I spent this morning commenting and uncommenting code.

As long as zones are still a thing, I feel like people will continue to run into this and they likely need a little more guidance to figure out the offending code.

**Comment by yharaskrik** [comment]
> As a follow up, I did eventually figure out what was causing the app to remain unstable, but to do it I had to literally just uncomment code and re-test until I narrowed in on the exact source. For me it ended up as this piece of code:
> 
> ```
>             this.router.events.subscribe({
>                 next: (val) => {
>                     if (val instanceof ActivationEnd) {
>                         this.activatedRoute$.next(val.snapshot);
>                         this.activatedRoute = val.snapshot;
>                     }
>                 },
>                 error: (err: any) => {
>                     this.log.error(err);
>                 },
>                 complete: () => {},
>             });
> ```
> 
> Which was no longer an issue once I wrapped this inside a `this.zone.runOutsideAngular()`. But my specific root cause is not the point of this GitHub issue. This GitHub issue is to try and add something that will allow developers to debug this issue much easier than the painful hours I spent this morning commenting and uncommenting code.
> 
> As long as zones are still a thing, I feel like people will continue to run into this and they likely need a little more guidance to figure out the offending code.

Nice work Jeff, I also have been taking a similar approach to figuring out what's going on. 

I generated an entirely new app and have been slowly adding pieces to it to see what is or is not causing issues (giving me a good reason to audit everything we are including in root anyway but still lots of work to track down hydration issues haha)

**Comment by zuhairak** [comment]
Thanks @jeffwhelpley , I also commented component by component and found out that mdb-carousel was causing the issue in my case and replaced it with ngb-carousel, there was also one component which had a custom function call which I had to run outside angular.

It was difficult to figure out the long tasks from the patch code given above in app.component because most of them where showing the calls from library code

**Comment by pdela** [comment]
> As a follow up, I did eventually figure out a few pieces of code that were causing the app to remain unstable, but to do it I had to literally just uncomment code and re-test until I narrowed in on the exact source. Here is one:
> 
> ```
>             this.router.events.subscribe({
>                 next: (val) => {
>                     if (val instanceof ActivationEnd) {
>                         this.activatedRoute$.next(val.snapshot);
>                         this.activatedRoute = val.snapshot;
>                     }
>                 },
>                 error: (err: any) => {
>                     this.log.error(err);
>                 },
>                 complete: () => {},
>             });
> ```
> 
> and here is another:
> 
> ```
>             const replayConfig = { maskAllText: false, maskAllInputs: false, blockAllMedia: false };
>             const integrations = [new SentryFullStory('gethuman', { client: FullStory }), new Replay(replayConfig)];
>             Sentry.init({ dsn: config.sentryUrl, replaysSessionSampleRate: 0.1, replaysOnErrorSampleRate: 1.0, integrations });
> ```
> 
> This one was really surprising to me because it must be something within the Sentry library that is doing some continuous async operations.
> 
> In all cases, the solution was to wrap the offending code inside a `this.zone.runOutsideAngular()`.
> 
> But my specific problems are not the point of this GitHub issue. This GitHub issue is to try and add something that will allow developers to debug this issue much easier than the painful hours I spent this morning commenting and uncommenting code.
> 
> As long as zones are still a thing, I feel like people will continue to run into this and they likely need a little more guidance to figure out the offending code.

I don't get why the router subscription causes the problem. Can you explain?

Anyway I fully support this request. I'm going mad with this problem.
Using task-tracking from node, I only get to a set timeout within firestore library. I suspect this is something internal to firestore as I made sure all my calls to firestore are resolved or completed (observables).

Of course I can't get rid of firestore nor I can delay the call to firestore after hydration happened since this will make the whole SSR useless if rendering happens without the info from the dB.

By the way Angular becomes stable in the server otherwise nothing will be sent to the client. It doesn't just In the client.

Really need some clue from angular to narrow down the problem.

**Comment by JomaKar** [comment]
> There is much easier way to find what’s preventing your app from being stable. I encountered same issue and found old trick to catch every running macrotask. Original script was not working with never versions of angular, so i modified it (and lost original source to be honest).
> 
> Put this to your app.component.ts:
> 
> ```
> import { ɵglobal, NgZone } from ‘@angular/core’;
> 
> ….
> 
> private ngZone = inject(NgZone);
> 
> constructor() {
> const ngZone = ɵglobal.Zone;
> const TaskTrackingZone = ngZone.current._parent?._properties?.TaskTrackingZone;
> 
> if(!TaskTrackingZone) {
>   return;
> }
> 
> inject(ApplicationRef).isStable.subscribe(stable => {
>   this.printNgZone(TaskTrackingZone, 0);
>   console.log('Is stable:', stable);
> });
> 
> this.printNgZone(TaskTrackingZone, 2000);
> }
> 
> private printNgZone(zone: any, delay: number): void {
>   this.ngZone.runOutsideAngular(() => {
>     setTimeout(() => {
>       // Print to the console all pending tasks
>       // (micro tasks, macro tasks and event listeners):
>       console.debug('👀 Pending tasks in NgZone: 👀');
>       console.debug({
>         microTasks: zone.getTasksFor('microTask'),
>         macroTasks: zone.getTasksFor('macroTask'),
>         eventTasks: zone.getTasksFor('eventTask')
>       });
> 
>       // Advice how to find the origin of Zone tasks:
>       console.debug(
>         👀 For every pending Zone Task listed above investigate the stacktrace in the property 'creationLocation' 👆
>       );
>     }, delay);
>   });
> }
> ```
> 
> dont forget to import `zone.js/dist/task-tracking` to your main.ts, and dont forget to enable debug output in your console. Happy hacking!

task-tracking is no longer exported by zone.js and that path is not accessible

**Comment by hheexx** [comment]
@jeffwhelpley I would recommend that in addition to better error massages, Angular should make 10 seconds value customizable and maybe make 5 sec the default.

**Comment by alfmosmq** [comment]
I am having the same issue, and I would like to know what exactly is the issue with router.events. 
It seems unlikely that we have to put router.events in RunOutsideAngular

**Comment by HarelM** [comment]
I'm facing a similar issue right now. I found an rxjs interval I was running when the app starts that caused this. But even after the warning is removed (10 seconds) I still see that the hydration is completing about 7-8 seconds after the entire screen is loaded. I'm getting the following console message:
`Angular hydrated 8 component(s) and 78 node(s), 0 component(s) were skipped. Learn more at https://angular.dev/guide/hydration.`
It would be best to also highlight in the message above which tasks took relatively long to finish (>500ms I guess) or allow some configuration to allow it. The link to the hydration page and the documentation there is not very useful for debugging this issue, I even installed the angular dev tool which show that hydration is taking some time, but not why it takes so long...
Adding more information to this message will allow improving the performance of the app without reaching the 10 seconds warning.
Never the less, improving the 10s warning is essential as well.
