### ISSUE TITLE
Unable to deserialize cloned data during `Components in Angular` tutorial

### ISSUE THREAD

**Issue by LukeSchlangen** [angular/angular#56134]
### Describe the problem that you experienced

`Components in Angular` tutorial is broken for me:
https://angular.dev/tutorials/learn-angular/1-components-in-angular

Other pages of the tutorial seem to be working though?

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/1-components-in-angular

### Add a screenshot if that helps illustrate the problem

<img width="960" alt="Screenshot 2024-05-28 at 1 57 54 PM" src="https://github.com/angular/angular/assets/5384581/76b6ecdd-ee49-4d69-9303-247e3b78397e">

### If this problem caused an exception or error, please paste it here

```true
Application bundle generation failed. [0.209 seconds]

✘ [ERROR] Unable to deserialize cloned data. [plugin angular-sass]

  This error came from the "onLoad" callback registered here:

    node_modules/@angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.js:145:22:
      145 │                 build.onLoad({ filter: language.componentFilter, ...
          ╵                       ~~~~~~

    at setup (/home/httpsangulardev-dlxb/node_modules/@angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.js:145:23)
    at handlePlugins (/home/httpsangulardev-dlxb/node_modules/esbuild/lib/main.js:1138:21)
    at buildOrContextImpl (/home/httpsangulardev-dlxb/node_modules/esbuild/lib/main.js:863:5)
    at Object.buildOrContext (/home/httpsangulardev-dlxb/node_modules/esbuild/lib/main.js:689:5)
    at eval (/home/httpsangulardev-dlxb/node_modules/esbuild/lib/main.js:1828:68)
    at Object.context (/home/httpsangulardev-dlxb/node_modules/esbuild/lib/main.js:1828:27)
    at context (/home/httpsangulardev-dlxb/node_modules/esbuild/lib/main.js:1670:58)
    at #performBundle (/home/httpsangulardev-dlxb/node_modules/@angular/build/src/tools/esbuild/bundler-context.js:158:68)
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

_No response_

**Comment by JeanMeche** [comment]
Hi, luckily this has already been fixed by #27723 and we're wainting for the release probably tomorrow to fix this. 
Thank you for your understanding.

**Comment by JuniorGunner** [comment]
Same problem today.
![image](https://github.com/angular/angular/assets/12654382/ebef15ac-0508-41e9-aa47-9914f4fb7503)

**Comment by mw44118** [comment]
Anybody else remember that episode of The Simpsons when they go to Itchy and Scratchy Land and the helicopter pilot says "where nothing can possibLIE go wrong.  PossibLEE go wrong."

I'm not saying we should throw managers into volcanoes

**Comment by Izzyth17** [comment]
This still happening for this tutorial. I'm not super mad, it's just demonstrating css and html stuff, but still.
<img width="1161" alt="Screenshot 2024-06-09 141128" src="https://github.com/angular/angular/assets/112516481/a9531b8f-0240-4841-a33e-e30d7629b113">

**Comment by bacloud23** [comment]
we need to the tutorial back 😡😡😡😡😡

**Comment by andreapaiola** [comment]
Same error here.

**Comment by JeanMeche** [comment]
I'll reopen this as it's confirmed that the issue wasn't fixed. We're looking into this.

**Comment by JeanMeche** [comment]
I don't reproduce it anymore. Can someone confirm ?

**Comment by bacloud23** [comment]
I confirm that now it works ! Thank you @JeanMeche

**Comment by bacloud23** [comment]
Not working @JeanMeche

**Comment by LukeSchlangen** [comment]
@bacloud23 - This is still working for me. Can you provide more details about what you're seeing or how to reproduce it?

If others are still seeing an error, feel free to share the details.

**Comment by bacloud23** [comment]
Hi @LukeSchlangen 
I am not behind a firewall or anything as long as I know.
We use uBlock though, so I deactivated it; Here is a capture of the page (sorry it is in French but you can guess ^^)

![image](https://github.com/angular/angular/assets/130276583/03a9d5a4-7b8c-4e5d-b814-680c5bcd47b4)

This is the error of the two ressources that seem to error:
![image](https://github.com/angular/angular/assets/130276583/87bacf93-ab1e-4492-9c3d-97e733e94806)

> NET::ERR_CERT_AUTHORITY_INVALID

**Comment by bacloud23** [comment]
the link:
https://httpsangulardev-dlxb--4200--9e2d28a3.local-corp.webcontainer-api.io/
So I went further and discovered that maybe my company etc decided to block it
https://globalurl.fortinet.net/rate/submit.php?id=44584D6A35160941232E602B396E216D&cat=00&loc=https://httpsangulardev%2ddlxb%2d%2d4200%2d%2d9e2d28a3%2elocal%2dcorp%2ewebcontainer%2dapi%2eio%2f&ver=8 

![image](https://github.com/angular/angular/assets/130276583/af91b320-3fff-4743-a813-b41019ab7d0a)
so nothing to do I guess.

**Comment by mw44118** [comment]
It works for me now and it used to not work for me

**Comment by bacloud23** [comment]
yes I think it is a network issue on my side. As I changed the network it does work @mw44118 
Sorry for the non issue.
