### ISSUE TITLE
npm install complains about peer deps

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#5746]
I get the following warnings when I install the latest alpha version:
```shell
npm WARN EPEERINVALID angular2@2.0.0-alpha.50 requires a peer of es6-promise@^3.0.2 but none was installed.
npm WARN EPEERINVALID angular2@2.0.0-alpha.50 requires a peer of es6-shim@^0.33.3 but none was installed.
npm WARN EPEERINVALID angular2@2.0.0-alpha.50 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN EPEERINVALID angular2@2.0.0-alpha.50 requires a peer of rxjs@5.0.0-alpha.14 but none was installed.
npm WARN EPEERINVALID angular2@2.0.0-alpha.50 requires a peer of zone.js@0.5.8 but none was installed.
```

**Comment by meenie** [comment]
If you are using npm3, then you have to install all of those separately. 
`npm install es6-promise@^3.0.2 es6-shim@^0.33.3 reflect-metadata@0.1.2 rxjs@5.0.0-alpha.14 zone.js@0.5.8`.  This is temporary until things can be fixed properly.

**Comment by rolandjitsu** [comment]
I am using the latest version of node and npm. That is how I fixed it, but just wanted to report it if it hasn't been reported yet.

**Comment by pkozlowski-opensource** [comment]
It is a breaking change, see: https://github.com/angular/angular/commit/80b025ae53760310e6776dd7897eff4bda5e4a26

It didn't make it to the changelog, unfortunately...

**Comment by rolandjitsu** [comment]
@pkozlowski-opensource that is great that those are required as separate deps, too bad it did not make it to the changelog.

Off topic, are there any other things that did not make it to the changelog that I should be aware of?

**Comment by pkozlowski-opensource** [comment]
> that is great that those are required as separate deps, too bad it did not make it to the changelog.

Changelog was updated via 4e16feaf722e8b1b3b14eff83b3fe5d2635daa19

**Comment by osmanmeer** [comment]
I updated npm using 'npm install npm -g' but still getting the same error as OP. My current npm ver is 3.7.3.

**Comment by ReedRichard** [comment]
I am also seeing this issue with npm 3.8.2 on OS X.

**Comment by ayyash** [comment]
I get 
```
npm WARN angular2@2.0.0-beta.14 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.14 requires a peer of rxjs@5.0.0-beta.2 but none was installed.

```
using npm 1.3.6, when trying to install latest of rxjs and reflect-metadata, does this mean I have to install the older versions?

**Comment by LindsayBrown81** [comment]
I am using node v5.10.1 (npm v3.8.3) and I get 
`npm WARN angular2@2.0.0-beta.15 requires a peer of reflect-metadata@0.1.2 but none was installed.` I am able to serve my app on local server despite the above message.

**Comment by matthewharwood** [comment]
+1 @LindsayBrown81  ├── UNMET PEER DEPENDENCY reflect-metadata@0.1.2

**Comment by sateffen** [comment]
Just a little grind to the left: Why are this peer dependencies, if they are absolutely needed for angular? Why not regular dependencies? If it's well documented (and I expect angular to be well documented), then there is no problem? Or am I missing something?

I'm fighting with the version thing sometimes as well, especially when *npm-check-update* updates all dependencies, but angular depends on older versions and needs explicit versions.

**Comment by paynoattn** [comment]
even with the correct peer dependencies installed npm still warns as of 2.0.0-beta.17

**Comment by chaitugk01** [comment]
Go a head and install 

npm install es6-promise
npm install -g rx
 

like wise
