### ISSUE TITLE
Issue when navigate to an anchor!!?

### ISSUE THREAD

**Issue by pokakhoaitay** [angular/angular#5859]
I use HashLocationStrategy, the routing in my web is ok, and i have the following code:
```<a href="#jumpToHere">Jump</a>```
```<h3 id="jumpToHere">Hello</h3>```

When i click on ```<a>``` tag, angular2 throw this exception: EXCEPTION: TypeError: Cannot read property 'toUrlPath' of null
[...]

Link demo: http://plnkr.co/edit/hipD6Rq1AWTn8VXnQ4w3?p=preview
Please help me fix that error!? How can i navigate to an anchor without that error?
Thanks!

**Comment by tycho01** [comment]
(Cross-posted on [SO](http://stackoverflow.com/questions/34247981/angular2-navigate-to-anchor-error) where a work-around was given.)
You mentioned your original issue was a 404 error using `PathlocationStrategy`; perhaps others here would know of existing threads for that one.
Or is this already solved in newer versions?

**Comment by user414** [comment]
I'm having this issue as well as I posted here

https://github.com/angular/angular/issues/4735#issuecomment-202556201

However, the solution doesn't work for me I had to do the scroll to as discussed in that thread. Investigating why will post if I find more information.

**Comment by ericmartinezr** [comment]
This issue is still alive, but now it's under another error message. I don't know exactly when [this line](https://github.com/angular/angular/blob/master/modules/angular2/src/router/directives/router_outlet.ts#L41) was added, but throws the following message

```
Error: Uncaught (in promise): ObjectUnsubscribedError
```
See this [plnkr](http://plnkr.co/edit/mB28473Z8IQJrKYNpUQo?p=preview) and press "Failing link"

If you try the same plnkr changing beta.15 to beta.3 the error is
```
TypeError: Cannot read property 'toUrlPath' of null
```
The big difference is that with ObjectUnsubscribedError there's no stack to trace, this cause this issue https://github.com/angular/angular/issues/8072 and it was difficult to track. It's overlapping over the previous error message, making it almost impossible to debug.

cc @petebacondarwin

**Comment by user414** [comment]
@ericmartinezr Had the subscription error, perhaps you can see if it has anything to do with

https://github.com/angular/zone.js/issues/310

it looks like the same error.

And has far as this issue of navigating to anchor after investigating, at least for me, the issue was with the base href pointed to in the documentation which I believe is incorrect, see

https://github.com/angular/angular/issues/4735#issuecomment-204362103

**Comment by ericmartinezr** [comment]
@user414 it sounds similar, but it is not. The one you mentioned is related to zone, this one it's related to Router and specifically to the `@Output()` recently added plus using routes not defined in your links. It fails at some point because the activation of the route failed when creating/disposing it so the output fails.

**Comment by ericmartinezr** [comment]
After a little further investigation, the error is not in [this line](https://github.com/angular/angular/blob/master/modules/angular2/src/router/directives/router_outlet.ts#L41), this hasn't landed yet, it's not in b.15 nor previous versions. So the error it is in [this line](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#L508).

**Comment by DanielYKPan** [comment]
I use default PathLocationStrategy, and I am in localhost:3000/jump page, and my page have the following html:
<a href="#jumpToHere">Jump</a>
<h3 id="jumpToHere">Hello</h3>

When i click on <a> tag, I was navigated to localhost:3000/#jumpToHere which is not a route I already defined.
Any ideas?

**Comment by DanielYKPan** [comment]
I use default PathLocationStrategy, and I am in localhost:3000/jump page, and my page have the following html:
<a href="#jumpToHere">Jump</a>

<h3 id="jumpToHere">Hello</h3>
When i click on tag, I was navigated to localhost:3000/#jumpToHere which is not a route I already defined.
Any ideas?

**Comment by DanielYKPan** [comment]
I use default PathLocationStrategy, and I am in localhost:3000/jump page, and my page have the following html: 
`<a href="#jumpToHere">Jump</a>`
<h3 id="jumpToHere">Hello</h3>``
When i click on tag, I was navigated to localhost:3000/#jumpToHere which is not a route I already defined. Any ideas?

**Comment by vicb** [comment]
obsolete - former router
