### ISSUE TITLE
[devMode] Expression 'xxxx' was changed after it was checked

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#5950]
Started getting a lot of these error through my code since dev mode has been enabled by default. It happens when a bound expression is changed at various times.

One of those times is `ngAfterViewInit`/`ngAfterContentInit`. This is sometimes useful when I want to set a value based on `ContentChildren`/`ViewChildren`/etc. (for example add class based on how big is the content, or set display value of custom select component with options loaded with `ng-content`) 

http://plnkr.co/edit/PysWkWFX3kH6RK2iy4y3?p=preview

another example with `ngModel` and class binding:
http://plnkr.co/edit/3ZglnkFDi3oWj2zgix2W?p=preview

**In prod mode it works without throwing the error.**

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/issues/5918

**Comment by Necroskillz** [comment]
Yeah, I've seen that issue - but it's specifically about `slice`. It seems like the issue is broader than that.

**Comment by pkozlowski-opensource** [comment]
> It seems like the issue is broader than that.

Yes - it is about mutating model that was previously checked.

**Comment by pkozlowski-opensource** [comment]
I'm re-opening this one since model mutation in lifecycle callbacks needs more thinking

**Comment by miqmago** [comment]
I'm having the same problem with `ngClass`:
```html
<div [ngClass]="getFormClass(false)">
```

```javascript
    private getFormClass(isAdsBlock: boolean): Object {
        let isShowAds: boolean = this.selected || this.isAdsLoaded();

        if (isAdsBlock) {
            return { 'col-md-6 pull-left center col-xs-12': isShowAds };
        } else {
            return isShowAds ? { 'col-md-6 pull-right col-xs-12': true } : { 'col-xs-12': true };
        }
    }
```

`isAdsLoaded` changes because of an async script (google ads)

**Comment by vicb** [comment]
@miqmago the problem with this code is that you return a new object each time `getFormClass` is called.

One possible way to solve this would be:

```ts
class Component {
  classes = {
    'col-md-6': true,
    'pull-left': false,
    'pull-right': true,
    // ...
  };

  private getFormClass(isAdsBlock: boolean): Object {
    // Update the classes object
    // If possible re-compute the values on events only to be more efficient      
    this.classes['pull-right'] = ...;
    this.classes['pull-left'] = ...;

    return this.classes;
  }
}
```

The main idea here is to always return the same object.

**Comment by miqmago** [comment]
That worked thanks! :)

**Comment by Daynil** [comment]
@vicb I was having the same problem as @miqmago and your suggestion fixed it - that is, modify and return an existing object when getFormClass is called rather than always returning a new one.

In the docs, however, the example showing how to use ngClass shows setClasses() to return a new object each time, as we have been doing: https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngClass

Does this need to be updated in the docs or is it just a consequence of being in dev mode?

**Comment by vicb** [comment]
@Daynil, the docs need to be updated.

**Comment by cagataycivici** [comment]
A similar issue with ViewContainerRef createEmbeddedView using TemplateRef.

https://github.com/angular/angular/issues/7443

**Comment by tdterry** [comment]
I just started receiving this error with form validation. It happens if I check validity of a field before defining the field. It ONLY happens with the FormBuilder-style validation. If you move the div with the error message after the input field, the exception goes away. I'm using Angular2 Beta 13.

template
====
```
<form [ngFormModel]="myForm">
    <div [hidden]="field.valid">required</div>
    <input type="text" [(ngModel)]="value" ngControl="field" #field="ngForm">
</form>
```

component
====
```
constructor(fb: FormBuilder) {
    this.myForm = fb.group({
        field: ['', Validators.required],
    });
}
```

**Comment by vicb** [comment]
fixed

**Comment by wangyizhuo** [comment]
vicb, how is this issue fixed? Will updating view model in ngAfterViewInit / ngAfterContentInit still cause a change detection error?

**Comment by vicb** [comment]
I think this is a docs issues and should be opened on angular/angular.io.
WDYT ?

**Comment by wangyizhuo** [comment]
I learned that this is by design from: http://www.bennadel.com/blog/3040-i-have-a-fundamental-misunderstanding-of-change-detection-in-angular-2-beta-8.htm

Better doc will certainly help. I think many people may find this or other github issues. If you can close it with a doc link will be even better.

**Comment by MoonStorm** [comment]
@vicb How was this fixed? Using the latest 2.2.1 and the issue is still present. A simple update of the model in the ``ngAfterViewInit`` is still causing this error.

**Comment by DzmitryShylovich** [comment]
It's not an issue and there's nothing to fix.

**Comment by MoonStorm** [comment]
A change detection error should not occur at that stage. It's normal for the model to change there.
