### ISSUE TITLE
Async Pipe should handle default Scheduled Observable values appropriately 

### ISSUE THREAD

**Issue by r-park** [angular/angular#5992]
http://plnkr.co/edit/SmIayfV8FEMz2nkqs88z

What is the recommended way of passing an observable into an ngFor loop with async pipe? When I try the following (in dev mode):

``` javascript
@Component({
  selector: 'child',
  providers: [],
  directives: [NgFor]
  template: `
    <div *ngFor="#item of items | async">{{item.name}}</div>
  `
})
export class Child {
  items: Observable<any>;

  constructor() {
    this.items = Observable.create(subscriber => {
      subscriber.next([{name: 'foo'}]);
    });
  }
}
```

It raises this exception:

``` javascript
EXCEPTION: Expression 'items | async in Child@1:9' has changed after it was checked. Previous value: '[object Object]'. Current value: '[object Object]' in [items | async in Child@1:9]
```

**Comment by robwormald** [comment]
This is because the result is being delivered synchronously - watch the console here: http://plnkr.co/edit/GE7MQd0pqzWfFRERjZrJ?p=preview

In a typical Observable use case, this wouldn't be an issue (say, an Http request or similar) - but people are certainly going to run into it. That said, if its truly a sync thing, it's better to use a simple array.

A simple workaround for the moment is to use the .subscribeOn and pass a scheduler, as seen here : http://plnkr.co/edit/HIhAp12nlEUQQ8cYd8lh?p=preview

Will investigate.

**Comment by robwormald** [comment]
cc @jeffbcross @vsavkin

**Comment by r-park** [comment]
Sorry, I tried to simplify my issue for the plunk and ended up making it synchronous. 

This is probably a better example of one of my issues: http://plnkr.co/edit/D6SsoG62aZGTRjZZZScM
A service that fetches some data and emits it via ReplaySubject.

And something similar here https://github.com/r-park/todo-angular2-ngrx where I'm trying to render a list of todos retrieved from ngrx/store. Only works in prod mode.

**Comment by kylecordes** [comment]
I see the same issue with my angular2 firebase implementation and progress (link below); moreover, if possible I would like to see the goal here include obvious trivial cases like the one @r-park  started with, in which an observable has already emitted one or more values before being wired to the async pipe.

**Comment by kylecordes** [comment]
Oops, forgot the link. Unfortunately, I don't have an example program using this with beta.0 sitting online anywhere at the moment.

https://www.npmjs.com/package/angular2-firebase

**Comment by robwormald** [comment]
Things to note - 
- there's no reason to wait for `ngAfterViewInit` to wire these sorts of things up, especially when dealing with Observables. Avoiding that will stop most of these cases.
- When are you going fully reactive, turn on the OnPush change detection strategy - this is a big win as it will only trigger change detection when a new value arrives.
- When you have an initial value that exists at startup, use a BehaviorSubject.

See http://plnkr.co/edit/D4zqhqELL7VmzOMWboNc?p=preview

**Comment by robwormald** [comment]
@kylecordes have a look at Sara's Firebase Pipe from AngularConnect - it, like the async pipe, hooks into the change detector and allows far more efficient operation, as it'll only require change detection when a new value arrives: https://github.com/sararob/angular2base/blob/master/src/firebasepipe.ts

**Comment by r-park** [comment]
In my case, using OnPush as per @robwormald fixed both of my issues :+1:

**Comment by kylecordes** [comment]
@robwormald: About the change detection strategy, that appears to be an optimization useful when you have a component to which it applies for 100% of the bindings; it should not influence correctness, right?

About the BehaviorSubject - as a developer of a Component, I may find myself receiving (from other code) an observable that arrived from who-knows-where, and I don't know (or care?) whether this had any values come through or not. This seems like an essential part of the contract of an observable, that you can use it without worrying at the point of consumption whether the data started flowing before or after you are ready to consume it.

About the Firebase event pipe example from Angular Connect - I read that in depth while working on my stuff. But I was aiming to avoid the coupling in that code, between the notion of subscribing to Firebase, and hooking up for rendering. I was intentionally looking to separate those concerns with the Observable interface between them. If I understand the async pipe correctly, it (and not any code that cares at all about Firebase, for example) should be responsible for hooking up change detection to operate efficiently, only when the data coming through the observable changes.

Sorry for so many words. Looking back through them, I wonder if my expectation of the async pipe is off-base. What I would like it to do is be handed in arbitrary observable, in an arbitrary state, without regard to its scheduler, and have it "just work". I realize it is still early days for all of this, and that the documentation in-progress does not promise what I'm looking for above.

https://angular.io/docs/ts/latest/api/common/AsyncPipe-class.html

**Comment by robwormald** [comment]
@kylecordes There's no reason it shouldn't work - see https://github.com/angular/angular/pull/5624 - but there's obviously a bug, hence the *will investigate* comment and [bug] label on this issue. For what @r-park is doing, which is presumably containing all of his state in Observables (with my *extremely-alpha-not-supported-do-not-try-this-at-home* library, I might add) - OnPush is basically the ideal solution. Ditto for most any application that fully embraces reactivity. 

re: The Observable contract, I agree, but its not quite as simple as all that, as there are Observables (and not just the Rx flavor - we hope to support Bacon, Kefir, the ES proposal, etc) -  5 flavors of Subject, and a variety of Scheduler implementations that all deliver values in various fashions and interact with the event loop in all sorts of fun ways, and so it may take some time to massage all the various permutations to work nicely with change detection. 

No worries on the words, i'm equally passionate about this stuff.

**Comment by robwormald** [comment]
fixed in https://github.com/angular/angular/pull/5996

**Comment by rosendi** [comment]
@kylecordes @robwormald Why not just make firebase reactive and use the async pipe? https://github.com/rosendi/farel/blob/master/farel/pipes/terminals/to_array_pipe.ts

**Comment by kylecordes** [comment]
@rosendi I'm not sure exactly what you mean "why not" - what you wrote is approximately what my Firebase observable wrapper (in progress) does.  (It does not internally create an async pipe, it produces an observable which can then be used by the off-the-shelf async pipe.)

**Comment by sbesselsen** [comment]
This is still an issue for us. It's very confusing as your first instinct is that you probably did something wrong. It will lead to lots of developers peppering their code with setTimeout()s "just in case", which in turn makes Angular 2 look more complicated than it needs to.

**Comment by DzmitryShylovich** [comment]
Can't reproduce http://plnkr.co/edit/5NsURHGDJMzTl6hW5fwM?p=preview

**Comment by frederik** [comment]
@DzmitryShylovich I guess this is what most people tried (including me) but bar never showed up

http://plnkr.co/edit/hZzksZR79tDJBoF7HbCa?p=preview (based on your plunk)

As long as I run everything out of an Observable which I create at declaration time OnPush works as expected.

**Comment by DzmitryShylovich** [comment]
@frederik I don't think it's an issue. I added `name` prop in your example http://plnkr.co/edit/i3vgu2vNHdIETtwh5Jx2?p=preview

As u can see it doesn't update as well. This is because `ngAfterViewInit` runs after change detection cycle. In this case u need to notify angular about new changes yourself using `ChangeDetectorRef.detectChanges()`

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
