### ISSUE TITLE
feat: add ability to inject route related info in the route providers

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#60662]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Currently, If I want to provide a Store service on my route providers, I cannot get the route details for that route. In the example below, inside the UserDetailsStore I cannot get the ongoing navigation's ActivatedRouteSnapshot in order to use it for data fetching for example.

```ts
{
  path: 'user/:id',
  providers: [UserDetailsStore],
  component: Child,
  resolve: {
    loader: () => {
      inject(UserDetailsStore).loadUserDetails();
      return true;
    },
  },
},


@Injectable()
export class UserDetailsStore {
  someRouteData = inject(SOME_ROUTER_PROVIDED_TOKEN_FOR_THE_ROUTE);

  user = signal<{ id: string } | null>(null);

  loadUserDetails() {
    const id = this.someRouteData.paramMap.get('id')!;

    // fetch user data

    // set user
    this.user.set({ id });
  }
}
```

### Proposed solution
Provide access to ongoing navigation’s ActivatedRouteSnapshot on the route providers through some DI token.

### Alternatives considered

Passing the ActivatedRouteSnapshot around. 

```ts
{
  path: 'user/:id',
  providers: [UserDetailsStore],
  component: Child,
  resolve: {
    loader: (snapshot: ActivatedRouteSnapshot) => {
      inject(UserDetailsStore).loadUserDetails(snapshot);
      return true;
    },
  },
},


@Injectable()
export class UserDetailsStore {
  user = signal<{ id: string } | null>(null);

  loadUserDetails(snapshot: ActivatedRouteSnapshot) {
    const id = snapshot.paramMap.get('id')!;

    // fetch user data

    // set user
    this.user.set({ id });
  }
}
```

**Comment by atscott** [comment]
@mauriziocescon As mentioned in the alternatives, you have access to the route snapshot in the resolver parameters and can pass that to the service.

**Comment by atscott** [comment]
From discussions elsewhere: this request is covered by a reactive route resource that can be non-blocking or truly just `ActivatedRoute` available in the route providers (since this is trying to update the data in a non-blocking manner, not necessarily doing the load in a resolver)

**Comment by mauriziocescon** [comment]
This might be a very stupid question... apology in advance 🙏! 

The example I reported above is actually an adaptation from https://github.com/angular/angular/issues/60243#issuecomment-2741062197. Maybe I'm missing something very stupid... but I wonder: isn't `params = {}` as soon as the route is lazily loaded?

Example: https://stackblitz.com/edit/stackblitz-starters-s7pkwfey?file=src%2Fitem-detail%2Froutes.ts

```ts
bootstrapApplication(App, {
  providers: [
    provideHttpClient(),
    provideRouter([
      { path: 'items', loadChildren: () => import('./items/routes') },
      { path: 'item-detail/:id', loadChildren: () => import('./item-detail/routes') },
      { path: '**', redirectTo: '/items' },
    ]),
  ],
});
```

```ts
export default [
  {
    path: '',
    component: ItemDetail,
    title: 'Item Detail',
    providers: [
      {
        provide: ItemDetailStore,
        useFactory: () => {

          // Trying to retrieve :id from item-detail/:id?id=sameId but 
          // const queryParams = inject(ActivatedRoute).params; is empty!
          // 
          // Same operation is fine within the component (makes sense from the doc)! 
          //
          // queryParams is defined: below I'm retrieving id for the resource. 
        
          const params = inject(ActivatedRoute).queryParams;
          const id = toSignal(params.pipe(map((params) => params['id'] as string))) as Signal<string>;

          return new ItemDetailStore(id);
        },
      },
    ],
  },
] satisfies Route[];
```
I wonder: is there a way to retrieve `params` from the route definition for such cases?

**Comment by atscott** [comment]
The state of `ActivatedRoute` is not updated until right before the `RouteOutlet`s are activated.

**Comment by mauriziocescon** [comment]
I see, thanks a lot for the heads up! 

Say: in a world of signals, I think a factory function for initialising providers is great cause it lets you encapsulate the state (in this case the `id`) without leaking (no need to "sync" between components-stores)!  

Not a huge deal... but I wonder: would it be possible to keep this ticket as a feature request for this part? Assuming it makes some sense. 

Thanks again!

**Comment by BojanKogoj** [comment]
I've been waiting for this since `httpResource` landed. 
Currently I've had to used `effect` from component using `ComponentInputBinding`.
```ts
@Injectable({ providedIn: 'root' })
export class MyService {
  public id = signal(1);
  public userResource = httpResource<User>(
    () => `https://swapi.dev/api/people/${this.id()}`
  );
}
```

```ts
@Component({ ... })
export class Person {
  private myService = inject(MyService);
  public id = input(1, { transform: numberAttribute });

  constructor() {
    effect(() => {
      this.myService.id.set(this.id());
    });
  }
}
```

https://stackblitz.com/edit/stackblitz-starters-2ung6vya?file=src%2Fmain.ts

**Comment by mauriziocescon** [comment]
@BojanKogoj yeah, problem deeply discussed in https://github.com/angular/angular/issues/60243 (see last messages for the status)!

**Comment by mauriziocescon** [comment]
I often wonder whether this ticket, in combination with `withAutoCleanupInjectors`, would also make it easier for AI, humans, and tooling to reason about the DI hierarchy.

Assuming `withAutoCleanupInjectors` is in place, by looking at the route hierarchy, you'd have a nice blueprint of DI as well. 🧐

```ts
@Service({ autoProvided: false })
export class Store {
  private readonly activatedRoute = inject(ActivatedRoute);
  private readonly params = toSignal(this.activatedRoute.params);

  readonly orderId = computed(() => (this.params()?.['orderId'] as string) ?? '');
  readonly itemId = computed(() => (this.params()?.['itemId'] as string) ?? '');
}

@Component({
  // ⚠️ activatedRoute provides what's needed here; no insight into the DI hierarchy
  providers: [Store],
  template: `
    <h1>Item</h1>
    <p>activatedRoute: {{ store.orderId() }} / {{ store.itemId() }}</p>
  `,
})
export class Item {
  protected readonly store = inject(Store);
}

export const routes: Routes = [
  {
    path: 'orders/:orderId',
    children: [
      {
        path: 'item/:itemId',
        component: Item,
        // ⚠️ activatedRoute cannot see orderId / itemId; the scope of the store is known
        providers: [Store],
      },
    ],
  },
];
```

**Comment by atscott** [comment]
Closing this as injecting route snapshots or in-flight navigation state into route-level providers is problematic.

A static snapshot in route providers doesn't work because the route injector is reused across navigations to the same route (like `/user/1` to `/user/2`), so anything injected at creation time becomes stale on subsequent navigations. To handle param updates it would have to be reactive, and making it available during resolvers/guards would mean exposing speculative, in-flight navigation state in DI before the navigation is actually committed.

The primary use case here—loading data based on route params without having to wire up resolvers or sync things via component effects—is solved by the router resources API (`Route.resources`). `ResourceContext` gives you reactive param signals directly on the route definition:

```ts
{
  path: 'user/:id',
  component: UserComponent,
  resources: ({ params }) => ({
    user: httpResource(() => `/api/users/${params().id}`)
  }),
}
```

This handles route reuse and navigation cancellation cleanly without needing resolvers or DI workarounds.

**Comment by mauriziocescon** [comment]
Thanks for the info @atscott ! I still don't get why
> exposing speculative, in-flight navigation state in DI before the navigation is actually committed.

Let me use the new `resources` capability in a different way:
```ts
class Store {
  private readonly id: Signal<string>;
  readonly search = signal('');

  readonly item = httpResource(() => `https://jsonplaceholder.typicode.com/posts/${this.id()}/comments?q=${this.search()}`);

  constructor(id: Signal<string>) {
    this.id = id;
  }
}

const PARAMS = new InjectionToken<any>('PARAMS');

bootstrapApplication(App, {
  providers: [
    provideRouter(
      [
        {
          path: 'item/:id',
          component: Item,
          providers: [
            {
              provide: PARAMS,
              useFactory: () => {
                const params = linkedSignal<any>(() => signal({}));
                return {
                  get: params.asReadonly(),
                  set: (p: any) => params.set(p),
                };
              },
            },
            {
              provide: Store,
              useFactory: () => {
                const params = inject(PARAMS).get();
                const id = computed(() => params().id);
                return new Store(id);
              },
            },
          ],
          resources: (ctx: any) => {
            const params = inject(PARAMS);
            params.set(ctx.params);
            return {};
          },
        } as Route,
        { path: '**', redirectTo: '/item/1' },
      ],
      withExperimentalAutoCleanupInjectors(),
      ɵwithRouterResources()
    ),
  ],
});
```
https://stackblitz.com/edit/stackblitz-starters-dufamxac

Maybe I'm missing something obvious, but conceptually I don't see anything really debatable here, except for the fact that "you cannot read params in providers, while you can in resources". True — but in my eyes, this is no different from the fact that you cannot read required signal inputs in component constructors. Same bucket!

---

Now, you might object that the DI tree is separate from the component tree, and that the two shouldn't intersect the way I propose above. I get it, but based on what I see and experience every day, this separation is unfortunately not ideal: it breaks the natural colocation between the route definition and the provider definitions for the chain of components.

Moreover, I believe a route defined like the one above is far easier to reason about for agents. I ran some tests with agents of medium/low reasoning capabilities: none of them gave the right answer to "does Store have access to itemId from activatedRoute in the example below?". The answer was always "sure, it's defined at the same level".

```ts
export const routes: Routes = [
  {
    path: 'orders/:orderId',
    children: [
      {
        path: 'item/:itemId',
        component: Item,
        providers: [Store],
      },
    ],
  },
];
```

To sum up: I like the design of resources — it makes sense for simple cases. But ideally, it would be nice to support more advanced cases where a Store is:
- provided at the route level,
- created at the route level,
- destroyed when you navigate away,
- initialized based on reactive params / query params,
- and everything is derived / composed at the Store level for many child components (Note: data fetching can depend on router data combined with other component fields).

My 2 cents!

**Comment by atscott** [comment]
Your example is hardly different from just providing the service in the component providers and injecting ActivatedRoute. All of your bullet points are addressed by component providers.

 Enea was originally requesting this for the purposes of using the information in resolvers and retaining it once the route loads. This is addressed directly by the resource integration. Your example would be more appropriately served with resources or component providers.

**Comment by mauriziocescon** [comment]
Sorry, I didn't mean to hijack Enea's request or create friction in general. My bad! ☮️

I know I can provide Store at the component level and inject ActivatedRoute, so it's not a blocking issue. I just tried my best to explain why I think it's inconvenient (colocation / AI), especially since the introduction of AutoCleanupInjectors.
