### ISSUE TITLE
The service worker v.20.2.0 freezes the browsers, works correctly with v20.1.0

### ISSUE THREAD

**Issue by meriturva** [angular/angular#63500]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

The issue is quite simple, and also easy to reproduce: the new implementations on v20.2 added to the service worker cause abnormal behavior, blocking the site from loading, especially during a page refresh.

How to reproduce:

1. ng new application-name
2. ng add @angular/pwa
3. ng serve -c=production
4. Open browser (Chrome 139.0.7258.155 on my side) and hit the refresh button
5. The browser is loading infinitely 

### Please provide the exception or error you saw

```true
Unfortunately, the browser is frozen and there are no error messages. Only some requests remain pending.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 20.2.1
Node: 22.18.0
Package Manager: npm 10.9.3
OS: win32 x64


Angular: 20.2.3
... common, compiler, compiler-cli, core, forms
... platform-browser, router, service-worker

Package                      Version
------------------------------------
@angular-devkit/architect    0.2002.1
@angular-devkit/core         20.2.1
@angular-devkit/schematics   20.2.1
@angular/build               20.2.1
@angular/cli                 20.2.1
@schematics/angular          20.2.1
rxjs                         7.8.2
typescript                   5.9.2
zone.js                      0.15.1
```

### Anything else?

Deploy the application with version 20.1 to temporarily resolve the issue.

**Comment by SkyZeroZx** [comment]
In my case I have a demo application with PWA and SSR in Angular 20.2.3, you can see the repository here I just updated it
Repo : https://github.com/SkyZeroZx/ng-ssr-twa-adaptive
App Deployed in Vercel : https://ng-ssr-twa-adaptive.vercel.app/
It works well for me
Chrome Version : 139.0.7258.155


EDIT : 
Update: If you run it with ng serve -c=production , you might use something like this:
```ts
const swRegistrationOptions: SwRegistrationOptions = {
enabled: !isDevMode(),
// Register the ServiceWorker as soon as the application is stable
// or after 30 seconds (whichever comes first).
registrationStrategy: 'registerWhenStable:30000'
};
```

It stays loaded indefinitely because you try to enable the service worker. In my experience, I remember you can never enable it in development mode because it "freezes." In my case, it works if I use https://www.npmjs.com/package/http-server, as far as I remember.

The app deployed in production under HTTPS that I mentioned above works.

**Comment by jvegaseg** [comment]
I'm experiencing the same issue.

**Comment by meriturva** [comment]
Unfortunately, this issue is very difficult to reproduce, and I suspect it is related to the update of the service worker from a previous version to the latest one. In particular, to work around the problem, I released a version of my enterprise application without enabling the service worker.
Additionally, I included a very simple JS script to remove the service worker:

```
navigator.serviceWorker.getRegistrations().then(registrations => {
  for (const registration of registrations) {
    registration.unregister();
  }
});
```

When the issue occurs, my clients’ browsers get stuck for about 30 seconds (waiting for a timeout), after which the application loads correctly and then executes the instructions to “unregister” service worker. Now, without any service worker, application runs as expected.
Only in this way was I able to provide a solution to all the complaints I received in recent days (I spent days investigating the server because I thought it was a network issue, but in the end, I believe it’s a combination of conditions between an old version of ngsw-worker.js and its update to the new version v.20.2).

On same time, i spent a lot of time trying to simulate the issue with a clean project and http-server without any success.

What about your project @jvegaseg ? Did you find a way to easily replicate the issue?

**Comment by jvegaseg** [comment]
I am attempting to isolate the issue, but I cannot obtain any logs because the browser freezes. In my case, when I try to access the application using `localhost:4200` with `ng serve`, the browser consistently freezes.

If I cancel the request (using the stop button in the browser) and perform a hard reload with **Ctrl+Shift+R**, the application loads successfully. However, when I subsequently refresh the page, it freezes again. If I cancel once more and perform another **hard reload**, the page loads successfully again.

This behavior is quite unusual, and I will continue investigating.

**Comment by meriturva** [comment]
What I have noted is that if you clear all site service workers and cache using, for example, DevTools -> Application -> Storage -> "Clear site data" everything starts to work again. Another test, quite simple, is to start the application using a different network port (a random one), so you can start with a service worker from the latest package version. @jvegaseg  Could you please try?

**Comment by jvegaseg** [comment]
I have already tried the following:

- **Clear site data**: it does not resolve the issue.

- **Change the network port**: it works the first time I use that port, but then the same problem occurs again.

**Comment by jvegaseg** [comment]
I was able to set a breakpoint in the service worker (**ngsw-worker.js**). The code consistently halts at line **1803**, at `await this.ensureInitialized(event);`, and it never resumes from there:

<img width="1131" height="854" alt="Image" src="https://github.com/user-attachments/assets/ccc29c1b-ac7e-424a-8bce-72c5a8eeded9" />

The value of `event` was:

<img width="2248" height="674" alt="Image" src="https://github.com/user-attachments/assets/91e28763-12e6-4126-9e1d-d0610f0ce8ac" />


In another try, within  ensureInitialized(),  could be the problem here?:

<img width="911" height="170" alt="Image" src="https://github.com/user-attachments/assets/d578fd26-2096-423f-b7f8-374198170bc4" />

Where error was:

```
SwCriticalError: Hash mismatch (cacheBustedFetchFromNetwork): http://localhost:4200/action.component-J6KFWARO.js: expected 05347f5e20eacab9f783f81475e5e090a8884c2a, got fa578afc4dace3ec0cb6f16496f86836ad1a1eac (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (ngsw-worker.js:578:21)
    at async PrefetchAssetGroup.fetchFromNetwork (ngsw-worker.js:550:19)
    at async PrefetchAssetGroup.fetchAndCacheOnce (ngsw-worker.js:529:21)
    at async ngsw-worker.js:657:9
    at async ngsw-worker.js:643:9
    at async ngsw-worker.js:643:9
    at async ngsw-worker.js:643:9
    at async ngsw-worker.js:643:9
    at async ngsw-worker.js:643:9
    at async ngsw-worker.js:643:9
```

**Comment by meriturva** [comment]
Same here using `npx http-server` on dist folder after `ng build`

<img width="1409" height="201" alt="Image" src="https://github.com/user-attachments/assets/50f7a34a-bea6-431c-9efb-b6a363ac071c" />

And on my dist folder there is no `chunk-23PK7XQE.js`

<img width="357" height="389" alt="Image" src="https://github.com/user-attachments/assets/07ca9190-7d25-46b6-87ab-221e056e0f07" />

I inspected more, and it happens when the cache storage is already present and an old version of "manifest".

<img width="635" height="91" alt="Image" src="https://github.com/user-attachments/assets/0b300faf-fdd4-429f-9293-68a5ed68dfb3" />

Basically, as I assumed on my first post, it happens only during the upgrade from an old version to the new one.

**Comment by unalkyl** [comment]
Same here. The application starts working when I unregister the service worker. Then, after a few minutes, I see the browser start to reload and the application crashes again.

**Comment by santiagof4** [comment]
We have the very same issue in our app after upgrading to Angular 20.2. Weirdly, the most reliable way to reproduce it is to close the browser entirely, opening it again and then try to open our app. The app gets stuck loading, in the devtools' network tab the very first request stays stuck pending. As far as we can tell, only Chromium based browsers are affected, even our Electron app is affected by the very same issue.

The only way to recover from this is to either unregister the service worker, or to refresh the page, but then it eventually happens again, or immediately after the browser get closed and opened again.

<img width="1488" height="872" alt="Image" src="https://github.com/user-attachments/assets/932a9451-d144-40f2-8a14-797ae102e50b" />

**Comment by meriturva** [comment]
@santiagof4 did you find a way to make v20.2 work with service worker? I had to disable the service and a few features to make my app work again.

**Comment by santiagof4** [comment]
@meriturva I tried a lot of stuff and sadly the only solution so far is to downgrade to v20.1.8

**Comment by jvegaseg** [comment]
@JeanMeche, do you need more info/clarification?

**Comment by SkyZeroZx** [comment]
I have a question about the applications you've been testing: are they Angular-based PWAs, or do any of them use server-side rendering ? I'd like to know more so I can try to replicate them.

**Comment by jvegaseg** [comment]
In my case, it is Angular-based PWA.

**Comment by meriturva** [comment]
> I have a question about the applications you've been testing: are they Angular-based PWAs, or do any of them use server-side rendering ? I'd like to know more so I can try to replicate them.

Just simple pwa!

**Comment by roger6106** [comment]
Same issue here. It's a simple PWA. Only chromium-based browsers are affected. Safari and Firefox work fine.

I had also found the same replication method posted above:
1. Quit the browser
2. Opening the browser
3. Visit the affected site

I was able to work around this by reverting @angular/service-worker to 20.1.8 while keeping the rest of Angular on 20.3.1. This is obviously unsupported and could easily have problems, but it allows me to keep using the functionality of the newer versions.

**Comment by MaksymPlotnikov** [comment]
I'm having the same issue on 20.3.4. It's really hard to catch. I'm glad I found this thread because it gave me the idea of how to localize the problem!

**Comment by jpintoF** [comment]
Same issue, any patch to avoid this behaviour, and at least, show last deployed version of my PWA?

**Comment by meriturva** [comment]
@MaksymPlotnikov, I’m happy that others have this issue too, but I see there isn’t much interest from the team, please, @JeanMeche take a look here. In my case, instead of using a previous version of the package, I disabled the service worker while waiting for a patch.

**Comment by jpintoF** [comment]
i made a rollback to v20.1.8 on @angular/service-worker package as suggest @roger6106 but still persist the problem, maybe i will disable service worker too while wait for a patch/fix

**Comment by xnf** [comment]
We (team of 3) also got into this issue suddenly today. Chrome/Firefox fails, Safari works. 
For now it fails only on localhost, and we brace ourselves for it to fail on prod.

Meanwhile the angular team proudly presented MCP...

**Comment by MaksymPlotnikov** [comment]
I had to remove all SW code and eagerly waiting for a fix from the Angular team...

**Comment by tmac12** [comment]
same problem also with v.20.3.7! Waiting for a fix

**Comment by atscott** [comment]
Is it possible to narrow this down further to a particular `20.2.0-next.#` or `20.2.0-rc.#` release?

**Comment by roger6106** [comment]
I have not narrowed it down, but it may be beneficial to do that. Here are the specific changes listed as affecting the service worker:

## [20.2.0-rc.0](https://github.com/angular/angular/releases/tag/20.2.0-rc.0)
- #63059

## [20.2.0-next.4](https://github.com/angular/angular/releases/tag/20.2.0-next.4)
- #62834
- #62831

## [20.2.0-next.3](https://github.com/angular/angular/releases/tag/20.2.0-next.3)
- #62737
- #62718

## [20.2.0-next.2](https://github.com/angular/angular/releases/tag/20.2.0-next.2)
- #62721

**Comment by meriturva** [comment]
My apps, unfortunately still running with service workers disabled. What about the new upcoming Angular version 21.x? I don't see any updates related to that issue, am I wrong?

**Comment by atscott** [comment]
I have observed that this works in 20.2.0-next.2 but is broken in 20.2.0-next.3. More work needs to be done to narrow down the issue further to an individual commit, if possible.

**Comment by atscott** [comment]
https://github.com/angular/angular/commit/6d011687ec1fa2b8f0211379bb98adc8e02f4e9a appears to be the culprit. 

Testing in the local app on main, the issue reproduces. Reverting the commit above resolves the issue.
