### ISSUE TITLE
Router: Provide support for handling the URL hash

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#6595]
If I have a URL with a hash, when I navigate to it, the hash is dropped from the URL and the page does not jump to the anchor tag. If I have to go an existing route and click a link with the hash at the end, it jumps to the anchor tag correctly. Also, their isn't a public api to get/set the hash outside of using `window.location.hash`

**Comment by ThiagoT1** [comment]
+1

**Comment by tamalnath** [comment]
Do we have any update on this?

**Comment by yeegr** [comment]
Yes, I need this really quick as well.

**Comment by p-mcgowan** [comment]
+1 please fix. This is mandatory for md-tab routing as well.

**Comment by afirdousi** [comment]
Are there any plans on this ?

I was thinking on a few scenarios in my angular 2 prod app. As for designing a solution, will it makes sense to have these values on each route in @RouteConfig as well as when the user uses router.navigate(). The user should be allowed to navigate to a position or #hash, by default to the top (0,0)

It may look something like:

`
@RouteConfig([
  { path: '/route1', component:Component1, name:'R1'  },  // Scrolls to default (0,0)
  { path: '/route2', component:Component2, name:'R2', position:(0,600)  }, // open at 600px vertically
  { path: '/route2', component:Component2, name:'R3', hash:"#about"  } // opens at #about
`

and on `router.navigate` it may look like

`
    this.router.navigate([ "R2" , { } , { position:(0,600) } ])  
    //or
    this.router.navigate([ "R3" , { } , { hash:"#about" } ])  
`


I believe we need changes in `Instruction` and `ComponentInstruction` classes down i `angular/route`.

This or any other better solutions we implement, will it jump to the position or scroll smooth to the specified position. Idk.

**Comment by kucharzyk** [comment]
+1 
please fix this issue

**Comment by emesx** [comment]
+1 (#8105)

**Comment by brandonroberts** [comment]
Support for fragments has been added to the v3 router

**Comment by mark-langer** [comment]
The router at release `alpha.8` does update the URL - including the hash - correctly but does not make the view jump to the anchor specified by that hash.

Let's assume you are at this location:
`www.example.org/Comp1/Comp2`

Then clicking this link:
`<a [routerLink]="['Comp3']" fragment="Test">Jump to 'Test' anchor </a>`

will update the browser's url to:
`www.example.org/Comp1/Comp2/Comp3#Test`

So far, so good.

However, the view does not automatically scroll/jump to the element with id "Test". Are there any plans to fix this or am I just missing something?

**Comment by justme1** [comment]
Using `this._router.navigate( ['/feed',  event ], {fragment: 'comments'});`

How can I retrieve the fragment in `ngOnInit` so I can focus on the comments section?

**Comment by justme1** [comment]
Found the answer:

http://victorsavkin.com/post/145672529346/angular-router

     constructor(private router:Router){
            const f: Observable<string> = _router.routerState.fragment;
            f.subscribe(params => {
                 debugger; // params == 'comments'
            });

**Comment by goelinsights** [comment]
@mark-langer did you ever get this working? Stuck in the same place where the #fragment works in the link but browser doesn't scroll to the id location.

**Comment by mark-langer** [comment]
Nope, I just stumbled upon this issue on stackoverflow. I didn't need to fix this for my own application. I haven't tried it since alpha.8, though. Have you tried if this works with RC.5?

**Comment by goelinsights** [comment]
It’s creating the #fragment in the route but not navigating to it via the angular router (v3) and I’m in RC4 currently.  On page refresh it works, but that kind of defeats the point.

**Comment by mark-langer** [comment]
Yes, absolutely agreed. Maybe the Chuck Norris of routing, @brandonroberts, can help?

**Comment by brandonroberts** [comment]
@mark-langer lol. Yea, I believe this is still an issue. The generation works fine, but if you click a link with a fragment in it, it doesn't jump to the anchor point

**Comment by FuKe** [comment]
+1 - I need this too.

**Comment by brandonroberts** [comment]
@vsavkin reopening this one as it does not jump to an anchor after navigation.

Plunker: http://plnkr.co/edit/zjBy5a?p=preview

**Comment by NathanWalker** [comment]
Just ran into this limitation :(  @brandonroberts thx for providing that plunkr to help illustrate ... looking fwd to when this fix is available.

**Comment by vsavkin** [comment]
Fixing it properly requires us to create a scrolling service (similar to what we have in Angular 1), which would be new API. We are not adding new API until the final is out.

As a temporary workaround, you can do the following:

```
class MyAppComponent {
  constructor(router: Router) {
      router.events.subscribe(s => {
       if (s instanceof NavigationEnd) {
         const tree = router.parseUrl(router.url);
         if (tree.fragment) {
           // you can use a 
           const element = document.querySelector("#" + tree.fragment);
           if (element) { element.scrollIntoView(element); }
         }
      }
     });
  }
}
```

**Comment by Luchillo** [comment]
May i ask how will it play out with URL sharing? say i have anchor tags that shows up in a content that is rendered by angular 2, thus available long after the page load, and i share the link with an anchor tag to link to a specific part of that app's page.

An example of this is my repo [Luchillo-tech-showcase](https://github.com/Luchillo/Luchillo-tech-showcase) which on load it reads some markup and parses it to html with Showdown, it generates some id's in title tags and if i try to use the anchor like `/#/home#license` it should scroll down to that content right? well it doesn't since the content is load after Angular 2 and so it's not available at the moment the browser checks the anchors.

Sharing links to specific parts of documents doesn't work well if we rely on anchor tags, so how would this play with Angular 2.0?

**Comment by bezigon** [comment]
The problem exists, and it must somehow solve.
For example, there is a project https://github.com/auth0-blog/angular-2-authentication-tutorial + modified router settings. As a result, access token doesn't handled in router configured with "useHash: true".
@vsavkin temporary workaround above not working.

**Comment by RandomAshes** [comment]
Here's how we solved the issue:
` goTo(): void {
      // this will scroll the page up
      window.location.hash = 'myAnchor';

      if (location === 'Get A Quote') {
        // @todo Route to 'Get A Quote' page
      } else {
        // after page scrolls up, scroll down to correct level
        // https://github.com/angular/angular/issues/6595
        setTimeout(() => {
          document.querySelector('#myAnchor').parentElement.scrollIntoView();
        });
    }
  }`

**Comment by mictibo** [comment]
Another Hacked solution inspired from @RandomAshes but that will work with any anchor
`goTo(anchor: string) {
    // TODO - HACK: remove click once https://github.com/angular/angular/issues/6595 is fixed
       setTimeout(() => {
           (<HTMLScriptElement>document.querySelector('#'+ anchor)).scrollIntoView();
       }); 
   }`

**Comment by jxxcarlson** [comment]
I also very much need a solution to this problem.  The app at [www.manuscripta.io](http://www.manuscripta.io), an Angular 1.* app, follows anchor links "normally".  I am working on an Angular2 version which is quite far along -- but missing this.

**Comment by DzmitryShylovich** [comment]
can somebody provide a small repro in plunkr if this is still an issue ?

**Comment by brandonroberts** [comment]
Here is the previous plunker updated to show the issue: http://plnkr.co/edit/zjBy5a?p=preview

**Comment by charlesaraya** [comment]
based on @vsavkin workaround, and taking advantage that fragments are provided as an observable:
```javascript
class MyAppComponent implements OnInit{

  constructor(private route: ActivatedRoute) { }

  ngOnInit() {
    this.route.fragment.subscribe(f => {
      const element = document.querySelector("#" + f)
      if (element) element.scrollIntoView(element)
    })
  }
}
```

**Comment by gowthamrodda** [comment]
@charlesaraya suggested code by you will work when the application loads first time. how to run the code in ngOnInit() when an click event get triggered?

**Comment by tcoz** [comment]
@gowthamrodda use what @charlesaraya says, just put it in an onclick in the component. 

```
<a [routerLink]="['/errata']" fragment="article_2" (click)="onAnchorClick()">Article 2</a>

constructor( private route: ActivatedRoute ) {}

onAnchorClick ( ) {
    this.route.fragment.subscribe ( f => {
      const element = document.querySelector ( "#" + f )
      if ( element ) element.scrollIntoView ( element )
    });
  }
```

**Comment by jxxcarlson** [comment]
Has anyone tried the following with success? [simple-page-scroll](https://github.com/bbottema/ng2-simple-page-scroll)

**Comment by tcoz** [comment]
I wrote an article on this subject, very straightforward to do without new components/directives etc:

Note that I use hashtag anchors to navigate on the page:

http://www.tcoz.com/newtcoz/#/errata#article_3 <http://www.tcoz.com/newtcoz/#/errata%23article_3>

**Comment by tcoz** [comment]
Ah note more angular 2 router peculiarities: when linking out from this email, it encodes the URL such that the hashtag gets rewritten, which breaks the incoming URL. Ugh this router thing is a complicated mess.

Anyway, go to www.tcoz.com <http://www.tcoz.com/>, click “Errata”.

**Comment by ThunderRoid** [comment]
So, to conclude, there is no official solution yet.

**Comment by genuinefafa** [comment]
good solution @tcoz 👍

**Comment by photostu** [comment]
@charlesaraya Thank you for that, perfect!

**Comment by antitoine** [comment]
@charlesaraya thank you for this workaround, but it is better to put it in the `ngAfterViewChecked` to make sure that the page is loaded:

```typescript
export class AppComponent implements AfterViewChecked, OnDestroy {

  constructor(private route: ActivatedRoute) { }

  ngAfterViewChecked() {
    this.routeFragmentSubscription = this.route.fragment
      .subscribe(fragment => {
        if (fragment) {
          let element = document.getElementById(fragment);
          if (element) {
            element.scrollIntoView();
          }
        }
      });
  }

  ngOnDestroy() {
    this.routeFragmentSubscription.unsubscribe();
  }
}
```

**Comment by tcoz** [comment]
Hmm...you can't click the anchor until after the page had loaded...but whatever works, glad you found a way.

**Comment by htrex** [comment]
Please fix this, seeing this problem with Angular 2.4.8 and router 3.4.8.

**Comment by ranavc32** [comment]
I am trying to pass fragment from one component to another and giving the id same as fragment to the div in target component still, its not scrolling to that div.

Is there any input on this.
Thank you !

**Comment by danmcclure** [comment]
@antitoine ngAfterViewChecked() gets called continuously per every ngDoCheck so it's not really the best place unless you unsubscribe after navigation.

**Comment by ReneVallecillo** [comment]
Well the afterViewInit does not work coming from other component. Sometimes it scrolls sometimes it doesn't

**Comment by MrGrigri** [comment]
The one main problem with @charlesaraya solution, or the way Angular is handling this, is that the css pseudo class `:target` is not working properly. It's supposed to update instantly, and this does not get updated at all. 

Do we have an ETA on a fix or proper implementation yet?

[MDN Pseudo-classes :target](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)

**Comment by JavierFuentes** [comment]
@antitoine solution is the only has worked for me...

I've only refined a little my code:

First, prepare `MyAppComponent` for automatic scrolling in **ngAfterViewChecked()**...

```typescript
    import { Component, OnInit, AfterViewChecked } from '@angular/core';
    import { ActivatedRoute } from '@angular/router';
    import { Subscription } from 'rxjs';
    
    @Component( {
       [...]
    } )
    export class MyAppComponent implements OnInit, AfterViewChecked {
    
      private scrollExecuted: boolean = false;
    
      constructor( private activatedRoute: ActivatedRoute ) {}
    
      ngAfterViewChecked() {
      
        if ( !this.scrollExecuted ) {
          let routeFragmentSubscription: Subscription;
      
          // Automatic scroll
          routeFragmentSubscription =
            this.activatedRoute.fragment
              .subscribe( fragment => {
                if ( fragment ) {
                  let element = document.getElementById( fragment );
                  if ( element ) {
                    element.scrollIntoView();
                  
                    this.scrollExecuted = true;
                  }
                }
              } );
      
          // Free resources
          setTimeout(
            () => {
              console.log( 'routeFragmentSubscription unsubscribe' );
              routeFragmentSubscription.unsubscribe();
            }, 1000 );
        }

      }

    }
```

Then, navigate to `my-app-route` sending `prodID` hashtag

```typescript
    import { Component } from '@angular/core';
    import { Router } from '@angular/router';

    @Component( {
       [...]
    } )
    export class MyOtherComponent {
    
      constructor( private router: Router ) {}
    
      gotoHashtag( prodID: string ) {
        this.router.navigate( [ '/my-app-route' ], { fragment: prodID } );
      }
    
    }
```

**Comment by vicky-gonsalves** [comment]
Here is another workaround with reference to JavierFuentes answer:

`<a [routerLink]="['self-route', id]" fragment="some-element" (click)="gotoHashtag('some-element')">Jump to Element</a>

in script:

```
import {ActivatedRoute} from "@angular/router";
import {Subscription} from "rxjs/Subscription";

export class Links {
    private scrollExecuted: boolean = false;

    constructor(private route: ActivatedRoute) {} 

    ngAfterViewChecked() {
            if (!this.scrollExecuted) {
              let routeFragmentSubscription: Subscription;
              routeFragmentSubscription = this.route.fragment.subscribe(fragment => {
                if (fragment) {
                  let element = document.getElementById(fragment);
                  if (element) {
                    element.scrollIntoView();
                    this.scrollExecuted = true;
                    // Free resources
                    setTimeout(
                      () => {
                        console.log('routeFragmentSubscription unsubscribe');
                        routeFragmentSubscription.unsubscribe();
                      }, 0);
                  }
                }
              });
            }
          }

        gotoHashtag(fragment: string) {
            const element = document.querySelector("#" + fragment);
            if (element) element.scrollIntoView(element);
        }
}
```
This allows user to directly scroll to element, if user directly lands on the page having hashtag in url.

But in this case, I have subscribed route Fragment in `ngAfterViewChecked `but `ngAfterViewChecked()` gets called continuously per every `ngDoCheck `and it doesn't allows user to scroll back to top, so `routeFragmentSubscription.unsubscribe` is called after a timeout of 0 millis after view is scrolled to element.

Additionally `gotoHashtag `method is defined to scroll to element when user specifically clicks on the anchor tag.

**Comment by natsid** [comment]
Bumping this issue: is there any plan to support link fragments (without tricky workarounds) in Angular?

**Comment by j2L4e** [comment]
All the above seems unnecessarily complex:

With dynamically rendered IDs
```
<div [id]="'some-id'">...</div>
```

Just reassigning the location works (at least in chrome, haven't tested others)
```
  ngAfterViewInit(): void {
    if(location.hash){
      location.assign(location.href);
    }
  }
```

**Comment by CoreyCole** [comment]
Using @charlesaraya solution on angular@4.2.4 I was getting the error 
```
ERROR DOMException: Failed to execute 'querySelector' on 'Document': '#' is not a valid selector.
```
This was happening when the fragment was empty/null. I fixed this by adding a filter to the fragment observable
```
import 'rxjs/add/operator/filter';
\\ ...
ngOnInit() {
  this.route.fragment
    .filter(f => f && f.length > 0)
    .subscribe(f => {
      const element = document.querySelector('#' + f);
      if (element) {
        element.scrollIntoView(element);
      }
    });
}
```

**Comment by RandomShaper** [comment]
One step ahead (or so I believe):

```js
  private fragment: string;

  constructor(private route: ActivatedRoute { }

  ngOnInit() {
    this.route.fragment.subscribe(fragment => { this.fragment = fragment; });
  }

  ngAfterViewChecked(): void {
    try {
      document.querySelector('#' + this.fragment).scrollIntoView();
    } catch (e) { }
  }
```

This one is as little bloated as possible, while "handling" no fragment, invalid fragment and no element found conditions.

**Comment by studiobl** [comment]
For accessibility, focus should be placed on the target element, not just scroll into view. Screen reader users will need the target element to be focused in order to perceive it's contents.

**Comment by waterplea** [comment]
I have a component that is used in many routes and depending on a route it is filled with different values. It always has predefined sections for the content and a navigation to those sections. I cannot have a link on a route to that very same route. Leaving routeLink empty or making it "./" does not activate the link so none of this workarounds will be suitable for basic section navigation on the same route, unless I'm missing something.

**Comment by badcoder28** [comment]
Got my problem solve thanks to @tcoz working solution. However removing the element part to `scrollIntoView(element)` argument gave me the right result.

Current url `localhost:3000/im/here`
```
 <li class="mat-caption"><a  [routerLink]="['.']" fragment="test">Jump to span</a></li>

<div>
   ... some lengthy elements
    <span id="test">Come here!</>
</div>

```

```
// inside in ngOnInit()
this.route.fragment.subscribe(f => {
      const element = document.querySelector('#' + f);
      if (element) {
        element.scrollIntoView(); // <-- omit element from the argument
      }
});
```

Got this url after clicking the anchor: `localhost:3000/im/here#test`

**Comment by RKopczynski** [comment]
I am not sure if it's good alternative, but I just wrote this:

`
<a class="button" href="myComponent#test">Find my test!</a>
`

It translate url to `localhost:port/myComponent#test` and works just fine without any additional code in components.

Unfortunately it works only when "myComponent" is actually opened. Same solution not worked when I tried to jump from another component to `myComponent#test`

**Comment by yooRabbit** [comment]
How can I add animation in scrollIntoView?by the way still don't have official solution since angular 5.

**Comment by xmcax** [comment]
Workaround provided by @badcoder28, would be fine, if it wasn't for the fact that it works only the first time you use it. If you click the link second time, URL does not get updated and so Observable does not emit anything...

**Comment by waverly** [comment]
https://stackoverflow.com/questions/48141804/angular-2-routing-with-fragments-async-data - struggling to get this working. anyone have any ideas?

**Comment by bennadel** [comment]
I just ran into this same issue (jump-to-anchor functionality). So, I wanted to throw my hat into the ring -- I took [an approach that **polyfills** the behavior with a Module](https://www.bennadel.com/blog/3402-creating-a-jump-to-anchor-fragment-polyfill-in-angular-5-2-0.htm). This way, your code doesn't actually have to change; and the polyfill can be removed once Angular core implements the fragment navigation.

It works by creating a directive that binds to `selector: "[id], a[name]"` and then monitors the `activatedRoute.fragment` stream. So, not all that different from some of the previous suggestions. But, different in that your app doesn't really have to "know" about any of this.

**Comment by jorgjanke** [comment]
This worked for me best for all navigation changes:

```
constructor(private route: ActivatedRoute) {}

ngOnInit() {
   this._sub = this.route.fragment.subscribe((hash: string) => {
      if (hash) {
        const cmp = document.getElementById(hash);
        if (cmp) {
          cmp.scrollIntoView();
        }
      } else {
        window.scrollTo(0, 0);
      }
    });
  } 
```

**Comment by paulogr** [comment]
I simple do this

```
@ViewChild('myanchor') myanchor
...
...
gotoMyAnchor() {
  this.myanchor.nativeElement.scrollIntoView()
}
```

Works all the time :)
Hope it helps.

**Comment by ehegnes** [comment]
As I understand it, @paulogr's method is a more traditional way to do something like this in Angular, since we're not supposed to be touching the DOM ourselves. Right?

**Comment by ecerta** [comment]
@poulogr 's approach doesn't account for tabindex adjustment for keyboard-only users, though. Someone using a keyboard will hit enter on that link, the page will scroll, and then when they go to tab again, the page'll jump right back up to where it was.

**Comment by MauricioQitPlus** [comment]
This is by far the most elegant solution I've seen so far... don't remember who came up with it but I guess this is how you are supposed to do it. The fragment attribute just changes the URL but don't jump into the section, so you need to add the anchor tag within the tag you are using to complete the trick.

  <div [routerLink]="['pagex']" fragment="sectiony">
    <a href="#sectiony">Jump to 'Section Y' anchor in page X  </a>
  </div>

**Comment by mgb389** [comment]
This is by far the most straightforward solution I've seen so far... don't remember who came up with it but I guess this is how you are supposed to do it. The fragment attribute just changes the URL but don't jump into the section, so you need to add the anchor tag within the tag you are using to complete the trick.


```
  <div [routerLink]="['pagex']" fragment="sectiony">
           <a href="#sectiony">Jump to 'Section Y' anchor in page X  </a>
  </div>
```

**Comment by bluefire2121** [comment]
When will the anchor service be added to Angular? I need this to build accessible apps and not having this feature isolates an enormous community. Please prioritize getting this developed. Thank you.

**Comment by omaracrystal** [comment]
@jorgjanke Your solution will navigate to the correct id on the page but then disregards the styling for routerLinkActive. 

I'm also having a hard time applying the "fragment" attribute value to navigate to the element with that id... while **routerLinkActive stays intact**... 

The following applies the correct active styling on click - but doesn't go to the correct route on the page (#hash) 
```
   <li class="nav-item">
      <a [routerLink]='link'
         routerLinkActive="router-link-active"
         fragment="services"
         (click)="goToRoute(this)">Services</a>
    </li>
```

**Comment by briancodes** [comment]
@omaracrystal That is similar to how what i used also. Except instead of using `(click)` I have subscribed to fragment change - this also covers the case where the user manually refreshes:
`this.route.fragment.subscribe(this.handleFragmentChange);` - where `route` is the `ActivatedRoute`

**Comment by jiangjianyu** [comment]
Was this bug have fixed?

**Comment by SteamWind** [comment]
@jiangjianyu as you can see, the issue is Open...

**Comment by ozknemoy** [comment]
may be this code may help someone
```
@Directive({
  selector : '[href]',
  host : {
    '(click)' : 'click($event)'
  },
})
export class HrefDirective {
  @Input() private href;
  private target = this.el.nativeElement.getAttribute('target');

  constructor(private el: ElementRef) {}

  click(event) {
    window.open(this.href, this.target)
  }
}
```

`<a href="#section-1" target="_self" class="header_nav--link">Some link</a>`

**Comment by brandonroberts** [comment]
Fixed via #20030

**Comment by rtm** [comment]
@brandonroberts I'm confused. You say this is "fixed", pointing to a patch which restores scroll position when returning to a page, but isn't this issue (see the title) originally about correct handling of hashes (fragments), or am I missing something?

**Comment by brandonroberts** [comment]
@rtm the PR adds support for handling fragments in addition to restoring thr scroll position when navigating between pages.

**Comment by MrGrigri** [comment]
@brandonroberts, that does not fix either the accessibility issue or CSS issue. 

1. Accessibility: When a keyboard user clicks the link with the fragment, the page is not only supposed to scroll into view (animated or not), but it's also supposed to change the `document.activeElement` to the new targeted location. 

2. CSS: URLs with an # followed by an anchor name link to a certain element within a document. The element being linked to is the target element. This does not happen.

**Comment by MrGrigri** [comment]
This does not solve the CSS `:target` pseudo-selector issue.

**Comment by trotyl** [comment]
@SteamWind This issue is only about scroll position, so what do you expect?

**Comment by SteamWind** [comment]
Maybe I misunderstood. Is it now possible to scroll to an hash when your already on the same route?

**Comment by trotyl** [comment]
Fragments are also part of the URL:

https://github.com/angular/angular/blob/15e671ec5a7527dae9c006073ff6b25e85142e16/packages/router/test/bootstrap.spec.ts#L312-L318

**Comment by trotyl** [comment]
@MrGrigri URL hash is about [scroll position](https://html.spec.whatwg.org/#scroll-to-fragid), isn't it? Or what are the other semantics a fragment defined by standards? And that's what [anchorScroll](https://angular.io/api/router/ExtraOptions#anchorScrolling) feature meant for.

If you have extra assumption about the fragment, that's already your own business logic. It could be fine to open new feature request for them, but which is indeed not part of this issue talking about:

> If I have a URL with a hash, when I navigate to it, the hash is dropped from the URL and the page does not jump to the anchor tag.

**Comment by MrGrigri** [comment]
Thanks @trotyl, I wasn't aware of the `anchorScroll` feature. I was able to get the scolling to work. However, there are still two things that don't work regarding the standard for [navigating to a fragment](https://html.spec.whatwg.org/#scroll-to-fragid). Mainly focus, and the [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:target) `:target` selector. 

Should I open a new issue to cover these two?

**Comment by trotyl** [comment]
It's a browser bug that `:target` selector doesn’t work with History API, see https://github.com/angular/angular/issues/21193 for more information.

**Comment by MrGrigri** [comment]
And what about the focus? It should focus the targeted element so when the tab key is pressed on the keyboard it continues from there. This is critical for accessibility.

**Comment by trotyl** [comment]
Sounds reasonable to me, better to open a new feature request for focusing behavior. It would likely also be put behind a flag for non-breaking requirement.

**Comment by phutaneVinayak** [comment]
i did as following  
in -- header.component.html
<a class="nav-link" [routerLink]="['about-us']" fragment="contact-us" preserveFragment>Contact Us</a>

in about-us.component.html
<section id="contact-us" class="bg-white">
<section>
 ----------------------------------------------------------------------------------------
nothing working. 
# contact-us is not added in routing . 
Any suggestion  ?

i am new bee in angular. :)

**Comment by phutaneVinayak** [comment]
> i did as following
> in -- header.component.html
> `<a class="nav-link" [routerLink]="['about-us']" fragment="contact-us" preserveFragment> Contact Us</a>`
> 
> in about-us.component.html
> `<section id="contact-us" class="bg-white"></section>`
> 
> hash is not adding in router.
> Any suggestion ?
> 
> i am new bee in angular. :)

issue resolve. i did it as  following :-

first i remove routerLink from a tag and add function on it .
`<a class="nav-link" (click)="navigateToContactUs()" >Contact Us</a>`

and in the function 
`this.router.navigate(['about-us'], {fragment: 'contact-us'})`

and the result is
`http://localhost:4200/about-us#contact-us`

**Comment by cbejensen** [comment]
I am doing what @phutaneVinayak suggested, and I do see the URL update with the fragment, but I do not see it scroll to that fragment's corresponding element. [Here's an example.](https://stackblitz.com/edit/router-fragment)

Both of these produce the fragment in the URL, but neither seems to scroll the page:

```ts
this.router.navigate(['/'], { fragment: 'test' });
```
```ts
this.location.go('#test');
```

I know the HTML element is ID'd correctly because if I click in the address bar and hit Enter, it works.

**Comment by phutaneVinayak** [comment]
> I am doing what @phutaneVinayak suggested, and I do see the URL update with the fragment, but I do not see it scroll to that fragment's corresponding element. [Here's an example.](https://stackblitz.com/edit/router-fragment?file=app%2Fapp.component.ts)
> 
> Both of these produce the fragment in the URL, but neither seems to scroll the page:
> 
> ```ts
> this.router.navigate(['/'], { fragment: 'test' });
> ```
> 
> ```ts
> this.location.go('#test');
> ```
> 
> I know the HTML element is ID'd correctly because if I click in the address bar and hit Enter, it works.

Hi @cbejensen. I am working on your stackBiltz, seem you are using angular 4 and it does not provide    
<pre><code> anchorScrolling: 'enabled'  </code></pre> options in routing config. so it will not definitely scroll to that id element. I need to find some workaround for that. give some time 

HappyCoding

**Comment by phutaneVinayak** [comment]
> I am doing what @phutaneVinayak suggested, and I do see the URL update with the fragment, but I do not see it scroll to that fragment's corresponding element. [Here's an example.](https://stackblitz.com/edit/router-fragment?file=app%2Fapp.component.ts)
> 
> Both of these produce the fragment in the URL, but neither seems to scroll the page:
> 
> ```ts
> this.router.navigate(['/'], { fragment: 'test' });
> ```
> 
> ```ts
> this.location.go('#test');
> ```
> 
> I know the HTML element is ID'd correctly because if I click in the address bar and hit Enter, it works.

Hi, @cbejensen
 I found the solution. Please check below code. It might be not a good way but it's solving the problem. 

<pre>
 <code>
    this.router.navigate(['/'], {fragment: 'test'}).then(res => {
      console.log(res);
        let testElement = document.getElementById('test');
        console.log("testElement", testElement)
        if (testElement != undefined) testElement.scrollIntoView();
    })
 </code>
</pre>

**Comment by janstapel** [comment]
> Hi, @cbejensen
> I found the solution. Please check below code. It might be not a good way but it's solving the problem.
> 
>  ```
> 
>     this.router.navigate(['/'], {fragment: 'test'}).then(res => {
>       console.log(res);
>         let testElement = document.getElementById('test');
>         console.log("testElement", testElement)
>         if (testElement != undefined) testElement.scrollIntoView();
>     })
>  
> ```
You don't even need the hash for that.. for me that looks elegant (but idk if it's good practice to navigate within pages without indicating it in URL)..
It neither looks very efficient so another solution for that would be nice..

`		this.router.navigate([target]).then(()=>{
			window.location.hash=fragment;
			
});`
Is also working.. but not if you want to navigate directly to a position of a page, coming from a different route..
