### ISSUE TITLE
[beta.16 regression] ngFor and ChangeDetectionStrategy.OnPush not updating with .markForCheck()

### ISSUE THREAD

**Issue by stringham** [angular/angular#8315]
This may be related to #8242 but that issue is specifically about event handlers not causing the change detector to run, and I saw that they got it working by adding a call to `.markForCheck()` on the ChangeDetectorRef.

I'm seeing that change detection isn't working even with a `.markForCheck()` call.

I have a component that keeps a count that increments on an interval, note it marks the change detector after changing the count.

```javascript
var Component1 = ng.core
    .Component({
        selector:"cmp1",
        template:"<div>Count: {{count}}</div>",
    })
    .Class({
        constructor:[
            ng.core.ChangeDetectorRef,
            function(cdr){
              this.count = 0;
              setInterval(function(){
                this.count++;
                cdr.markForCheck();
              }.bind(this), 500);

            }
        ]
    });
```

I have another component that uses that component in an *ngFor with changeDetectionStrategy.OnPush

```javascript
var Component2 = ng.core
    .Component({
        selector:"cmp2",
        template:'<div>Component 2 (ngfor):</div><cmp1 *ngFor="#a of [1,2]"></cmp1>',
        directives:[Component1],
        changeDetection: ng.core.ChangeDetectionStrategy.OnPush,
    })
    .Class({
        constructor:[
            function(){}
        ]
    });
```

and another component that uses the first component twice, not in an *ngFor

```
var Component3 = ng.core
    .Component({
        selector:"cmp3",
        template:'<div>Component 3 (no ngfor):</div><cmp1></cmp1><cmp1></cmp1>',
        directives:[Component1],
        changeDetection: ng.core.ChangeDetectionStrategy.OnPush,
    })
    .Class({
        constructor:[
            function(){}
        ]
    });
```

and the root app uses all three components.

```javascript
var AppComponent = ng.core
    .Component({
        selector:'test-app',
        template:`
            <cmp1></cmp1>
            <cmp2></cmp2>
            <cmp3></cmp3>
        `,
        directives:[
            Component1,
            Component2,
            Component3,
        ]
    })
    .Class({
        constructor:[
            function() {
                window.app = this;
            }
        ]
    });
```

In beta.16 component 1 and 3 update, but component 2 stays at 0.
In beta.15 they all update as expected.

Here's a plnkr of it not working in beta.16: http://plnkr.co/edit/waoh6evhRvOvX1yMuOKG?p=preview
Here's the same thing in beta.15: http://plnkr.co/edit/a5POuqddYbG5C9oVuzA8?p=preview

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8242

**Comment by frankpepermans** [comment]
I'm also seeing this issue, my app is also heavily dependent on OnPush and markForCheck().

Completely broken in b16 and b17

**Comment by born2net** [comment]
same here, I was going to test 0.17 in hopes the team fixed it, but I guess no luck :(

**Comment by bennylut** [comment]
Same here, almost all my components uses on push detection as I think its much more predictable, without this issue fixed I am stuck at b15

**Comment by Ristaaf** [comment]
Same here, a combination of markForCheck() and detectChanges() (to actually trigger a check) is a workaround for me (implemented on a childcomponent of a component that is in an ngFor and has onPush and changes the datamodel for the complete application), but it kind of defeats the idea of onPush, and I am also not sure how much it will affect my complete application (haven't tested enough yet, and it will probably only check the childcomponent for changes not the parent)

**Comment by bennylut** [comment]
Anyone tested this issue on rc0? I am planing a migration soon and would like to know if it is safe.
Thanks?

**Comment by tycho01** [comment]
For me the issue appears unchanged in RC1 from beta 16. I'm trying `tick()`, `flushMicrotasks()`, `fixture.detectChanges()`, `comp.cdr.markForCheck()` -- none are helping. In beta.15, it was fine without any additional hacks.

**Comment by born2net** [comment]
can't believe ng2 is in RC.1 and basic onPush is still broken :(

**Comment by tycho01** [comment]
I can't believe there's 1.4k+ open issues with plenty months old that seem largely ignored. :P

**Comment by gonzofish** [comment]
yeah, the team had been working round the clock towards ng-conf, Igor mentioned in an AMA that they had a lot of cleanup they needed to do when they got back

**Comment by born2net** [comment]
tx for update

**Comment by dominique-mueller** [comment]
Any news on this one yet? This issue really breaks a lot of components ...

**Comment by gonzofish** [comment]
I updated to RC1 and my issues with OnPush seemed to be alleviated, not sure if it would help others...maybe branch your code and try it?

**Comment by tycho01** [comment]
I'm now under the impression it's working for me outside of tests, though
inside tests I'm still getting failures in tests that started for me with
beta 16. Would be glad to see others' reports to confirm.

**Comment by dominique-mueller** [comment]
As described in #6948 providing a trackBy function for the ngFor loop fixed my issues with OnPush. I'm using RC.1 at the moment.
But still, shouldn't this work without a trackBy function?

**Comment by zoechi** [comment]
@dominique-mueller What datatype are the items in the array you are iterating over with `ngFor`? AFAIK for primitive types `trackBy` is required.

**Comment by dominique-mueller** [comment]
Ha! At first I've used a Map (from immutable.js) - ngFor over a Map requires the trackBy function to be defined. Using a List (also from immutable.js) seems to work without it.
So for me, everything works fine now. So as the other ones mentioned above, maybe the issue is fixed?

**Comment by tycho01** [comment]
Correction: I've tried a bit further, and I am still experiencing change detection issues outside of tests as well, where neither `markForCheck` nor `trackBy` are helping; not for every loop, nor dependent on Immutable structures (still getting it with just arrays). Still trying to figure out the elements required for a minimal reproduction though, not sure if different from @stringham's. Unfortunately that's complicated a bit with a dozen of my tests [failing to run](https://github.com/angular/angular/issues/7084) as well.

**Comment by tycho01** [comment]
@dominique-mueller: I fixed all my issues now. Not using Immutable.js, so can't speak for that, but RC1 seems fine. Sorry for the confusion I caused with my earlier report.

**Comment by vicb** [comment]
Is this still an issue with 2.0.0 ?
