### ISSUE TITLE
ngIf on Observable list length prevents ngFor to loop through Observable list with async pipe

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9641]
In case of an Observable array, in component template if we add *ngIf =" (list$ | async)?.length>0" it doesn't loops through the child *ngFor.

For example if I have below Observable list in the component:

`list$: Observable<any[]>;`

and below in template:

```
<div>
    Length: {{(list$ | async)?.length}}
    <div *ngIf="(list$ | async)?.length>0">
        <ul>
            <li *ngFor="let item of (list$ | async)">
                {{item.name}}
            </li>
        </ul>
    </div>
</div>
```

It seems that (list$ | async)?.length gives us the length of the list but the list isn't printed on the screen.

Whereas if I remove ngIf it start working:

```
<div>
    Length: {{(list$ | async)?.length}}
        <ul>
            <li *ngFor="let item of (list$ | async)">
                {{item.name}}
            </li>
        </ul>
</div>
```

**Comment by vicb** [comment]
Please provide a plunker.

One possible issue is that `| async` will subscribe each time is is called.

**Comment by zoechi** [comment]
Crossref http://stackoverflow.com/questions/38057537/how-to-check-length-of-the-an-observable-array

**Comment by naveedahmed1** [comment]
Please have a look at http://plnkr.co/edit/5KBEVj5Hhtx0BB5v3vVg?p=preview if you remove <div *ngIf="(todos$ | async)?.length>0"> from todo.component, it will start displaying list.

**Comment by zoechi** [comment]
> It seems that (list$ | async)?.length gives us the length of the list but the list isn't printed on the screen.

![image](https://cloud.githubusercontent.com/assets/405837/16393413/f844391e-3cb0-11e6-8777-d5f14c8a9cc7.png)

Can you please update the Plunker so it demonstrates the problem?

**Comment by wiredprogrammer** [comment]
In my experience I've had a similar issue.  It feels like it doesn't always reevaluate the expression.

**Comment by vicb** [comment]
is this still an issue ?

**Comment by naveedahmed1** [comment]
Yes, it seems. Please have a look at above plunker.

**Comment by 17twenty** [comment]
Can confirm still an issue in release. 

`
<div  class="well" *ngIf="(users$ | async)?.length>0">
  <div *ngFor="let user of users | async"
        class="search-result" >
        <a routerLink="/user/{{user.id}}" routerLinkActive="active">
    {{user.given_name}} {{user.family_name}}</a>
  </div>
</div>
`

**Comment by zoechi** [comment]
Why are you using `Users$` in `*ngIf` and `users` in `*ngFor`?

**Comment by 17twenty** [comment]
I was cleaning it up. Ignore that typo

**Comment by zoechi** [comment]
You could edit the post and fix the typo

**Comment by 17twenty** [comment]
Done

**Comment by Almar** [comment]
Hey guys, any update on this?
A ngIf on a simple boolean has the same effect!
See [plunker](http://plnkr.co/edit/qCKhKCmjXutkozxXZ9A1?p=preview). This list is shown or hidden based on a boolean. First pass the list is shown but after two 'toggles' the list is not shown anymore.

**Comment by DzmitryShylovich** [comment]
> common@2.0.0-rc.3

**Comment by brankoiliccc** [comment]
This is still an issue in 4.0.2

      <div` *ngIf="(addressResponse | async )?.addresses?.length >0">
          <div  *ngFor="let item of (addressResponse | async )?.addresses">
                    ....... item not printing
          </div>
      </div>

**Comment by huiguang-liang** [comment]
Confirmed that it is still an issue in the latest release.

```html
<ul class="custom-dropdown" *ngIf="(heroes | async)?.length > 0">
  <li *ngFor="let hero of heroes | async">{{hero.name}}</li>
</ul>
```

Where `heroes: Observable<Hero[]>`. The `<li></li` is not rendering.

**Comment by kylecordes** [comment]
Does anyone have a plunkr producing this on current Angular? I have seen issues that initially appear very similar to this, but turn out instead to be a consequence of the observable being subscribed again when the If becomes true and the For enters the view.

**Comment by Dynalon** [comment]
@kylecordes I agree, the only plunkr here is not faulty (does not contain a bug in angular) at all as I reasoned in my post. Al other responses claiming that the error persist and do not provide a plunkr should be discarded, as it is more likely the Observables are used/suscribed in a wrong way.

**Comment by huiguang-liang** [comment]
@Dynalon @kylecordes please see this [plnkr](https://plnkr.co/edit/MgwBEpAsANLrZrJ5EHcW).

I only added `*ngIf="(heroes | async)?.length > 0"` to line 4 of `app/hero-search.component.html`.

Its literally the same code as given in the Angular tutorial [here](https://angular.io/resources/live-examples/toh-6/ts/eplnkr.html).

**Comment by Dynalon** [comment]
@huiguang-liang Yes and by adding it, you changed the semantic of the search: The `| async` pipe inside the `*ngFor` will now subscribe to the `hero` 0bservable AFTER the search result has been received; there is no bug in angular here, but in your code!

Observables are by default cold and do NOT cache any value (unlike promises). That is, if you subscribe after an item is emitted you will not get that item. The solution is to turn the cold observable into a hot observable which cashes the last element using `publishReplay(1).refCount()`. This is the only change I made (plus importing publishReplay) of your plunkr and now it works fine here: https://plnkr.co/edit/jjtJkTaEeFWZd8wKjP5O?p=preview

I agree that this issue is mostly about people not understanding RxJS/Observables; there is no real plunkr here that shows an issue in angular (except for relying on the hard to grasp RxJS which is another topic).

@huiguang-liang Look at my plunkr and try to understand the difference between hot and cold observables (and read about ReplaySubject vs. BehaviourSubject vs. Subject).

**Comment by huiguang-liang** [comment]
@Dynalon, thanks for clarifying this, indeed it works. Good explanation too.

**Comment by kylecordes** [comment]
I generally do the same thing as @Dynalon  said: `.publishReplay(1).refCount()`.

**Comment by afriedma** [comment]
But this code creates 2 subscribers to heroes, should there only be 1?

**Comment by Delagen** [comment]
As for angular 4 try this
```
<ng-container *ngIf="heroes|async;let heroesItems">
	<ul class="custom-dropdown" *ngIf="heroesItems.length > 0">
		<li *ngFor="let hero of heroesItems">{{hero.name}}</li>
	</ul>
</ng-container>

```

**Comment by afriedma** [comment]
This approach works like a charm, here is fixed plunker https://plnkr.co/edit/yW3sDygDwCb86hP29tdc?p=preview

Thanks a lot for your answer.

**Comment by huiguang-liang** [comment]
@Delagen, great alternative! Works perfectly, thanks for the suggestion.

**Comment by brianmay** [comment]
Looks good to me. I would suggest that this needs to be better documented. i.e. the naive solution given at the top, why the naive solution doesn't work, and some of the alternative options listed here.

Which raises the question - where should it be documented? Maybe here? https://angular.io/docs/ts/latest/api/common/index/AsyncPipe-pipe.html

**Comment by pavel-blagodov** [comment]
the issue might be relevant to https://github.com/angular/angular/issues/19591

**Comment by simeyla** [comment]
Use `shareReplay()` instead of `publishReplay(1).refCount()`

**Comment by vicb** [comment]
Long list of comments, let's try to sum up:

```
<div>
    Length: {{(list$ | async)?.length}}
    <div *ngIf="(list$ | async)?.length>0">
        <ul>
            <li *ngFor="let item of (list$ | async)">
                {{item.name}}
            </li>
        </ul>
    </div>
</div>
```

2 problems with this code:
- the `<li>` is created only after `(list$ | async)?.length>0` becomes true. At this point the Observable has already emitted the list and it's not considered by the ngFor.
- multiple `| async` will create multiple subscription (which may or may not be a problem).

 Using `shareReplay()` could be one way to solve the issue
